- // MIR for `get_query` before Inline
+ // MIR for `get_query` after Inline
  
  fn get_query(_1: &T) -> () {
      debug t => _1;                       // in scope 0 at $DIR/dyn_trait.rs:+0:31: +0:32
      let mut _0: ();                      // return place in scope 0 at $DIR/dyn_trait.rs:+0:38: +0:38
      let _2: &<Q as Query>::C;            // in scope 0 at $DIR/dyn_trait.rs:+1:9: +1:10
      let mut _3: &T;                      // in scope 0 at $DIR/dyn_trait.rs:+1:22: +1:23
      let mut _4: &<Q as Query>::C;        // in scope 0 at $DIR/dyn_trait.rs:+2:23: +2:24
      scope 1 {
          debug c => _2;                   // in scope 1 at $DIR/dyn_trait.rs:+1:9: +1:10
+         scope 2 (inlined try_execute_query::<<Q as Query>::C>) { // at $DIR/dyn_trait.rs:34:5: 34:25
+             debug c => _4;               // in scope 2 at $DIR/dyn_trait.rs:26:36: 26:37
+             let mut _5: &dyn Cache<V = <Q as Query>::V>; // in scope 2 at $DIR/dyn_trait.rs:27:14: 27:15
+             let mut _6: &<Q as Query>::C; // in scope 2 at $DIR/dyn_trait.rs:27:14: 27:15
+             scope 3 (inlined mk_cycle::<<Q as Query>::V>) { // at $DIR/dyn_trait.rs:27:5: 27:16
+                 debug c => _5;           // in scope 3 at $DIR/dyn_trait.rs:20:27: 20:28
+                 let mut _7: &dyn Cache<V = <Q as Query>::V>; // in scope 3 at $DIR/dyn_trait.rs:21:5: 21:22
+             }
+         }
      }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/dyn_trait.rs:+1:9: +1:10
          StorageLive(_3);                 // scope 0 at $DIR/dyn_trait.rs:+1:22: +1:23
          _3 = &(*_1);                     // scope 0 at $DIR/dyn_trait.rs:+1:22: +1:23
          _2 = <Q as Query>::cache::<T>(move _3) -> bb1; // scope 0 at $DIR/dyn_trait.rs:+1:13: +1:24
                                           // mir::Constant
                                           // + span: $DIR/dyn_trait.rs:33:13: 33:21
                                           // + user_ty: UserType(0)
                                           // + literal: Const { ty: for<'a> fn(&'a T) -> &'a <Q as Query>::C {<Q as Query>::cache::<T>}, val: Value(<ZST>) }
      }
  
      bb1: {
          StorageDead(_3);                 // scope 0 at $DIR/dyn_trait.rs:+1:23: +1:24
          StorageLive(_4);                 // scope 1 at $DIR/dyn_trait.rs:+2:23: +2:24
          _4 = &(*_2);                     // scope 1 at $DIR/dyn_trait.rs:+2:23: +2:24
-         _0 = try_execute_query::<<Q as Query>::C>(move _4) -> bb2; // scope 1 at $DIR/dyn_trait.rs:+2:5: +2:25
+         StorageLive(_5);                 // scope 2 at $DIR/dyn_trait.rs:27:14: 27:15
+         StorageLive(_6);                 // scope 2 at $DIR/dyn_trait.rs:27:14: 27:15
+         _6 = _4;                         // scope 2 at $DIR/dyn_trait.rs:27:14: 27:15
+         _5 = move _6 as &dyn Cache<V = <Q as Query>::V> (Pointer(Unsize)); // scope 2 at $DIR/dyn_trait.rs:27:14: 27:15
+         StorageDead(_6);                 // scope 2 at $DIR/dyn_trait.rs:27:14: 27:15
+         StorageLive(_7);                 // scope 3 at $DIR/dyn_trait.rs:21:5: 21:22
+         _7 = _5;                         // scope 3 at $DIR/dyn_trait.rs:21:5: 21:22
+         _0 = <dyn Cache<V = <Q as Query>::V> as Cache>::store_nocache(move _7) -> bb2; // scope 3 at $DIR/dyn_trait.rs:21:5: 21:22
                                           // mir::Constant
-                                          // + span: $DIR/dyn_trait.rs:34:5: 34:22
-                                          // + literal: Const { ty: for<'a> fn(&'a <Q as Query>::C) {try_execute_query::<<Q as Query>::C>}, val: Value(<ZST>) }
+                                          // + span: $DIR/dyn_trait.rs:21:7: 21:20
+                                          // + literal: Const { ty: for<'a> fn(&'a dyn Cache<V = <Q as Query>::V>) {<dyn Cache<V = <Q as Query>::V> as Cache>::store_nocache}, val: Value(<ZST>) }
      }
  
      bb2: {
+         StorageDead(_7);                 // scope 3 at $DIR/dyn_trait.rs:21:21: 21:22
+         StorageDead(_5);                 // scope 2 at $DIR/dyn_trait.rs:27:15: 27:16
          StorageDead(_4);                 // scope 1 at $DIR/dyn_trait.rs:+2:24: +2:25
          StorageDead(_2);                 // scope 0 at $DIR/dyn_trait.rs:+3:1: +3:2
          return;                          // scope 0 at $DIR/dyn_trait.rs:+3:2: +3:2
      }
  }
  
