- // MIR for `one` before Inline
+ // MIR for `one` after Inline
  
  fn one() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/inline_cycle.rs:+0:10: +0:10
      let _1: ();                          // in scope 0 at $DIR/inline_cycle.rs:+1:5: +1:24
+     scope 1 (inlined <C as Call>::call) { // at $DIR/inline_cycle.rs:14:5: 14:24
+     }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/inline_cycle.rs:+1:5: +1:24
-         _1 = <C as Call>::call() -> bb1; // scope 0 at $DIR/inline_cycle.rs:+1:5: +1:24
+         _1 = <A<C> as Call>::call() -> bb1; // scope 1 at $DIR/inline_cycle.rs:43:9: 43:23
                                           // mir::Constant
-                                          // + span: $DIR/inline_cycle.rs:14:5: 14:22
-                                          // + literal: Const { ty: fn() {<C as Call>::call}, val: Value(<ZST>) }
+                                          // + span: $DIR/inline_cycle.rs:43:9: 43:21
+                                          // + literal: Const { ty: fn() {<A<C> as Call>::call}, val: Value(<ZST>) }
      }
  
      bb1: {
          StorageDead(_1);                 // scope 0 at $DIR/inline_cycle.rs:+1:24: +1:25
          _0 = const ();                   // scope 0 at $DIR/inline_cycle.rs:+0:10: +2:2
          return;                          // scope 0 at $DIR/inline_cycle.rs:+2:2: +2:2
      }
  }
  
