- // MIR for `preserve_debuginfo_3` before SimplifyCfg-final
+ // MIR for `preserve_debuginfo_3` after SimplifyCfg-final
  
  fn preserve_debuginfo_3(_1: &Foo, _2: bool) -> i32 {
      debug foo_a => _3;
      debug foo_b => _4;
      debug foo_c => _5;
      let mut _0: i32;
      let mut _3: &i32;
      let mut _4: &i64;
      let mut _5: &i32;
  
      bb0: {
-         switchInt(copy _2) -> [1: bb1, otherwise: bb2];
+         switchInt(copy _2) -> [1: bb2, otherwise: bb1];
      }
  
      bb1: {
-         // DBG: _3 = &((*_1).0: i32);
-         goto -> bb3;
-     }
- 
-     bb2: {
          // DBG: _4 = &((*_1).1: i64);
          _0 = copy ((*_1).2: i32);
          return;
      }
  
-     bb3: {
+     bb2: {
+         // DBG: _3 = &((*_1).0: i32);
          // DBG: _5 = &((*_1).2: i32);
          _0 = copy ((*_1).0: i32);
          return;
      }
  }
  
