- // MIR for `preserve_debuginfo_2` before SimplifyCfg-final
+ // MIR for `preserve_debuginfo_2` after SimplifyCfg-final
  
  fn preserve_debuginfo_2(_1: &Foo) -> i32 {
      debug foo_a => _2;
      debug foo_b => _3;
      debug foo_c => _4;
      let mut _0: i32;
      let mut _2: &i32;
      let mut _3: &i64;
      let mut _4: &i32;
  
      bb0: {
-         goto -> bb1;
-     }
- 
-     bb1: {
          // DBG: _2 = &((*_1).0: i32);
-         nop;
-         goto -> bb2;
-     }
- 
-     bb2: {
          // DBG: _3 = &((*_1).1: i64);
-         nop;
          _0 = copy ((*_1).2: i32);
          // DBG: _4 = &((*_1).2: i32);
-         nop;
          return;
      }
  }
  
