- // MIR for `invalid_debuginfo` before SingleUseConsts
+ // MIR for `invalid_debuginfo` after SingleUseConsts
  
  fn invalid_debuginfo() -> () {
      let mut _0: ();
      let _1: ();
      scope 1 (inlined foo) {
          let _2: ();
          let mut _3: &isize;
          let _4: &isize;
          let _5: isize;
          let mut _6: &isize;
          scope 2 (inlined bar) {
-             debug x => _4;
+             debug x => const foo::promoted[0];
              let _7: isize;
              let mut _9: &isize;
              let _10: &isize;
              scope 3 {
-                 debug a => _7;
+                 debug a => const 1_isize;
                  let mut _8: &isize;
                  scope 4 {
-                     debug z => _4;
+                     debug z => const foo::promoted[0];
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_1);
          StorageLive(_4);
-         _4 = const foo::promoted[0];
+         nop;
          StorageLive(_7);
-         _7 = const 1_isize;
-         // DBG: _4 = &_7;
+         nop;
          StorageDead(_7);
-         _1 = const ();
+         nop;
          StorageDead(_4);
          StorageDead(_1);
          _0 = const ();
          return;
      }
  }
  
