- // MIR for `move_simple` before DeadStoreElimination
+ // MIR for `move_simple` after DeadStoreElimination
  
  fn move_simple(_1: i32) -> () {
      debug x => _1;
      let mut _0: ();
      let _2: ();
      let mut _3: i32;
      let mut _4: i32;
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = _1;
          StorageLive(_4);
          _4 = _1;
          _2 = use_both(move _3, move _4) -> [return: bb1, unwind continue];
      }
  
      bb1: {
          StorageDead(_4);
          StorageDead(_3);
          StorageDead(_2);
          _0 = const ();
          return;
      }
  }
  
