- // MIR for `move_simple` before DeadStoreElimination-final
+ // MIR for `move_simple` after DeadStoreElimination-final
  
  fn move_simple(_1: i32) -> () {
      debug x => _1;
      let mut _0: ();
      let _2: ();
      let mut _3: i32;
      let mut _4: i32;
  
      bb0: {
          StorageLive(_2);
-         _2 = use_both(_1, _1) -> [return: bb1, unwind continue];
+         _2 = use_both(_1, move _1) -> [return: bb1, unwind continue];
      }
  
      bb1: {
          StorageDead(_2);
          _0 = const ();
          return;
      }
  }
  
