test_utils::marks!(
    inserts_parens_for_function_calls
    goto_definition_works_for_macros
    goto_definition_works_for_methods
    goto_definition_works_for_fields
    goto_definition_works_for_named_fields
    call_info_bad_offset
    dont_complete_current_use
);
