#!/usr/bin/perl -w

$indent = 0;
while (<>) {
    if (/^rust: ">>/) {
        $indent += 1;
    } elsif (/^rust: "<</) {
        $indent -= 1;
    }

    printf "%03d  ", $indent;
    for ($i = 0; $i < $indent; $i++) {
        printf("  ");
    }
    print;
}

