[files]
extend-exclude = [
    # exclude git (sub)modules and generated content
    "compiler/rustc_codegen_gcc",
    "compiler/rustc_codegen_cranelift",
    "compiler/rustc_baked_icu_data",
    "library/backtrace",
    "library/stdarch",
    # generated lorem ipsum texts
    "library/alloc/benches/str.rs",
    "library/alloc/tests/str.rs",
]

[default.extend-words]
# Add exclusions here, lines should be like `x = "x"`, where `x` is excluded word.
#
# Also see docs: https://github.com/crate-ci/typos/blob/v1.28.2/docs/reference.md
thir = "thir"
padd = "padd"
rplace = "rplace"
arange = "arange"
rela = "rela"
unstalled = "unstalled"
taits = "taits"
Datas = "Datas"
splitted = "splitted"
leafs = "leafs"
Lits = "Lits"
makro = "makro"
optin = "optin"
parm = "parm"
unparseable = "unparseable"
matcheable = "matcheable"
smove = "smove"
childs = "childs"
filetimes = "filetimes"

[default.extend-identifiers]
ERROR_FILENAME_EXCED_RANGE = "ERROR_FILENAME_EXCED_RANGE"
DNS_ERROR_INVAILD_VIRTUALIZATION_INSTANCE_NAME = "DNS_ERROR_INVAILD_VIRTUALIZATION_INSTANCE_NAME"
ERROR_DS_FILTER_USES_CONTRUCTED_ATTRS = "ERROR_DS_FILTER_USES_CONTRUCTED_ATTRS"
ERROR_DS_NOT_AUTHORITIVE_FOR_DST_NC = "ERROR_DS_NOT_AUTHORITIVE_FOR_DST_NC"
ERROR_MCA_OCCURED = "ERROR_MCA_OCCURED"
ERRNO_ACCES = "ERRNO_ACCES"
tolen = "tolen"
pard = "pard"

[default]
extend-ignore-words-re = [
    # words with length <= 3 chars is likely noise
    "^[a-zA-Z]{1,3}$",
]

extend-ignore-re = [
    # ignore this intensional typo examples
    "/// 1 \\| #\\[cfg\\(widnows\\)\\]",
    "/// warning: unexpected `cfg` condition name: `widnows`",
    "/// #\\[cfg\\(widnows\\)\\]",
    "\\.arg\\(\"Oh no, a tpyo!\"\\)",
    # string used in benches
    "\"core::iter::adapters::Copie\"",
]
