- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/array_index.rs:4:11: 4:11
      let _1: u32;                         // in scope 0 at $DIR/array_index.rs:5:9: 5:10
      let mut _2: [u32; 4];                // in scope 0 at $DIR/array_index.rs:5:18: 5:30
      let _3: usize;                       // in scope 0 at $DIR/array_index.rs:5:31: 5:32
      let mut _4: usize;                   // in scope 0 at $DIR/array_index.rs:5:18: 5:33
      let mut _5: bool;                    // in scope 0 at $DIR/array_index.rs:5:18: 5:33
      scope 1 {
          debug x => _1;                   // in scope 1 at $DIR/array_index.rs:5:9: 5:10
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/array_index.rs:5:9: 5:10
          StorageLive(_2);                 // scope 0 at $DIR/array_index.rs:5:18: 5:30
          _2 = [const 0u32, const 1u32, const 2u32, const 3u32]; // scope 0 at $DIR/array_index.rs:5:18: 5:30
                                           // ty::Const
                                           // + ty: u32
                                           // + val: Value(Scalar(0x00000000))
                                           // mir::Constant
                                           // + span: $DIR/array_index.rs:5:19: 5:20
                                           // + literal: Const { ty: u32, val: Value(Scalar(0x00000000)) }
                                           // ty::Const
                                           // + ty: u32
                                           // + val: Value(Scalar(0x00000001))
                                           // mir::Constant
                                           // + span: $DIR/array_index.rs:5:22: 5:23
                                           // + literal: Const { ty: u32, val: Value(Scalar(0x00000001)) }
                                           // ty::Const
                                           // + ty: u32
                                           // + val: Value(Scalar(0x00000002))
                                           // mir::Constant
                                           // + span: $DIR/array_index.rs:5:25: 5:26
                                           // + literal: Const { ty: u32, val: Value(Scalar(0x00000002)) }
                                           // ty::Const
                                           // + ty: u32
                                           // + val: Value(Scalar(0x00000003))
                                           // mir::Constant
                                           // + span: $DIR/array_index.rs:5:28: 5:29
                                           // + literal: Const { ty: u32, val: Value(Scalar(0x00000003)) }
          StorageLive(_3);                 // scope 0 at $DIR/array_index.rs:5:31: 5:32
          _3 = const 2usize;               // scope 0 at $DIR/array_index.rs:5:31: 5:32
                                           // ty::Const
                                           // + ty: usize
                                           // + val: Value(Scalar(0x0000000000000002))
                                           // mir::Constant
                                           // + span: $DIR/array_index.rs:5:31: 5:32
                                           // + literal: Const { ty: usize, val: Value(Scalar(0x0000000000000002)) }
          _4 = const 4usize;               // scope 0 at $DIR/array_index.rs:5:18: 5:33
                                           // ty::Const
                                           // + ty: usize
                                           // + val: Value(Scalar(0x0000000000000004))
                                           // mir::Constant
                                           // + span: $DIR/array_index.rs:5:18: 5:33
                                           // + literal: Const { ty: usize, val: Value(Scalar(0x0000000000000004)) }
-         _5 = Lt(_3, _4);                 // scope 0 at $DIR/array_index.rs:5:18: 5:33
-         assert(move _5, "index out of bounds: the len is {} but the index is {}", move _4, _3) -> bb1; // scope 0 at $DIR/array_index.rs:5:18: 5:33
+         _5 = const true;                 // scope 0 at $DIR/array_index.rs:5:18: 5:33
+                                          // ty::Const
+                                          // + ty: bool
+                                          // + val: Value(Scalar(0x01))
+                                          // mir::Constant
+                                          // + span: $DIR/array_index.rs:5:18: 5:33
+                                          // + literal: Const { ty: bool, val: Value(Scalar(0x01)) }
+         assert(const true, "index out of bounds: the len is {} but the index is {}", move _4, _3) -> bb1; // scope 0 at $DIR/array_index.rs:5:18: 5:33
+                                          // ty::Const
+                                          // + ty: bool
+                                          // + val: Value(Scalar(0x01))
+                                          // mir::Constant
+                                          // + span: $DIR/array_index.rs:5:18: 5:33
+                                          // + literal: Const { ty: bool, val: Value(Scalar(0x01)) }
      }
  
      bb1: {
-         _1 = _2[_3];                     // scope 0 at $DIR/array_index.rs:5:18: 5:33
+         _1 = const 2u32;                 // scope 0 at $DIR/array_index.rs:5:18: 5:33
+                                          // ty::Const
+                                          // + ty: u32
+                                          // + val: Value(Scalar(0x00000002))
+                                          // mir::Constant
+                                          // + span: $DIR/array_index.rs:5:18: 5:33
+                                          // + literal: Const { ty: u32, val: Value(Scalar(0x00000002)) }
          StorageDead(_3);                 // scope 0 at $DIR/array_index.rs:5:33: 5:34
          StorageDead(_2);                 // scope 0 at $DIR/array_index.rs:5:33: 5:34
          _0 = const ();                   // scope 0 at $DIR/array_index.rs:4:11: 6:2
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/array_index.rs:4:11: 6:2
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
          StorageDead(_1);                 // scope 0 at $DIR/array_index.rs:6:1: 6:2
          return;                          // scope 0 at $DIR/array_index.rs:6:2: 6:2
      }
  }
  
