- // MIR for `main` before InstrumentCoverage
+ // MIR for `main` after InstrumentCoverage
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/instrument_coverage.rs:9:11: 9:11
      let mut _1: ();                      // in scope 0 at $DIR/instrument_coverage.rs:9:1: 15:2
      let mut _2: bool;                    // in scope 0 at $DIR/instrument_coverage.rs:11:12: 11:17
      let mut _3: !;                       // in scope 0 at $DIR/instrument_coverage.rs:11:18: 13:10
+     let mut _4: ();                      // in scope 0 at $DIR/instrument_coverage.rs:9:1: 15:2
  
      bb0: {
-         falseUnwind -> [real: bb1, cleanup: bb2]; // scope 0 at $DIR/instrument_coverage.rs:10:5: 14:6
+         StorageLive(_4);                 // scope 0 at $DIR/instrument_coverage.rs:9:1: 15:2
+         _4 = const std::intrinsics::count_code_region(const 0_u32, const 387_u32, const 465_u32) -> bb7; // scope 0 at $DIR/instrument_coverage.rs:9:1: 15:2
+                                          // ty::Const
+                                          // + ty: unsafe extern "rust-intrinsic" fn(u32, u32, u32) {std::intrinsics::count_code_region}
+                                          // + val: Value(Scalar(<ZST>))
+                                          // mir::Constant
+                                          // + span: $DIR/instrument_coverage.rs:9:1: 9:1
+                                          // + literal: Const { ty: unsafe extern "rust-intrinsic" fn(u32, u32, u32) {std::intrinsics::count_code_region}, val: Value(Scalar(<ZST>)) }
+                                          // ty::Const
+                                          // + ty: u32
+                                          // + val: Value(Scalar(0x00000000))
+                                          // mir::Constant
+                                          // + span: $DIR/instrument_coverage.rs:9:1: 9:1
+                                          // + literal: Const { ty: u32, val: Value(Scalar(0x00000000)) }
+                                          // ty::Const
+                                          // + ty: u32
+                                          // + val: Value(Scalar(0x00000183))
+                                          // mir::Constant
+                                          // + span: $DIR/instrument_coverage.rs:9:1: 9:1
+                                          // + literal: Const { ty: u32, val: Value(Scalar(0x00000183)) }
+                                          // ty::Const
+                                          // + ty: u32
+                                          // + val: Value(Scalar(0x000001d1))
+                                          // mir::Constant
+                                          // + span: $DIR/instrument_coverage.rs:9:1: 9:1
+                                          // + literal: Const { ty: u32, val: Value(Scalar(0x000001d1)) }
      }
  
      bb1: {
          StorageLive(_2);                 // scope 0 at $DIR/instrument_coverage.rs:11:12: 11:17
          _2 = const bar() -> [return: bb3, unwind: bb2]; // scope 0 at $DIR/instrument_coverage.rs:11:12: 11:17
                                           // ty::Const
                                           // + ty: fn() -> bool {bar}
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/instrument_coverage.rs:11:12: 11:15
                                           // + literal: Const { ty: fn() -> bool {bar}, val: Value(Scalar(<ZST>)) }
      }
  
      bb2 (cleanup): {
          resume;                          // scope 0 at $DIR/instrument_coverage.rs:9:1: 15:2
      }
  
      bb3: {
          FakeRead(ForMatchedPlace, _2);   // scope 0 at $DIR/instrument_coverage.rs:11:12: 11:17
          switchInt(_2) -> [false: bb5, otherwise: bb4]; // scope 0 at $DIR/instrument_coverage.rs:11:9: 13:10
      }
  
      bb4: {
          falseEdge -> [real: bb6, imaginary: bb5]; // scope 0 at $DIR/instrument_coverage.rs:11:9: 13:10
      }
  
      bb5: {
          _1 = const ();                   // scope 0 at $DIR/instrument_coverage.rs:11:9: 13:10
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/instrument_coverage.rs:11:9: 13:10
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
          StorageDead(_2);                 // scope 0 at $DIR/instrument_coverage.rs:14:5: 14:6
          goto -> bb0;                     // scope 0 at $DIR/instrument_coverage.rs:10:5: 14:6
      }
  
      bb6: {
          _0 = const ();                   // scope 0 at $DIR/instrument_coverage.rs:12:13: 12:18
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/instrument_coverage.rs:12:13: 12:18
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
          StorageDead(_2);                 // scope 0 at $DIR/instrument_coverage.rs:14:5: 14:6
          return;                          // scope 0 at $DIR/instrument_coverage.rs:15:2: 15:2
+     }
+ 
+     bb7: {
+         StorageDead(_4);                 // scope 0 at $DIR/instrument_coverage.rs:10:5: 14:6
+         falseUnwind -> [real: bb1, cleanup: bb2]; // scope 0 at $DIR/instrument_coverage.rs:10:5: 14:6
      }
  }
  
