- // MIR for `constptr` before GVN
+ // MIR for `constptr` after GVN
  
  fn constptr() -> () {
      let mut _0: ();
      let mut _1: i32;
      let _2: ();
      let mut _3: i32;
      let _5: ();
      let mut _6: i32;
      scope 1 {
          debug x => _1;
          let _4: *const i32;
          scope 2 {
              debug r => _4;
          }
      }
  
      bb0: {
          StorageLive(_1);
          _1 = const 42_i32;
          StorageLive(_2);
          StorageLive(_3);
-         _3 = copy _1;
-         _2 = opaque::<i32>(move _3) -> [return: bb1, unwind unreachable];
+         _3 = const 42_i32;
+         _2 = opaque::<i32>(const 42_i32) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          StorageDead(_3);
          StorageDead(_2);
          StorageLive(_4);
          _4 = &raw const _1;
          StorageLive(_5);
          StorageLive(_6);
          _6 = copy _1;
          _5 = opaque::<i32>(move _6) -> [return: bb2, unwind unreachable];
      }
  
      bb2: {
          StorageDead(_6);
          StorageDead(_5);
          _0 = const ();
          StorageDead(_4);
          StorageDead(_1);
          return;
      }
  }
  
