- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();
      let _1: u32;
      let mut _2: (u32, bool);
      scope 1 {
          debug x => _1;
      }
  
      bb0: {
          StorageLive(_1);
-         _2 = CheckedAdd(const 1_u32, const 1_u32);
-         assert(!move (_2.1: bool), "attempt to compute `{} + {}`, which would overflow", const 1_u32, const 1_u32) -> [success: bb1, unwind unreachable];
+         _2 = const (2_u32, false);
+         assert(!const false, "attempt to compute `{} + {}`, which would overflow", const 1_u32, const 1_u32) -> [success: bb1, unwind unreachable];
      }
  
      bb1: {
-         _1 = move (_2.0: u32);
+         _1 = const 2_u32;
          _0 = const ();
          StorageDead(_1);
          return;
      }
+ }
+ 
+ ALLOC0 (size: 8, align: 4) {
+     02 00 00 00 00 __ __ __                         │ .....░░░
  }
  
