- // MIR for `hello` before GVN
+ // MIR for `hello` after GVN
  
  fn hello() -> () {
      let mut _0: ();
      let mut _1: bool;
      let mut _2: !;
  
      bb0: {
          StorageLive(_1);
-         _1 = const <bool as NeedsDrop>::NEEDS;
-         switchInt(move _1) -> [0: bb2, otherwise: bb1];
+         _1 = const false;
+         switchInt(const false) -> [0: bb2, otherwise: bb1];
      }
  
      bb1: {
          _2 = begin_panic::<&str>(const "explicit panic") -> unwind unreachable;
      }
  
      bb2: {
          StorageDead(_1);
          return;
      }
  }
  
  ALLOC0 (size: 14, align: 1) {
      65 78 70 6c 69 63 69 74 20 70 61 6e 69 63       │ explicit panic
  }
  
