- // MIR for `ge` before GVN
+ // MIR for `ge` after GVN
  
  fn ge(_1: u32) -> () {
      debug input => _1;
      let mut _0: ();
      let _2: bool;
      let mut _3: u64;
      let mut _4: u32;
      let mut _6: u64;
      let mut _7: u32;
      let mut _8: u64;
      let mut _10: u64;
      let mut _11: u32;
      scope 1 {
          debug yes => _2;
          let _5: bool;
          scope 2 {
              debug runtime => _5;
              let _9: bool;
              scope 3 {
                  debug no => _9;
              }
          }
      }
  
      bb0: {
          StorageLive(_2);
-         StorageLive(_3);
+         nop;
          StorageLive(_4);
          _4 = copy _1;
-         _3 = move _4 as u64 (IntToInt);
+         _3 = copy _1 as u64 (IntToInt);
          StorageDead(_4);
-         _2 = Ge(const U32_MAX_PLUS_ONE, move _3);
-         StorageDead(_3);
+         _2 = const true;
+         nop;
          StorageLive(_5);
          StorageLive(_6);
          StorageLive(_7);
          _7 = copy _1;
-         _6 = move _7 as u64 (IntToInt);
+         _6 = copy _3;
          StorageDead(_7);
          StorageLive(_8);
-         _8 = const core::num::<impl u32>::MAX as u64 (IntToInt);
-         _5 = Ge(move _6, move _8);
+         _8 = const 4294967295_u64;
+         _5 = Ge(copy _3, const 4294967295_u64);
          StorageDead(_8);
          StorageDead(_6);
          StorageLive(_9);
          StorageLive(_10);
          StorageLive(_11);
          _11 = copy _1;
-         _10 = move _11 as u64 (IntToInt);
+         _10 = copy _3;
          StorageDead(_11);
-         _9 = Ge(move _10, const U32_MAX_PLUS_ONE);
+         _9 = const false;
          StorageDead(_10);
          _0 = const ();
          StorageDead(_9);
          StorageDead(_5);
          StorageDead(_2);
          return;
      }
  }
  
