- // MIR for `le` before GVN
+ // MIR for `le` after GVN
  
  fn le(_1: u16) -> () {
      debug input => _1;
      let mut _0: ();
      let _2: bool;
      let mut _3: u32;
      let mut _4: u16;
      let mut _6: u32;
      let mut _7: u32;
      let mut _8: u16;
      let mut _10: u32;
      let mut _11: u16;
      scope 1 {
          debug yes => _2;
          let _5: bool;
          scope 2 {
              debug runtime => _5;
              let _9: bool;
              scope 3 {
                  debug no => _9;
              }
          }
      }
  
      bb0: {
          StorageLive(_2);
-         StorageLive(_3);
+         nop;
          StorageLive(_4);
          _4 = copy _1;
-         _3 = move _4 as u32 (IntToInt);
+         _3 = copy _1 as u32 (IntToInt);
          StorageDead(_4);
-         _2 = Le(move _3, const U16_MAX_PLUS_ONE);
-         StorageDead(_3);
+         _2 = const true;
+         nop;
          StorageLive(_5);
          StorageLive(_6);
-         _6 = const core::num::<impl u16>::MAX as u32 (IntToInt);
+         _6 = const 65535_u32;
          StorageLive(_7);
          StorageLive(_8);
          _8 = copy _1;
-         _7 = move _8 as u32 (IntToInt);
+         _7 = copy _3;
          StorageDead(_8);
-         _5 = Le(move _6, move _7);
+         _5 = Le(const 65535_u32, copy _3);
          StorageDead(_7);
          StorageDead(_6);
          StorageLive(_9);
          StorageLive(_10);
          StorageLive(_11);
          _11 = copy _1;
-         _10 = move _11 as u32 (IntToInt);
+         _10 = copy _3;
          StorageDead(_11);
-         _9 = Le(const U16_MAX_PLUS_ONE, move _10);
+         _9 = const false;
          StorageDead(_10);
          _0 = const ();
          StorageDead(_9);
          StorageDead(_5);
          StorageDead(_2);
          return;
      }
  }
  
