- // MIR for `indirect_ref_t_1` before GVN
+ // MIR for `indirect_ref_t_1` after GVN
  
  fn indirect_ref_t_1(_1: &(T,), _2: fn(T), _3: fn()) -> () {
      debug x => _1;
      debug out => _2;
      debug clobber => _3;
      let mut _0: ();
      let _4: ();
      let mut _5: fn(T);
      let mut _6: T;
      let _7: ();
      let mut _8: fn();
      let _9: ();
      let mut _10: fn(T);
      let mut _11: T;
  
      bb0: {
          StorageLive(_4);
          StorageLive(_5);
          _5 = copy _2;
-         StorageLive(_6);
+         nop;
          _6 = copy ((*_1).0: T);
-         _4 = move _5(move _6) -> [return: bb1, unwind unreachable];
+         _4 = copy _2(copy _6) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
-         StorageDead(_6);
+         nop;
          StorageDead(_5);
          StorageDead(_4);
          StorageLive(_7);
          StorageLive(_8);
          _8 = copy _3;
-         _7 = move _8() -> [return: bb2, unwind unreachable];
+         _7 = copy _3() -> [return: bb2, unwind unreachable];
      }
  
      bb2: {
          StorageDead(_8);
          StorageDead(_7);
          StorageLive(_9);
          StorageLive(_10);
          _10 = copy _2;
          StorageLive(_11);
-         _11 = copy ((*_1).0: T);
-         _9 = move _10(move _11) -> [return: bb3, unwind unreachable];
+         _11 = copy _6;
+         _9 = copy _2(copy _6) -> [return: bb3, unwind unreachable];
      }
  
      bb3: {
          StorageDead(_11);
          StorageDead(_10);
          StorageDead(_9);
          _0 = const ();
          return;
      }
  }
  
