- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();
      let _1: ();
      let mut _2: ((), u8, u8);
  
      bb0: {
          StorageLive(_2);
-         _2 = (const (), const 0_u8, const 0_u8);
-         _1 = encode(move _2) -> [return: bb1, unwind unreachable];
+         _2 = const ((), 0_u8, 0_u8);
+         _1 = encode(const ((), 0_u8, 0_u8)) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          StorageDead(_2);
          return;
      }
+ }
+ 
+ ALLOC0 (size: 2, align: 1) {
+     00 00                                           │ ..
+ }
+ 
+ ALLOC1 (size: 2, align: 1) {
+     00 00                                           │ ..
  }
  
