- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/issue_66971.rs:+0:11: +0:11
      let _1: ();                          // in scope 0 at $DIR/issue_66971.rs:+1:5: +1:23
      let mut _2: ((), u8, u8);            // in scope 0 at $DIR/issue_66971.rs:+1:12: +1:22
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/issue_66971.rs:+1:12: +1:22
          _2 = (const (), const 0_u8, const 0_u8); // scope 0 at $DIR/issue_66971.rs:+1:12: +1:22
          _1 = encode(move _2) -> bb1;     // scope 0 at $DIR/issue_66971.rs:+1:5: +1:23
                                           // mir::Constant
                                           // + span: $DIR/issue_66971.rs:18:5: 18:11
                                           // + literal: Const { ty: fn(((), u8, u8)) {encode}, val: Value(<ZST>) }
      }
  
      bb1: {
          StorageDead(_2);                 // scope 0 at $DIR/issue_66971.rs:+1:22: +1:23
          return;                          // scope 0 at $DIR/issue_66971.rs:+2:2: +2:2
      }
  }
  
