- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/issue_67019.rs:+0:11: +0:11
      let _1: ();                          // in scope 0 at $DIR/issue_67019.rs:+1:5: +1:20
      let mut _2: ((u8, u8),);             // in scope 0 at $DIR/issue_67019.rs:+1:10: +1:19
      let mut _3: (u8, u8);                // in scope 0 at $DIR/issue_67019.rs:+1:11: +1:17
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/issue_67019.rs:+1:10: +1:19
          StorageLive(_3);                 // scope 0 at $DIR/issue_67019.rs:+1:11: +1:17
-         _3 = (const 1_u8, const 2_u8);   // scope 0 at $DIR/issue_67019.rs:+1:11: +1:17
+         _3 = const (1_u8, 2_u8);         // scope 0 at $DIR/issue_67019.rs:+1:11: +1:17
          _2 = (move _3,);                 // scope 0 at $DIR/issue_67019.rs:+1:10: +1:19
          StorageDead(_3);                 // scope 0 at $DIR/issue_67019.rs:+1:18: +1:19
          _1 = test(move _2) -> bb1;       // scope 0 at $DIR/issue_67019.rs:+1:5: +1:20
                                           // mir::Constant
                                           // + span: $DIR/issue_67019.rs:13:5: 13:9
                                           // + literal: Const { ty: fn(((u8, u8),)) {test}, val: Value(<ZST>) }
      }
  
      bb1: {
          StorageDead(_2);                 // scope 0 at $DIR/issue_67019.rs:+1:19: +1:20
          return;                          // scope 0 at $DIR/issue_67019.rs:+2:2: +2:2
      }
  }
  
