- // MIR for `test` before ConstProp
+ // MIR for `test` after ConstProp
  
  fn test(_1: i32) -> i32 {
      debug x => _1;                       // in scope 0 at $DIR/mult_by_zero.rs:+0:9: +0:10
      let mut _0: i32;                     // return place in scope 0 at $DIR/mult_by_zero.rs:+0:21: +0:24
      let mut _2: i32;                     // in scope 0 at $DIR/mult_by_zero.rs:+1:3: +1:4
  
      bb0: {
-         _0 = Mul(_1, const 0_i32);       // scope 0 at $DIR/mult_by_zero.rs:+1:3: +1:8
+         _0 = const 0_i32;                // scope 0 at $DIR/mult_by_zero.rs:+1:3: +1:8
          return;                          // scope 0 at $DIR/mult_by_zero.rs:+2:2: +2:2
      }
  }
  
