- // MIR for `main` before GVN
+ // MIR for `main` after GVN
  
  fn main() -> () {
      let mut _0: ();
      let _1: u8;
      let mut _2: u8;
      let mut _3: &u8;
      let mut _4: u8;
      let mut _5: &u8;
      scope 1 {
          debug x => _1;
      }
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
-         StorageLive(_3);
+         nop;
          _3 = const {ALLOC0: &u8};
          _2 = copy (*_3);
          StorageLive(_4);
          StorageLive(_5);
          _5 = const {ALLOC0: &u8};
-         _4 = copy (*_5);
+         _4 = copy (*_3);
          _1 = Add(move _2, move _4);
          StorageDead(_4);
          StorageDead(_2);
          StorageDead(_5);
-         StorageDead(_3);
+         nop;
          _0 = const ();
          StorageDead(_1);
          return;
      }
  }
  
  ALLOC0 (static: FOO, size: 1, align: 1) {
      02                                              │ .
  }
  
