- // MIR for `main` before PromoteTemps
+ // MIR for `main` after PromoteTemps
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/ref_deref.rs:+0:11: +0:11
      let _1: i32;                         // in scope 0 at $DIR/ref_deref.rs:+1:5: +1:10
      let mut _2: &i32;                    // in scope 0 at $DIR/ref_deref.rs:+1:6: +1:10
      let _3: i32;                         // in scope 0 at $DIR/ref_deref.rs:+1:8: +1:9
+     let mut _4: &i32;                    // in scope 0 at $DIR/ref_deref.rs:+1:6: +1:10
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/ref_deref.rs:+1:5: +1:10
          StorageLive(_2);                 // scope 0 at $DIR/ref_deref.rs:+1:6: +1:10
-         StorageLive(_3);                 // scope 0 at $DIR/ref_deref.rs:+1:8: +1:9
-         _3 = const 4_i32;                // scope 0 at $DIR/ref_deref.rs:+1:8: +1:9
-         _2 = &_3;                        // scope 0 at $DIR/ref_deref.rs:+1:6: +1:10
+         _4 = const _;                    // scope 0 at $DIR/ref_deref.rs:+1:6: +1:10
+                                          // mir::Constant
+                                          // + span: $DIR/ref_deref.rs:6:6: 6:10
+                                          // + literal: Const { ty: &i32, val: Unevaluated(main, [], Some(promoted[0])) }
+         _2 = &(*_4);                     // scope 0 at $DIR/ref_deref.rs:+1:6: +1:10
          _1 = (*_2);                      // scope 0 at $DIR/ref_deref.rs:+1:5: +1:10
-         StorageDead(_3);                 // scope 0 at $DIR/ref_deref.rs:+1:10: +1:11
          StorageDead(_2);                 // scope 0 at $DIR/ref_deref.rs:+1:10: +1:11
          StorageDead(_1);                 // scope 0 at $DIR/ref_deref.rs:+1:10: +1:11
          _0 = const ();                   // scope 0 at $DIR/ref_deref.rs:+0:11: +2:2
          return;                          // scope 0 at $DIR/ref_deref.rs:+2:2: +2:2
      }
  }
  
