- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/repeat.rs:+0:11: +0:11
      let _1: u32;                         // in scope 0 at $DIR/repeat.rs:+1:9: +1:10
      let mut _2: u32;                     // in scope 0 at $DIR/repeat.rs:+1:18: +1:28
      let mut _3: [u32; 8];                // in scope 0 at $DIR/repeat.rs:+1:18: +1:25
      let _4: usize;                       // in scope 0 at $DIR/repeat.rs:+1:26: +1:27
      let mut _5: usize;                   // in scope 0 at $DIR/repeat.rs:+1:18: +1:28
      let mut _6: bool;                    // in scope 0 at $DIR/repeat.rs:+1:18: +1:28
      scope 1 {
          debug x => _1;                   // in scope 1 at $DIR/repeat.rs:+1:9: +1:10
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/repeat.rs:+1:9: +1:10
          StorageLive(_2);                 // scope 0 at $DIR/repeat.rs:+1:18: +1:28
          StorageLive(_3);                 // scope 0 at $DIR/repeat.rs:+1:18: +1:25
          _3 = [const 42_u32; 8];          // scope 0 at $DIR/repeat.rs:+1:18: +1:25
          StorageLive(_4);                 // scope 0 at $DIR/repeat.rs:+1:26: +1:27
          _4 = const 2_usize;              // scope 0 at $DIR/repeat.rs:+1:26: +1:27
-         _5 = Len(_3);                    // scope 0 at $DIR/repeat.rs:+1:18: +1:28
-         _6 = Lt(_4, _5);                 // scope 0 at $DIR/repeat.rs:+1:18: +1:28
-         assert(move _6, "index out of bounds: the length is {} but the index is {}", move _5, _4) -> bb1; // scope 0 at $DIR/repeat.rs:+1:18: +1:28
+         _5 = const 8_usize;              // scope 0 at $DIR/repeat.rs:+1:18: +1:28
+         _6 = const true;                 // scope 0 at $DIR/repeat.rs:+1:18: +1:28
+         assert(const true, "index out of bounds: the length is {} but the index is {}", move _5, _4) -> bb1; // scope 0 at $DIR/repeat.rs:+1:18: +1:28
      }
  
      bb1: {
-         _2 = _3[_4];                     // scope 0 at $DIR/repeat.rs:+1:18: +1:28
-         _1 = Add(move _2, const 0_u32);  // scope 0 at $DIR/repeat.rs:+1:18: +1:32
+         _2 = const 42_u32;               // scope 0 at $DIR/repeat.rs:+1:18: +1:28
+         _1 = const 42_u32;               // scope 0 at $DIR/repeat.rs:+1:18: +1:32
          StorageDead(_2);                 // scope 0 at $DIR/repeat.rs:+1:31: +1:32
          StorageDead(_4);                 // scope 0 at $DIR/repeat.rs:+1:32: +1:33
          StorageDead(_3);                 // scope 0 at $DIR/repeat.rs:+1:32: +1:33
          _0 = const ();                   // scope 0 at $DIR/repeat.rs:+0:11: +2:2
          StorageDead(_1);                 // scope 0 at $DIR/repeat.rs:+2:1: +2:2
          return;                          // scope 0 at $DIR/repeat.rs:+2:2: +2:2
      }
  }
  
