- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();
      let _1: I32;
      let mut _3: i32;
      let mut _4: i32;
      let mut _5: i32;
      scope 1 {
          debug x => _1;
          let _2: I32;
          scope 2 {
              debug y => _2;
          }
      }
  
      bb0: {
          StorageLive(_1);
-         _1 = I32(const 0_i32);
+         _1 = const I32(0_i32);
          StorageLive(_2);
          StorageLive(_3);
          StorageLive(_4);
-         _4 = (_1.0: i32);
+         _4 = const 0_i32;
          StorageLive(_5);
-         _5 = (_1.0: i32);
-         _3 = Add(move _4, move _5);
+         _5 = const 0_i32;
+         _3 = const 0_i32;
          StorageDead(_5);
          StorageDead(_4);
-         _2 = I32(move _3);
+         _2 = const I32(0_i32);
          StorageDead(_3);
          _0 = const ();
          StorageDead(_2);
          StorageDead(_1);
          return;
      }
+ }
+ 
+ ALLOC0 (size: 4, align: 4) {
+     00 00 00 00                                     │ ....
+ }
+ 
+ ALLOC1 (size: 4, align: 4) {
+     00 00 00 00                                     │ ....
  }
  
