- // MIR for `add` before GVN
+ // MIR for `add` after GVN
  
  fn add() -> u32 {
      let mut _0: u32;
      let mut _1: (u32, bool);
  
      bb0: {
-         _1 = AddWithOverflow(const 2_u32, const 2_u32);
-         assert(!move (_1.1: bool), "attempt to compute `{} + {}`, which would overflow", const 2_u32, const 2_u32) -> [success: bb1, unwind continue];
+         _1 = const (4_u32, false);
+         assert(!const false, "attempt to compute `{} + {}`, which would overflow", const 2_u32, const 2_u32) -> [success: bb1, unwind continue];
      }
  
      bb1: {
-         _0 = move (_1.0: u32);
+         _0 = const 4_u32;
          return;
      }
+ }
+ 
+ ALLOC0 (size: 8, align: 4) {
+     04 00 00 00 00 __ __ __                         │ .....░░░
  }
  
