- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();
      let _1: u32;
      let _2: ();
      let mut _3: u32;
      scope 1 {
          debug x => _1;
      }
  
      bb0: {
          StorageLive(_1);
          _1 = const 1_u32;
          StorageLive(_2);
          StorageLive(_3);
-         _3 = _1;
+         _3 = const 1_u32;
          _2 = consume(move _3) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          StorageDead(_3);
          StorageDead(_2);
          _0 = const ();
          StorageDead(_1);
          return;
      }
  }
  
