- // MIR for `unreachable_mut` before GVN
+ // MIR for `unreachable_mut` after GVN
  
  fn unreachable_mut() -> ! {
      let mut _0: !;
      let _1: &mut Never;
      let mut _2: &mut Never;
      scope 1 {
          debug x => _1;
      }
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
-         _2 = const 1_usize as &mut Never (Transmute);
-         _1 = &mut (*_2);
+         _2 = const {0x1 as &mut Never};
+         _1 = const {0x1 as &mut Never};
          StorageDead(_2);
          unreachable;
      }
  }
  
