- // MIR for `option_field` before GVN
+ // MIR for `option_field` after GVN
  
  fn option_field(_1: Option<NonNull<()>>) -> *const () {
      debug x => _1;
      let mut _0: *const ();
      let mut _2: isize;
      let mut _4: std::ptr::NonNull<()>;
      scope 1 {
          debug x => _3;
          let _3: std::ptr::NonNull<()>;
      }
  
      bb0: {
          _2 = discriminant(_1);
          switchInt(move _2) -> [1: bb1, otherwise: bb2];
      }
  
      bb1: {
-         StorageLive(_3);
+         nop;
          _3 = copy ((_1 as Some).0: std::ptr::NonNull<()>);
          StorageLive(_4);
          _4 = copy _3;
-         _0 = move _4 as *const () (Transmute);
+         _0 = copy _1 as *const () (Transmute);
          StorageDead(_4);
-         StorageDead(_3);
+         nop;
          goto -> bb3;
      }
  
      bb2: {
          _0 = const 0_usize as *const () (PointerWithExposedProvenance);
          goto -> bb3;
      }
  
      bb3: {
          return;
      }
  }
  
