- // MIR for `main` before GVN
+ // MIR for `main` after GVN
  
  fn main() -> () {
      let mut _0: ();
      let _1: main::Un;
      let mut _2: u32;
      let _3: ();
      let mut _4: u32;
      scope 1 {
          debug un => _1;
          scope 3 (inlined std::mem::drop::<u32>) {
          }
      }
      scope 2 (inlined val) {
      }
  
      bb0: {
          StorageLive(_1);
-         StorageLive(_2);
+         nop;
          _2 = const 1_u32;
-         _1 = Un { us: move _2 };
-         StorageDead(_2);
+         _1 = const Un {{ us: 1_u32 }};
+         nop;
          StorageLive(_3);
          StorageLive(_4);
-         _4 = copy (_1.0: u32);
+         _4 = const 1_u32;
          StorageDead(_4);
          StorageDead(_3);
          _0 = const ();
          StorageDead(_1);
          return;
      }
  }
+ 
+ ALLOC0 (size: 4, align: 4) { .. }
  
