/// Do not update manually - use `./x.py test tidy --bless`
/// Holds all direct and indirect dependencies of proc-macro crates in tree.
/// See <https://github.com/rust-lang/rust/issues/134863>
pub static CRATES: &[&str] = &[
    // tidy-alphabetical-start
    "askama_derive",
    "askama_parser",
    "basic-toml",
    "bitflags",
    "bumpalo",
    "darling",
    "darling_core",
    "defmt",
    "defmt-parser",
    "derive_builder_core",
    "equivalent",
    "fluent-bundle",
    "fluent-langneg",
    "fluent-syntax",
    "fnv",
    "foldhash",
    "glob",
    "hashbrown",
    "heck",
    "ident_case",
    "indexmap",
    "intl-memoizer",
    "intl_pluralrules",
    "jiff-core",
    "memchr",
    "minimal-lexical",
    "nom",
    "pest",
    "pest_generator",
    "pest_meta",
    "proc-macro2",
    "quote",
    "rustc-hash",
    "self_cell",
    "serde",
    "serde_core",
    "serde_derive_internals",
    "smallvec",
    "stable_deref_trait",
    "strsim",
    "syn",
    "synstructure",
    "thiserror",
    "tinystr",
    "type-map",
    "ucd-trie",
    "unic-langid",
    "unic-langid-impl",
    "unic-langid-macros",
    "unicode-ident",
    "wasm-bindgen-macro-support",
    "wasm-bindgen-shared",
    "winnow",
    "yoke",
    "zerofrom",
    "zerovec",
    // tidy-alphabetical-end
];
