/// Do not update manually - use `./x.py test tidy --bless`
/// Holds all direct and indirect dependencies of proc-macro crates in tree.
/// See <https://github.com/rust-lang/rust/issues/134863>
pub static CRATES: &[&str] = &[
    // tidy-alphabetical-start
    "annotate-snippets",
    "anstyle",
    "basic-toml",
    "bumpalo",
    "darling",
    "darling_core",
    "derive_builder_core",
    "fluent-bundle",
    "fluent-langneg",
    "fluent-syntax",
    "fnv",
    "heck",
    "ident_case",
    "intl-memoizer",
    "intl_pluralrules",
    "log",
    "memchr",
    "mime",
    "mime_guess",
    "minimal-lexical",
    "nom",
    "num-conv",
    "proc-macro2",
    "quote",
    "rinja_parser",
    "rustc-hash",
    "self_cell",
    "serde",
    "smallvec",
    "stable_deref_trait",
    "strsim",
    "syn",
    "synstructure",
    "thiserror",
    "time-core",
    "tinystr",
    "type-map",
    "unic-langid",
    "unic-langid-impl",
    "unic-langid-macros",
    "unicase",
    "unicode-ident",
    "unicode-width",
    "wasm-bindgen-backend",
    "wasm-bindgen-macro-support",
    "wasm-bindgen-shared",
    "yoke",
    "zerofrom",
    "zerovec",
    // tidy-alphabetical-end
];
