/// Do not update manually - use `./x.py test tidy --bless`
/// Holds all direct and indirect dependencies of proc-macro crates in tree.
/// See <https://github.com/rust-lang/rust/issues/134863>
pub static CRATES: &[&str] = &[
    // tidy-alphabetical-start
    "allocator_api2",
    "askama_derive",
    "askama_parser",
    "basic_toml",
    "bitflags",
    "bumpalo",
    "darling",
    "darling_core",
    "defmt",
    "defmt_parser",
    "derive_builder_core",
    "equivalent",
    "fluent_bundle",
    "fluent_langneg",
    "fluent_syntax",
    "fnv",
    "foldhash",
    "glob",
    "hashbrown",
    "heck",
    "ident_case",
    "indexmap",
    "intl_memoizer",
    "intl_pluralrules",
    "jiff_core",
    "log",
    "memchr",
    "minimal_lexical",
    "nom",
    "pest",
    "pest_generator",
    "pest_meta",
    "proc_macro2",
    "quote",
    "rustc_hash",
    "self_cell",
    "serde",
    "serde_core",
    "serde_derive_internals",
    "smallvec",
    "stable_deref_trait",
    "strsim",
    "syn",
    "synstructure",
    "thiserror",
    "tinystr",
    "type_map",
    "ucd_trie",
    "unic_langid",
    "unic_langid_impl",
    "unic_langid_macros",
    "unicode_ident",
    "wasm_bindgen_macro_support",
    "wasm_bindgen_shared",
    "winnow",
    "yoke",
    "zerofrom",
    "zerovec",
    // tidy-alphabetical-end
];
