- // MIR for `main` before SimplifyLocals
+ // MIR for `main` after SimplifyLocals
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:12:11: 12:11
-     let mut _1: ((), ());                // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:20: 13:28
-     let mut _2: ();                      // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:21: 13:23
-     let mut _3: ();                      // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:25: 13:27
-     let _4: ();                          // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:14:5: 14:22
-     let mut _5: ((), ());                // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:14:13: 14:21
-     let mut _6: ();                      // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:14:14: 14:16
-     let mut _7: ();                      // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:14:18: 14:20
-     let _8: ();                          // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:16:5: 16:35
-     let mut _9: u8;                      // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:34
-     let mut _10: u8;                     // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:30
-     let mut _11: Temp;                   // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:28
+     let _1: ();                          // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:14:5: 14:22
+     let _2: ();                          // in scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:16:5: 16:35
      scope 1 {
      }
  
      bb0: {
-         StorageLive(_1);                 // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:20: 13:28
-         StorageLive(_2);                 // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:21: 13:23
-         _2 = const ();                   // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:21: 13:23
+         StorageLive(_1);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:5: 14:22
+         _1 = const use_zst(const ((), ())) -> bb1; // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:5: 14:22
                                           // ty::Const
-                                          // + ty: ()
-                                          // + val: Value(Scalar(<ZST>))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:13:21: 13:23
-                                          // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
-         StorageLive(_3);                 // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:25: 13:27
-         _3 = const ();                   // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:25: 13:27
-                                          // ty::Const
-                                          // + ty: ()
-                                          // + val: Value(Scalar(<ZST>))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:13:25: 13:27
-                                          // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
-         _1 = const ((), ());             // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:20: 13:28
-                                          // ty::Const
-                                          // + ty: ((), ())
-                                          // + val: Value(Scalar(<ZST>))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:13:20: 13:28
-                                          // + literal: Const { ty: ((), ()), val: Value(Scalar(<ZST>)) }
-         StorageDead(_3);                 // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:27: 13:28
-         StorageDead(_2);                 // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:27: 13:28
-         StorageDead(_1);                 // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:13:28: 13:29
-         StorageLive(_4);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:5: 14:22
-         StorageLive(_5);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:13: 14:21
-         StorageLive(_6);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:14: 14:16
-         _6 = const ();                   // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:14: 14:16
-                                          // ty::Const
-                                          // + ty: ()
-                                          // + val: Value(Scalar(<ZST>))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:14:14: 14:16
-                                          // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
-         StorageLive(_7);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:18: 14:20
-         _7 = const ();                   // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:18: 14:20
-                                          // ty::Const
-                                          // + ty: ()
-                                          // + val: Value(Scalar(<ZST>))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:14:18: 14:20
-                                          // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
-         _5 = const ((), ());             // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:13: 14:21
-                                          // ty::Const
-                                          // + ty: ((), ())
-                                          // + val: Value(Scalar(<ZST>))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:14:13: 14:21
-                                          // + literal: Const { ty: ((), ()), val: Value(Scalar(<ZST>)) }
-         StorageDead(_7);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:20: 14:21
-         StorageDead(_6);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:20: 14:21
-         _4 = const use_zst(const ((), ())) -> bb1; // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:5: 14:22
-                                          // ty::Const
                                           // + ty: fn(((), ())) {use_zst}
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify-locals-removes-unused-consts.rs:14:5: 14:12
                                           // + literal: Const { ty: fn(((), ())) {use_zst}, val: Value(Scalar(<ZST>)) }
                                           // ty::Const
                                           // + ty: ((), ())
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify-locals-removes-unused-consts.rs:14:5: 14:22
                                           // + literal: Const { ty: ((), ()), val: Value(Scalar(<ZST>)) }
      }
  
      bb1: {
-         StorageDead(_5);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:21: 14:22
-         StorageDead(_4);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:22: 14:23
-         StorageLive(_8);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:5: 16:35
-         StorageLive(_9);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:34
-         StorageLive(_10);                // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:30
-         StorageLive(_11);                // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:28
-         _11 = const Temp { x: 40_u8 };   // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:28
+         StorageDead(_1);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:14:22: 14:23
+         StorageLive(_2);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:5: 16:35
+         _2 = const use_u8(const 42_u8) -> bb2; // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:5: 16:35
                                           // ty::Const
-                                          // + ty: Temp
-                                          // + val: Value(Scalar(0x28))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:28
-                                          // + literal: Const { ty: Temp, val: Value(Scalar(0x28)) }
-         _10 = const 40_u8;               // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:30
-                                          // ty::Const
-                                          // + ty: u8
-                                          // + val: Value(Scalar(0x28))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:30
-                                          // + literal: Const { ty: u8, val: Value(Scalar(0x28)) }
-         _9 = const 42_u8;                // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:34
-                                          // ty::Const
-                                          // + ty: u8
-                                          // + val: Value(Scalar(0x2a))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify-locals-removes-unused-consts.rs:16:12: 16:34
-                                          // + literal: Const { ty: u8, val: Value(Scalar(0x2a)) }
-         StorageDead(_10);                // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:33: 16:34
-         _8 = const use_u8(const 42_u8) -> bb2; // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:5: 16:35
-                                          // ty::Const
                                           // + ty: fn(u8) {use_u8}
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify-locals-removes-unused-consts.rs:16:5: 16:11
                                           // + literal: Const { ty: fn(u8) {use_u8}, val: Value(Scalar(<ZST>)) }
                                           // ty::Const
                                           // + ty: u8
                                           // + val: Value(Scalar(0x2a))
                                           // mir::Constant
                                           // + span: $DIR/simplify-locals-removes-unused-consts.rs:16:5: 16:35
                                           // + literal: Const { ty: u8, val: Value(Scalar(0x2a)) }
      }
  
      bb2: {
-         StorageDead(_9);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:34: 16:35
-         StorageDead(_11);                // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:35: 16:36
-         StorageDead(_8);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:35: 16:36
+         StorageDead(_2);                 // scope 1 at $DIR/simplify-locals-removes-unused-consts.rs:16:35: 16:36
          _0 = const ();                   // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:12:11: 17:2
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify-locals-removes-unused-consts.rs:12:11: 17:2
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
          return;                          // scope 0 at $DIR/simplify-locals-removes-unused-consts.rs:17:2: 17:2
      }
  }
  
