- // MIR for `borrowed_not_shortened_to_last_direct_use` before MoveElimination
+ // MIR for `borrowed_not_shortened_to_last_direct_use` after MoveElimination
  
  fn borrowed_not_shortened_to_last_direct_use(_1: u32) -> u32 {
      debug x => _1;
      let mut _0: u32;
      let _2: u32;
      let mut _5: u32;
      let mut _6: u32;
      let mut _7: u32;
      scope 1 {
-         debug a => _2;
+         debug a => _1;
          let _3: &u32;
          scope 2 {
              debug r => _3;
              let _4: u32;
              scope 3 {
-                 debug out => _4;
+                 debug out => _7;
              }
          }
      }
  
      bb0: {
-         StorageLive(_2);
-         _2 = copy _1;
+         nop;
+         nop;
+         nop;
          StorageLive(_3);
-         _3 = &_2;
-         StorageLive(_4);
-         _4 = copy _2;
-         StorageLive(_5);
+         _3 = &_1;
+         nop;
+         StorageLive(_7);
+         _7 = copy _1;
+         nop;
+         nop;
          StorageLive(_6);
          _6 = copy (*_3);
-         StorageLive(_7);
-         _7 = copy _4;
+         StorageDead(_3);
+         nop;
+         nop;
+         StorageLive(_5);
          _5 = Add(move _6, move _7);
-         StorageDead(_7);
          StorageDead(_6);
+         StorageDead(_7);
+         nop;
+         nop;
          _0 = opaque::<u32>(move _5) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          StorageDead(_5);
-         StorageDead(_4);
-         StorageDead(_3);
-         StorageDead(_2);
+         nop;
+         nop;
+         nop;
+         nop;
          return;
      }
  }
  
