const QUERY = ['fn:foo', 'enum : foo', 'macro<f>:foo'];

const PARSED = [
    {
        args: [],
        elemName: null,
        elems: [{
            name: "foo",
            fullPath: ["foo"],
            pathWithoutLast: [],
            pathLast: "foo",
            generics: [],
        }],
        foundElems: 1,
        id: "fn:foo",
        nameSplit: null,
        original: "fn:foo",
        returned: [],
        typeFilter: 5,
        userQuery: "fn:foo",
        error: null,
    },
    {
        args: [],
        elemName: null,
        elems: [{
            name: "foo",
            fullPath: ["foo"],
            pathWithoutLast: [],
            pathLast: "foo",
            generics: [],
        }],
        foundElems: 1,
        id: "enum : foo",
        nameSplit: null,
        original: "enum : foo",
        returned: [],
        typeFilter: 4,
        userQuery: "enum : foo",
        error: null,
    },
    {
        args: [],
        elemName: null,
        elems: [{
            name: "foo",
            fullPath: ["foo"],
            pathWithoutLast: [],
            pathLast: "foo",
            generics: [],
        }],
        foundElems: 1,
        id: "macro<f>:foo",
        nameSplit: null,
        original: "macro<f>:foo",
        returned: [],
        typeFilter: 14,
        userQuery: "macro<f>:foo",
        error: null,
    },
];
