- // MIR for `integer_transmutes` before InstSimplify
+ // MIR for `integer_transmutes` after InstSimplify
  
  fn integer_transmutes() -> () {
      let mut _0: ();
      let mut _1: u32;
      let mut _2: i64;
      let mut _3: usize;
  
      bb0: {
-         _1 = const 1_i32 as u32 (Transmute);
-         _2 = const 1_u64 as i64 (Transmute);
-         _3 = const 1_isize as usize (Transmute);
+         _1 = const 1_i32 as u32 (IntToInt);
+         _2 = const 1_u64 as i64 (IntToInt);
+         _3 = const 1_isize as usize (IntToInt);
          return;
      }
  }
  
