- // MIR for `borrowed` before CopyProp
+ // MIR for `borrowed` after CopyProp
  
  fn borrowed(_1: T) -> bool {
      let mut _0: bool;
      let mut _2: T;
      let mut _3: &T;
  
      bb0: {
-         _2 = _1;
          _3 = &_1;
          _0 = opaque::<&T>(_3) -> [return: bb1, unwind continue];
      }
  
      bb1: {
-         _0 = opaque::<T>(_2) -> [return: bb2, unwind continue];
+         _0 = opaque::<T>(_1) -> [return: bb2, unwind continue];
      }
  
      bb2: {
          return;
      }
  }
  
