- // MIR for `dead_twice` before CopyProp
+ // MIR for `dead_twice` after CopyProp
  
  fn dead_twice(_1: T) -> T {
      let mut _0: T;
      let mut _2: T;
      let mut _3: T;
      let mut _4: T;
  
      bb0: {
-         StorageLive(_2);
          _2 = opaque::<T>(move _1) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
-         _4 = move _2;
-         StorageDead(_2);
-         StorageLive(_2);
-         _0 = opaque::<T>(move _4) -> [return: bb2, unwind unreachable];
+         _0 = opaque::<T>(copy _2) -> [return: bb2, unwind unreachable];
      }
  
      bb2: {
-         StorageDead(_2);
          return;
      }
  }
  
