- // MIR for `f` before CopyProp
+ // MIR for `f` after CopyProp
  
  fn f(_1: &mut usize) -> () {
      let mut _0: ();
      let mut _2: usize;
      let mut _3: usize;
  
      bb0: {
          StorageLive(_2);
          _2 = const 42_usize;
-         _3 = copy _2;
-         (*_1) = copy _3;
+         (*_1) = copy _2;
          StorageDead(_2);
          return;
      }
  
      bb1: {
          StorageLive(_2);
-         (*_1) = copy _3;
+         (*_1) = copy _2;
          StorageDead(_2);
          return;
      }
  }
  
