- // MIR for `f_move` before CopyProp
+ // MIR for `f_move` after CopyProp
  
  fn f_move() -> () {
      let mut _0: ();
      let mut _1: S;
      let mut _2: S;
      let mut _3: S;
  
      bb0: {
          StorageLive(_1);
          _1 = S(const 1_u32, const 2_u32);
-         StorageLive(_2);
-         _2 = copy _1;
-         _3 = opaque::<S>(move _1) -> [return: bb1, unwind unreachable];
+         _3 = opaque::<S>(copy _1) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
-         StorageDead(_2);
          StorageDead(_1);
          return;
      }
  }
  
