- // MIR for `f` before CopyProp
+ // MIR for `f` after CopyProp
  
  fn f(_1: Foo) -> bool {
      let mut _0: bool;
      let mut _2: Foo;
      let mut _3: u8;
  
      bb0: {
-         _2 = _1;
-         _3 = move (_2.0: u8);
-         _0 = opaque::<Foo>(move _1) -> [return: bb1, unwind continue];
+         _3 = (_1.0: u8);
+         _0 = opaque::<Foo>(_1) -> [return: bb1, unwind continue];
      }
  
      bb1: {
          _0 = opaque::<u8>(move _3) -> [return: bb2, unwind continue];
      }
  
      bb2: {
          return;
      }
  }
  
