- // MIR for `foo` before DestinationPropagation
+ // MIR for `foo` after DestinationPropagation
  
  fn foo(_1: u8) -> () {
      debug x => _1;
      let mut _0: ();
      let mut _2: u8;
      let mut _3: u8;
  
      bb0: {
-         StorageLive(_2);
+         nop;
          StorageLive(_3);
          _3 = _1;
-         _2 = dummy(move _3) -> bb1;
+         _1 = dummy(move _3) -> bb1;
      }
  
      bb1: {
          StorageDead(_3);
-         _1 = move _2;
-         StorageDead(_2);
+         nop;
+         nop;
          _0 = const ();
          return;
      }
  }
  
