- // MIR for `nrvo` before DestinationPropagation
+ // MIR for `nrvo` after DestinationPropagation
  
  fn nrvo(_1: for<'a> fn(&'a mut [u8; 1024])) -> [u8; 1024] {
      debug init => _1;                    // in scope 0 at $DIR/simple.rs:+0:9: +0:13
      let mut _0: [u8; 1024];              // return place in scope 0 at $DIR/simple.rs:+0:39: +0:49
      let mut _2: [u8; 1024];              // in scope 0 at $DIR/simple.rs:+1:9: +1:16
      let _3: ();                          // in scope 0 at $DIR/simple.rs:+2:5: +2:19
      let mut _4: for<'a> fn(&'a mut [u8; 1024]); // in scope 0 at $DIR/simple.rs:+2:5: +2:9
      let mut _5: &mut [u8; 1024];         // in scope 0 at $DIR/simple.rs:+2:10: +2:18
      let mut _6: &mut [u8; 1024];         // in scope 0 at $DIR/simple.rs:+2:10: +2:18
      scope 1 {
          debug buf => _2;                 // in scope 1 at $DIR/simple.rs:+1:9: +1:16
      }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/simple.rs:+1:9: +1:16
          _2 = [const 0_u8; 1024];         // scope 0 at $DIR/simple.rs:+1:19: +1:28
          StorageLive(_3);                 // scope 1 at $DIR/simple.rs:+2:5: +2:19
-         StorageLive(_4);                 // scope 1 at $DIR/simple.rs:+2:5: +2:9
-         _4 = _1;                         // scope 1 at $DIR/simple.rs:+2:5: +2:9
+         nop;                             // scope 1 at $DIR/simple.rs:+2:5: +2:9
+         nop;                             // scope 1 at $DIR/simple.rs:+2:5: +2:9
          StorageLive(_5);                 // scope 1 at $DIR/simple.rs:+2:10: +2:18
          StorageLive(_6);                 // scope 1 at $DIR/simple.rs:+2:10: +2:18
          _6 = &mut _2;                    // scope 1 at $DIR/simple.rs:+2:10: +2:18
          _5 = &mut (*_6);                 // scope 1 at $DIR/simple.rs:+2:10: +2:18
-         _3 = move _4(move _5) -> [return: bb1, unwind unreachable]; // scope 1 at $DIR/simple.rs:+2:5: +2:19
+         _3 = move _1(move _5) -> [return: bb1, unwind unreachable]; // scope 1 at $DIR/simple.rs:+2:5: +2:19
      }
  
      bb1: {
          StorageDead(_5);                 // scope 1 at $DIR/simple.rs:+2:18: +2:19
-         StorageDead(_4);                 // scope 1 at $DIR/simple.rs:+2:18: +2:19
+         nop;                             // scope 1 at $DIR/simple.rs:+2:18: +2:19
          StorageDead(_6);                 // scope 1 at $DIR/simple.rs:+2:19: +2:20
          StorageDead(_3);                 // scope 1 at $DIR/simple.rs:+2:19: +2:20
          _0 = _2;                         // scope 1 at $DIR/simple.rs:+3:5: +3:8
          StorageDead(_2);                 // scope 0 at $DIR/simple.rs:+4:1: +4:2
          return;                          // scope 0 at $DIR/simple.rs:+4:2: +4:2
      }
  }
  
