- // MIR for `main` before DestinationPropagation
+ // MIR for `main` after DestinationPropagation
  
  fn main() -> () {
      let mut _0: ();
      let _1: main::Un;
      let mut _2: u32;
      scope 1 {
          debug un => const Un {{ us: 1_u32 }};
          scope 3 (inlined std::mem::drop::<u32>) {
              debug _x => const 1_u32;
          }
      }
      scope 2 (inlined val) {
      }
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
          StorageDead(_2);
          StorageDead(_1);
          return;
      }
  }
  
  ALLOC0 (size: 4, align: 4) {
      01 00 00 00                                     │ ....
  }
  
