#![allow(non_upper_case_globals)]

use rustc_span::symbol::PREDEFINED_SYMBOLS_COUNT;

#[doc(no_inline)]
pub use rustc_span::sym::*;

macro_rules! val {
    ($name:ident) => {
        stringify!($name)
    };
    ($name:ident $value:literal) => {
        $value
    };
}

macro_rules! generate {
    ($($name:ident $(: $value:literal)? ,)*) => {
        /// To be supplied to `rustc_interface::Config`
        pub const EXTRA_SYMBOLS: &[&str] = &[
            $(
                val!($name $($value)?),
            )*
        ];

        $(
            pub const $name: rustc_span::Symbol = rustc_span::Symbol::new(PREDEFINED_SYMBOLS_COUNT + ${index()});
        )*
    };
}

generate! {
    abs,
    align_of,
    as_bytes,
    as_deref_mut,
    as_deref,
    as_mut,
    AsyncReadExt,
    AsyncWriteExt,
    Binary,
    build_hasher,
    bytes,
    cargo_clippy: "cargo-clippy",
    Cargo_toml: "Cargo.toml",
    cast,
    chars,
    CLIPPY_ARGS,
    CLIPPY_CONF_DIR,
    clippy_utils,
    clone_into,
    cloned,
    collect,
    const_ptr,
    contains,
    copied,
    CRLF: "\r\n",
    Current,
    de,
    Deserialize,
    diagnostics,
    EarlyLintPass,
    ends_with,
    error,
    ErrorKind,
    exp,
    extend,
    finish_non_exhaustive,
    finish,
    flat_map,
    for_each,
    from_raw,
    from_ref,
    from_str_radix,
    fs,
    futures_util,
    get,
    hygiene,
    insert,
    int_roundings,
    into_bytes,
    into_owned,
    IntoIter,
    io,
    is_ascii,
    is_empty,
    is_err,
    is_none,
    is_ok,
    is_some,
    itertools,
    Itertools,
    kw,
    last,
    lazy_static,
    Lazy,
    LF: "\n",
    Lint,
    lock_api,
    LowerExp,
    LowerHex,
    max,
    MAX,
    mem,
    min,
    MIN,
    mode,
    msrv,
    msrvs,
    MsrvStack,
    mut_ptr,
    mutex,
    next_tuple,
    Octal,
    once_cell,
    OpenOptions,
    or_default,
    Other,
    parse,
    PathLookup,
    paths,
    push,
    regex,
    Regex,
    RegexBuilder,
    RegexSet,
    reserve,
    resize,
    restriction,
    rustc_lint_defs,
    rustc_lint,
    rustc_span,
    rustfmt_skip,
    rwlock,
    serde,
    set_len,
    set_mode,
    set_readonly,
    signum,
    span_lint_and_then,
    split_whitespace,
    split,
    Start,
    Step,
    symbol,
    Symbol,
    SyntaxContext,
    take,
    TBD,
    then_some,
    to_digit,
    to_owned,
    tokio,
    unused_extern_crates,
    unwrap_err,
    unwrap_or_default,
    UpperExp,
    UpperHex,
    V4,
    V6,
    Visitor,
    Weak,
    with_capacity,
    wrapping_offset,
}
