#![allow(non_upper_case_globals)]

use rustc_span::symbol::PREDEFINED_SYMBOLS_COUNT;

#[doc(no_inline)]
pub use rustc_span::sym::*;

macro_rules! val {
    ($name:ident) => {
        stringify!($name)
    };
    ($name:ident $value:literal) => {
        $value
    };
}

macro_rules! generate {
    ($($name:ident $(: $value:literal)? ,)*) => {
        /// To be supplied to `rustc_interface::Config`
        pub const EXTRA_SYMBOLS: &[&str] = &[
            $(
                val!($name $($value)?),
            )*
        ];

        $(
            pub const $name: rustc_span::Symbol = rustc_span::Symbol::new(PREDEFINED_SYMBOLS_COUNT + ${index()});
        )*
    };
}

// List of extra symbols to be included in Clippy (for example, as `sym::ambiguous_glob_reexports`).
// An alternative content can be specified using a colon after the symbol name.
generate! {
    AsyncReadExt,
    AsyncWriteExt,
    BACKSLASH_SINGLE_QUOTE: r"\'",
    Binary,
    CLIPPY_ARGS,
    CLIPPY_CONF_DIR,
    CRLF: "\r\n",
    Cargo_toml: "Cargo.toml",
    Current,
    DOUBLE_QUOTE: "\"",
    Deserialize,
    EarlyLintPass,
    ErrorKind,
    IntoIter,
    Itertools,
    LF: "\n",
    Lazy,
    Lint,
    LowerExp,
    LowerHex,
    MAX,
    MIN,
    MsrvStack,
    Octal,
    OpenOptions,
    Other,
    PathLookup,
    Regex,
    RegexBuilder,
    RegexSet,
    Start,
    Step,
    Symbol,
    SyntaxContext,
    TBD,
    UpperExp,
    UpperHex,
    V4,
    V6,
    Visitor,
    Weak,
    abs,
    align_of,
    ambiguous_glob_reexports,
    as_bytes,
    as_deref,
    as_deref_mut,
    as_mut,
    build_hasher,
    bytes,
    cargo_clippy: "cargo-clippy",
    cast,
    chars,
    clippy_utils,
    clone_into,
    cloned,
    collect,
    const_ptr,
    contains,
    copied,
    de,
    diagnostics,
    disallowed_types,
    ends_with,
    enum_glob_use,
    error,
    exp,
    extend,
    finish,
    finish_non_exhaustive,
    flat_map,
    for_each,
    from_bytes_with_nul,
    from_bytes_with_nul_unchecked,
    from_ptr,
    from_raw,
    from_ref,
    from_str_radix,
    fs,
    futures_util,
    get,
    hidden_glob_reexports,
    hygiene,
    insert,
    int_roundings,
    into_bytes,
    into_owned,
    io,
    is_ascii,
    is_empty,
    is_err,
    is_none,
    is_ok,
    is_some,
    itertools,
    kw,
    last,
    lazy_static,
    ln,
    lock_api,
    log,
    macro_use_imports,
    map_or,
    map_or_else,
    max,
    mem,
    min,
    mode,
    module_name_repetitions,
    msrv,
    msrvs,
    mut_ptr,
    mutex,
    needless_return,
    next_tuple,
    once_cell,
    or_default,
    parse,
    paths,
    powf,
    powi,
    push,
    redundant_pub_crate,
    regex,
    reserve,
    resize,
    restriction,
    rustc_lint,
    rustc_lint_defs,
    rustc_span,
    rustfmt_skip,
    rwlock,
    serde,
    set_len,
    set_mode,
    set_readonly,
    signum,
    single_component_path_imports,
    span_lint_and_then,
    split,
    split_whitespace,
    sqrt,
    style,
    symbol,
    take,
    then_some,
    to_ascii_lowercase,
    to_ascii_uppercase,
    to_digit,
    to_lowercase,
    to_owned,
    to_uppercase,
    tokio,
    unreachable_pub,
    unsafe_removed_from_name,
    unused,
    unused_braces,
    unused_extern_crates,
    unused_import_braces,
    unused_trait_names,
    unwrap_err,
    unwrap_or_default,
    unwrap_or_else,
    warnings,
    wildcard_imports,
    with_capacity,
    wrapping_offset,
}
