- // MIR for `test` before DataflowConstProp
+ // MIR for `test` after DataflowConstProp
  
  fn test(_1: bool, _2: bool) -> bool {
      debug x => _1;                       // in scope 0 at $DIR/boolean_identities.rs:+0:13: +0:14
      debug y => _2;                       // in scope 0 at $DIR/boolean_identities.rs:+0:22: +0:23
      let mut _0: bool;                    // return place in scope 0 at $DIR/boolean_identities.rs:+0:34: +0:38
      let mut _3: bool;                    // in scope 0 at $DIR/boolean_identities.rs:+1:5: +1:15
      let mut _4: bool;                    // in scope 0 at $DIR/boolean_identities.rs:+1:6: +1:7
      let mut _5: bool;                    // in scope 0 at $DIR/boolean_identities.rs:+1:18: +1:29
      let mut _6: bool;                    // in scope 0 at $DIR/boolean_identities.rs:+1:19: +1:20
  
      bb0: {
          StorageLive(_3);                 // scope 0 at $DIR/boolean_identities.rs:+1:5: +1:15
          StorageLive(_4);                 // scope 0 at $DIR/boolean_identities.rs:+1:6: +1:7
          _4 = _2;                         // scope 0 at $DIR/boolean_identities.rs:+1:6: +1:7
          _3 = const true;                 // scope 0 at $DIR/boolean_identities.rs:+1:5: +1:15
          StorageDead(_4);                 // scope 0 at $DIR/boolean_identities.rs:+1:14: +1:15
          StorageLive(_5);                 // scope 0 at $DIR/boolean_identities.rs:+1:18: +1:29
          StorageLive(_6);                 // scope 0 at $DIR/boolean_identities.rs:+1:19: +1:20
          _6 = _1;                         // scope 0 at $DIR/boolean_identities.rs:+1:19: +1:20
          _5 = const false;                // scope 0 at $DIR/boolean_identities.rs:+1:18: +1:29
          StorageDead(_6);                 // scope 0 at $DIR/boolean_identities.rs:+1:28: +1:29
          _0 = const false;                // scope 0 at $DIR/boolean_identities.rs:+1:5: +1:29
          StorageDead(_5);                 // scope 0 at $DIR/boolean_identities.rs:+1:28: +1:29
          StorageDead(_3);                 // scope 0 at $DIR/boolean_identities.rs:+1:28: +1:29
          return;                          // scope 0 at $DIR/boolean_identities.rs:+2:2: +2:2
      }
  }
  
