- // MIR for `main` before DataflowConstProp
+ // MIR for `main` after DataflowConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/issue-67019.rs:+0:11: +0:11
      let _1: ();                          // in scope 0 at $DIR/issue-67019.rs:+1:5: +1:20
      let mut _2: ((u8, u8),);             // in scope 0 at $DIR/issue-67019.rs:+1:10: +1:19
      let mut _3: (u8, u8);                // in scope 0 at $DIR/issue-67019.rs:+1:11: +1:17
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/issue-67019.rs:+1:5: +1:20
          StorageLive(_2);                 // scope 0 at $DIR/issue-67019.rs:+1:10: +1:19
          StorageLive(_3);                 // scope 0 at $DIR/issue-67019.rs:+1:11: +1:17
          Deinit(_3);                      // scope 0 at $DIR/issue-67019.rs:+1:11: +1:17
          (_3.0: u8) = const 1_u8;         // scope 0 at $DIR/issue-67019.rs:+1:11: +1:17
          (_3.1: u8) = const 2_u8;         // scope 0 at $DIR/issue-67019.rs:+1:11: +1:17
          Deinit(_2);                      // scope 0 at $DIR/issue-67019.rs:+1:10: +1:19
          (_2.0: (u8, u8)) = const (1_u8, 2_u8); // scope 0 at $DIR/issue-67019.rs:+1:10: +1:19
          StorageDead(_3);                 // scope 0 at $DIR/issue-67019.rs:+1:18: +1:19
          _1 = test(move _2) -> bb1;       // scope 0 at $DIR/issue-67019.rs:+1:5: +1:20
                                           // mir::Constant
                                           // + span: $DIR/issue-67019.rs:12:5: 12:9
                                           // + literal: Const { ty: fn(((u8, u8),)) {test}, val: Value(<ZST>) }
      }
  
      bb1: {
          StorageDead(_2);                 // scope 0 at $DIR/issue-67019.rs:+1:19: +1:20
          StorageDead(_1);                 // scope 0 at $DIR/issue-67019.rs:+1:20: +1:21
          nop;                             // scope 0 at $DIR/issue-67019.rs:+0:11: +2:2
          return;                          // scope 0 at $DIR/issue-67019.rs:+2:2: +2:2
      }
  }
  
