- // MIR for `main` before DataflowConstProp
+ // MIR for `main` after DataflowConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/large_array_index.rs:+0:11: +0:11
      let _1: u8;                          // in scope 0 at $DIR/large_array_index.rs:+2:9: +2:10
      let mut _2: [u8; 5000];              // in scope 0 at $DIR/large_array_index.rs:+2:17: +2:29
      let _3: usize;                       // in scope 0 at $DIR/large_array_index.rs:+2:30: +2:31
      let mut _4: usize;                   // in scope 0 at $DIR/large_array_index.rs:+2:17: +2:32
      let mut _5: bool;                    // in scope 0 at $DIR/large_array_index.rs:+2:17: +2:32
      scope 1 {
          debug x => _1;                   // in scope 1 at $DIR/large_array_index.rs:+2:9: +2:10
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/large_array_index.rs:+2:9: +2:10
          StorageLive(_2);                 // scope 0 at $DIR/large_array_index.rs:+2:17: +2:29
          _2 = [const 0_u8; 5000];         // scope 0 at $DIR/large_array_index.rs:+2:17: +2:29
          StorageLive(_3);                 // scope 0 at $DIR/large_array_index.rs:+2:30: +2:31
          _3 = const 2_usize;              // scope 0 at $DIR/large_array_index.rs:+2:30: +2:31
          _4 = const 5000_usize;           // scope 0 at $DIR/large_array_index.rs:+2:17: +2:32
          _5 = const true;                 // scope 0 at $DIR/large_array_index.rs:+2:17: +2:32
          assert(const true, "index out of bounds: the length is {} but the index is {}", const 5000_usize, const 2_usize) -> bb1; // scope 0 at $DIR/large_array_index.rs:+2:17: +2:32
      }
  
      bb1: {
          _1 = _2[_3];                     // scope 0 at $DIR/large_array_index.rs:+2:17: +2:32
          StorageDead(_3);                 // scope 0 at $DIR/large_array_index.rs:+2:32: +2:33
          StorageDead(_2);                 // scope 0 at $DIR/large_array_index.rs:+2:32: +2:33
          nop;                             // scope 0 at $DIR/large_array_index.rs:+0:11: +3:2
          StorageDead(_1);                 // scope 0 at $DIR/large_array_index.rs:+3:1: +3:2
          return;                          // scope 0 at $DIR/large_array_index.rs:+3:2: +3:2
      }
  }
  
