- // MIR for `test` before DataflowConstProp
+ // MIR for `test` after DataflowConstProp
  
  fn test(_1: i32) -> i32 {
      debug x => _1;                       // in scope 0 at $DIR/mult_by_zero.rs:+0:9: +0:10
      let mut _0: i32;                     // return place in scope 0 at $DIR/mult_by_zero.rs:+0:20: +0:23
      let mut _2: i32;                     // in scope 0 at $DIR/mult_by_zero.rs:+1:5: +1:6
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/mult_by_zero.rs:+1:5: +1:6
          _2 = _1;                         // scope 0 at $DIR/mult_by_zero.rs:+1:5: +1:6
          _0 = const 0_i32;                // scope 0 at $DIR/mult_by_zero.rs:+1:5: +1:10
          StorageDead(_2);                 // scope 0 at $DIR/mult_by_zero.rs:+1:9: +1:10
          return;                          // scope 0 at $DIR/mult_by_zero.rs:+2:2: +2:2
      }
  }
  
