- // MIR for `main` before SimplifyCfg-initial
+ // MIR for `main` after SimplifyCfg-initial
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/simplify_cfg.rs:5:11: 5:11
      let mut _1: ();                      // in scope 0 at $DIR/simplify_cfg.rs:5:1: 11:2
      let mut _2: bool;                    // in scope 0 at $DIR/simplify_cfg.rs:7:12: 7:17
      let mut _3: !;                       // in scope 0 at $DIR/simplify_cfg.rs:7:18: 9:10
  
      bb0: {
-         goto -> bb1;                     // scope 0 at $DIR/simplify_cfg.rs:6:5: 10:6
+         falseUnwind -> [real: bb1, cleanup: bb2]; // scope 0 at $DIR/simplify_cfg.rs:6:5: 10:6
      }
  
      bb1: {
-         falseUnwind -> [real: bb3, cleanup: bb4]; // scope 0 at $DIR/simplify_cfg.rs:6:5: 10:6
-     }
- 
-     bb2: {
-         goto -> bb13;                    // scope 0 at $DIR/simplify_cfg.rs:11:2: 11:2
-     }
- 
-     bb3: {
          StorageLive(_2);                 // scope 0 at $DIR/simplify_cfg.rs:7:12: 7:17
-         _2 = const bar() -> [return: bb5, unwind: bb4]; // scope 0 at $DIR/simplify_cfg.rs:7:12: 7:17
+         _2 = const bar() -> [return: bb3, unwind: bb2]; // scope 0 at $DIR/simplify_cfg.rs:7:12: 7:17
                                           // ty::Const
                                           // + ty: fn() -> bool {bar}
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify_cfg.rs:7:12: 7:15
                                           // + literal: Const { ty: fn() -> bool {bar}, val: Value(Scalar(<ZST>)) }
      }
  
-     bb4 (cleanup): {
+     bb2 (cleanup): {
          resume;                          // scope 0 at $DIR/simplify_cfg.rs:5:1: 11:2
      }
  
-     bb5: {
+     bb3: {
          FakeRead(ForMatchedPlace, _2);   // scope 0 at $DIR/simplify_cfg.rs:7:12: 7:17
-         switchInt(_2) -> [false: bb7, otherwise: bb6]; // scope 0 at $DIR/simplify_cfg.rs:7:9: 9:10
+         switchInt(_2) -> [false: bb5, otherwise: bb4]; // scope 0 at $DIR/simplify_cfg.rs:7:9: 9:10
      }
  
-     bb6: {
-         falseEdge -> [real: bb8, imaginary: bb7]; // scope 0 at $DIR/simplify_cfg.rs:7:9: 9:10
+     bb4: {
+         falseEdge -> [real: bb6, imaginary: bb5]; // scope 0 at $DIR/simplify_cfg.rs:7:9: 9:10
      }
  
-     bb7: {
+     bb5: {
          _1 = const ();                   // scope 0 at $DIR/simplify_cfg.rs:7:9: 9:10
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify_cfg.rs:7:9: 9:10
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
-         goto -> bb12;                    // scope 0 at $DIR/simplify_cfg.rs:7:9: 9:10
+         StorageDead(_2);                 // scope 0 at $DIR/simplify_cfg.rs:10:5: 10:6
+         goto -> bb0;                     // scope 0 at $DIR/simplify_cfg.rs:6:5: 10:6
      }
  
-     bb8: {
+     bb6: {
          _0 = const ();                   // scope 0 at $DIR/simplify_cfg.rs:8:13: 8:18
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify_cfg.rs:8:13: 8:18
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
-         goto -> bb9;                     // scope 0 at $DIR/simplify_cfg.rs:8:13: 8:18
-     }
- 
-     bb9: {
          StorageDead(_2);                 // scope 0 at $DIR/simplify_cfg.rs:10:5: 10:6
-         goto -> bb2;                     // scope 0 at $DIR/simplify_cfg.rs:8:13: 8:18
-     }
- 
-     bb10: {
-         unreachable;                     // scope 0 at $DIR/simplify_cfg.rs:7:18: 9:10
-     }
- 
-     bb11: {
-         goto -> bb12;                    // scope 0 at $DIR/simplify_cfg.rs:7:9: 9:10
-     }
- 
-     bb12: {
-         StorageDead(_2);                 // scope 0 at $DIR/simplify_cfg.rs:10:5: 10:6
-         goto -> bb1;                     // scope 0 at $DIR/simplify_cfg.rs:6:5: 10:6
-     }
- 
-     bb13: {
          return;                          // scope 0 at $DIR/simplify_cfg.rs:11:2: 11:2
      }
  }
  
