- // MIR for `main` before GVN
+ // MIR for `main` after GVN
  
  fn main() -> () {
      let mut _0: ();
      let _1: std::alloc::Layout;
      let mut _2: std::option::Option<std::alloc::Layout>;
      let mut _3: *mut u8;
      let mut _4: *mut [u8];
      let mut _5: std::ptr::NonNull<[u8]>;
      let mut _6: std::result::Result<std::ptr::NonNull<[u8]>, std::alloc::AllocError>;
      let mut _7: std::alloc::Layout;
      scope 1 {
          debug layout => _1;
          scope 2 {
              debug ptr => _3;
          }
          scope 5 (inlined <std::alloc::Global as Allocator>::allocate) {
              scope 6 (inlined std::alloc::Global::alloc_impl) {
              }
          }
          scope 7 (inlined #[track_caller] Result::<NonNull<[u8]>, std::alloc::AllocError>::unwrap) {
              let mut _10: isize;
              let _11: std::alloc::AllocError;
              let mut _12: !;
              let mut _13: &dyn std::fmt::Debug;
              let _14: &std::alloc::AllocError;
              scope 8 {
              }
              scope 9 {
              }
          }
          scope 10 (inlined NonNull::<[u8]>::as_ptr) {
          }
      }
      scope 3 (inlined #[track_caller] Option::<Layout>::unwrap) {
          let mut _8: isize;
          let mut _9: !;
          scope 4 {
          }
      }
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
-         _2 = Option::<Layout>::None;
+         _2 = const Option::<Layout>::None;
          StorageLive(_8);
-         _8 = discriminant(_2);
-         switchInt(move _8) -> [0: bb2, 1: bb3, otherwise: bb1];
+         _8 = const 0_isize;
+         switchInt(const 0_isize) -> [0: bb2, 1: bb3, otherwise: bb1];
      }
  
      bb1: {
          unreachable;
      }
  
      bb2: {
          _9 = option::unwrap_failed() -> unwind unreachable;
      }
  
      bb3: {
-         _1 = move ((_2 as Some).0: std::alloc::Layout);
+         _1 = const Layout {{ size: Indirect { alloc_id: ALLOC0, offset: Size(8 bytes) }: usize, align: std::mem::Alignment {{ _inner_repr_trick: Scalar(0x0000000000000000): mem::alignment::AlignmentEnum }} }};
          StorageDead(_8);
          StorageDead(_2);
          StorageLive(_3);
          StorageLive(_4);
          StorageLive(_5);
          StorageLive(_6);
          StorageLive(_7);
-         _7 = copy _1;
-         _6 = std::alloc::Global::alloc_impl_runtime(move _7, const false) -> [return: bb4, unwind unreachable];
+         _7 = const Layout {{ size: Indirect { alloc_id: ALLOC0, offset: Size(8 bytes) }: usize, align: std::mem::Alignment {{ _inner_repr_trick: Scalar(0x0000000000000000): mem::alignment::AlignmentEnum }} }};
+         _6 = std::alloc::Global::alloc_impl_runtime(const Layout {{ size: Indirect { alloc_id: ALLOC0, offset: Size(8 bytes) }: usize, align: std::mem::Alignment {{ _inner_repr_trick: Scalar(0x0000000000000000): mem::alignment::AlignmentEnum }} }}, const false) -> [return: bb4, unwind unreachable];
      }
  
      bb4: {
          StorageDead(_7);
          StorageLive(_10);
          _10 = discriminant(_6);
          switchInt(move _10) -> [0: bb6, 1: bb5, otherwise: bb1];
      }
  
      bb5: {
          StorageLive(_13);
          StorageLive(_14);
          _14 = &_11;
          _13 = copy _14 as &dyn std::fmt::Debug (PointerCoercion(Unsize, Implicit));
          _12 = result::unwrap_failed(const "called `Result::unwrap()` on an `Err` value", move _13) -> unwind unreachable;
      }
  
      bb6: {
          _5 = move ((_6 as Ok).0: std::ptr::NonNull<[u8]>);
          StorageDead(_10);
          StorageDead(_6);
          _4 = copy _5 as *mut [u8] (Transmute);
          StorageDead(_5);
          _3 = copy _4 as *mut u8 (PtrToPtr);
          StorageDead(_4);
          StorageDead(_3);
          StorageDead(_1);
          return;
      }
  }
  
- ALLOC0 (size: 43, align: 1) {
+ ALLOC0 (size: 16, align: 8) {
+     00 00 00 00 00 00 00 00 __ __ __ __ __ __ __ __ │ ........░░░░░░░░
+ }
+ 
+ ALLOC1 (size: 43, align: 1) {
      0x00 │ 63 61 6c 6c 65 64 20 60 52 65 73 75 6c 74 3a 3a │ called `Result::
      0x10 │ 75 6e 77 72 61 70 28 29 60 20 6f 6e 20 61 6e 20 │ unwrap()` on an 
      0x20 │ 60 45 72 72 60 20 76 61 6c 75 65                │ `Err` value
  }
  
