- // MIR for `main` before SimplifyBranches-after-const-prop
+ // MIR for `main` after SimplifyBranches-after-const-prop
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/simplify_if.rs:5:11: 5:11
      let mut _1: bool;                    // in scope 0 at $DIR/simplify_if.rs:6:8: 6:13
      let _2: ();                          // in scope 0 at $DIR/simplify_if.rs:7:9: 7:15
  
      bb0: {
          StorageLive(_1);                 // bb0[0]: scope 0 at $DIR/simplify_if.rs:6:8: 6:13
          _1 = const false;                // bb0[1]: scope 0 at $DIR/simplify_if.rs:6:8: 6:13
                                           // ty::Const
                                           // + ty: bool
                                           // + val: Value(Scalar(0x00))
                                           // mir::Constant
                                           // + span: $DIR/simplify_if.rs:6:8: 6:13
                                           // + literal: Const { ty: bool, val: Value(Scalar(0x00)) }
-         switchInt(const false) -> [false: bb1, otherwise: bb2]; // bb0[2]: scope 0 at $DIR/simplify_if.rs:6:5: 8:6
-                                          // ty::Const
-                                          // + ty: bool
-                                          // + val: Value(Scalar(0x00))
-                                          // mir::Constant
-                                          // + span: $DIR/simplify_if.rs:6:5: 8:6
-                                          // + literal: Const { ty: bool, val: Value(Scalar(0x00)) }
+         goto -> bb1;                     // bb0[2]: scope 0 at $DIR/simplify_if.rs:6:5: 8:6
      }
  
      bb1: {
          _0 = const ();                   // bb1[0]: scope 0 at $DIR/simplify_if.rs:6:5: 8:6
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify_if.rs:6:5: 8:6
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
          goto -> bb4;                     // bb1[1]: scope 0 at $DIR/simplify_if.rs:6:5: 8:6
      }
  
      bb2: {
          StorageLive(_2);                 // bb2[0]: scope 0 at $DIR/simplify_if.rs:7:9: 7:15
          _2 = const noop() -> bb3;        // bb2[1]: scope 0 at $DIR/simplify_if.rs:7:9: 7:15
                                           // ty::Const
                                           // + ty: fn() {noop}
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify_if.rs:7:9: 7:13
                                           // + literal: Const { ty: fn() {noop}, val: Value(Scalar(<ZST>)) }
      }
  
      bb3: {
          StorageDead(_2);                 // bb3[0]: scope 0 at $DIR/simplify_if.rs:7:15: 7:16
          _0 = const ();                   // bb3[1]: scope 0 at $DIR/simplify_if.rs:6:14: 8:6
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/simplify_if.rs:6:14: 8:6
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
          goto -> bb4;                     // bb3[2]: scope 0 at $DIR/simplify_if.rs:6:5: 8:6
      }
  
      bb4: {
          StorageDead(_1);                 // bb4[0]: scope 0 at $DIR/simplify_if.rs:9:1: 9:2
          return;                          // bb4[1]: scope 0 at $DIR/simplify_if.rs:9:2: 9:2
      }
  }
  
