- // MIR for `unreachable_direct` before DataflowConstProp
+ // MIR for `unreachable_direct` after DataflowConstProp
  
  fn unreachable_direct() -> ! {
      let mut _0: !;
      let _1: Never;
      let mut _2: ();
      scope 1 {
          debug x => _1;
      }
      scope 2 {
      }
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
-         _2 = ();
-         _1 = move _2 as Never (Transmute);
+         _2 = const ();
+         _1 = const ZeroSized: Never;
          unreachable;
      }
  }
  
