- // MIR for `main` before DataflowConstProp
+ // MIR for `main` after DataflowConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/recursive.rs:+0:11: +0:11
      let _1: S<'_>;                       // in scope 0 at $DIR/recursive.rs:+2:9: +2:10
      let mut _3: &S<'_>;                  // in scope 0 at $DIR/recursive.rs:+3:20: +3:22
      let _4: &S<'_>;                      // in scope 0 at $DIR/recursive.rs:+3:20: +3:22
      let mut _6: &S<'_>;                  // in scope 0 at $DIR/recursive.rs:+4:20: +4:22
      let _7: &S<'_>;                      // in scope 0 at $DIR/recursive.rs:+4:20: +4:22
      let mut _9: isize;                   // in scope 0 at $DIR/recursive.rs:+6:9: +6:18
      let mut _11: isize;                  // in scope 0 at $DIR/recursive.rs:+7:13: +7:22
      let mut _13: isize;                  // in scope 0 at $DIR/recursive.rs:+8:17: +8:28
      let mut _15: !;                      // in scope 0 at $DIR/recursive.rs:+9:22: +9:43
      let mut _16: !;                      // in scope 0 at $DIR/recursive.rs:+11:18: +11:39
      let mut _17: !;                      // in scope 0 at $DIR/recursive.rs:+13:14: +13:35
      let mut _18: &S<'_>;                 // in scope 0 at $DIR/recursive.rs:+7:20: +7:21
      let mut _19: &S<'_>;                 // in scope 0 at $DIR/recursive.rs:+7:20: +7:21
      scope 1 {
          debug a => _1;                   // in scope 1 at $DIR/recursive.rs:+2:9: +2:10
          let _2: S<'_>;                   // in scope 1 at $DIR/recursive.rs:+3:9: +3:10
          scope 2 {
              debug b => _2;               // in scope 2 at $DIR/recursive.rs:+3:9: +3:10
              let _5: S<'_>;               // in scope 2 at $DIR/recursive.rs:+4:9: +4:10
              scope 3 {
                  debug c => _5;           // in scope 3 at $DIR/recursive.rs:+4:9: +4:10
                  let _8: u32;             // in scope 3 at $DIR/recursive.rs:+5:9: +5:10
                  let _10: &S<'_>;         // in scope 3 at $DIR/recursive.rs:+6:16: +6:17
                  scope 4 {
                      debug d => _8;       // in scope 4 at $DIR/recursive.rs:+5:9: +5:10
                  }
                  scope 5 {
                      debug b => _10;      // in scope 5 at $DIR/recursive.rs:+6:16: +6:17
                      let _12: &&S<'_>;    // in scope 5 at $DIR/recursive.rs:+7:20: +7:21
                      scope 6 {
                          debug a => _12;  // in scope 6 at $DIR/recursive.rs:+7:20: +7:21
                          let _14: &u32;   // in scope 6 at $DIR/recursive.rs:+8:24: +8:27
                          scope 7 {
                              debug num => _14; // in scope 7 at $DIR/recursive.rs:+8:24: +8:27
                          }
                      }
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/recursive.rs:+2:9: +2:10
          Deinit(_1);                      // scope 0 at $DIR/recursive.rs:+2:13: +2:22
          ((_1 as Num).0: u32) = const 0_u32; // scope 0 at $DIR/recursive.rs:+2:13: +2:22
          discriminant(_1) = 1;            // scope 0 at $DIR/recursive.rs:+2:13: +2:22
          StorageLive(_2);                 // scope 1 at $DIR/recursive.rs:+3:9: +3:10
          StorageLive(_3);                 // scope 1 at $DIR/recursive.rs:+3:20: +3:22
          StorageLive(_4);                 // scope 1 at $DIR/recursive.rs:+3:20: +3:22
          _4 = &_1;                        // scope 1 at $DIR/recursive.rs:+3:20: +3:22
          _3 = &(*_4);                     // scope 1 at $DIR/recursive.rs:+3:20: +3:22
          Deinit(_2);                      // scope 1 at $DIR/recursive.rs:+3:13: +3:23
          ((_2 as Rec).0: &S<'_>) = move _3; // scope 1 at $DIR/recursive.rs:+3:13: +3:23
          discriminant(_2) = 0;            // scope 1 at $DIR/recursive.rs:+3:13: +3:23
          StorageDead(_3);                 // scope 1 at $DIR/recursive.rs:+3:22: +3:23
          StorageDead(_4);                 // scope 1 at $DIR/recursive.rs:+3:23: +3:24
          StorageLive(_5);                 // scope 2 at $DIR/recursive.rs:+4:9: +4:10
          StorageLive(_6);                 // scope 2 at $DIR/recursive.rs:+4:20: +4:22
          StorageLive(_7);                 // scope 2 at $DIR/recursive.rs:+4:20: +4:22
          _7 = &_2;                        // scope 2 at $DIR/recursive.rs:+4:20: +4:22
          _6 = &(*_7);                     // scope 2 at $DIR/recursive.rs:+4:20: +4:22
          Deinit(_5);                      // scope 2 at $DIR/recursive.rs:+4:13: +4:23
          ((_5 as Rec).0: &S<'_>) = move _6; // scope 2 at $DIR/recursive.rs:+4:13: +4:23
          discriminant(_5) = 0;            // scope 2 at $DIR/recursive.rs:+4:13: +4:23
          StorageDead(_6);                 // scope 2 at $DIR/recursive.rs:+4:22: +4:23
          StorageDead(_7);                 // scope 2 at $DIR/recursive.rs:+4:23: +4:24
          StorageLive(_8);                 // scope 3 at $DIR/recursive.rs:+5:9: +5:10
          _9 = discriminant(_5);           // scope 3 at $DIR/recursive.rs:+5:19: +5:20
          switchInt(move _9) -> [0_isize: bb2, otherwise: bb1]; // scope 3 at $DIR/recursive.rs:+5:13: +5:20
      }
  
      bb1: {
          StorageLive(_17);                // scope 3 at $DIR/recursive.rs:+13:14: +13:35
          _17 = exit(const 0_i32);         // scope 3 at $DIR/recursive.rs:+13:14: +13:35
                                           // mir::Constant
                                           // + span: $DIR/recursive.rs:22:14: 22:32
                                           // + literal: Const { ty: fn(i32) -> ! {exit}, val: Value(<ZST>) }
      }
  
      bb2: {
          StorageLive(_10);                // scope 3 at $DIR/recursive.rs:+6:16: +6:17
          _10 = ((_5 as Rec).0: &S<'_>);   // scope 3 at $DIR/recursive.rs:+6:16: +6:17
          _11 = discriminant((*_10));      // scope 5 at $DIR/recursive.rs:+6:28: +6:29
          switchInt(move _11) -> [0_isize: bb4, otherwise: bb3]; // scope 5 at $DIR/recursive.rs:+6:22: +6:29
      }
  
      bb3: {
          StorageLive(_16);                // scope 5 at $DIR/recursive.rs:+11:18: +11:39
          _16 = exit(const 0_i32);         // scope 5 at $DIR/recursive.rs:+11:18: +11:39
                                           // mir::Constant
                                           // + span: $DIR/recursive.rs:20:18: 20:36
                                           // + literal: Const { ty: fn(i32) -> ! {exit}, val: Value(<ZST>) }
      }
  
      bb4: {
          StorageLive(_12);                // scope 5 at $DIR/recursive.rs:+7:20: +7:21
          _12 = &(((*_10) as Rec).0: &S<'_>); // scope 5 at $DIR/recursive.rs:+7:20: +7:21
          _18 = deref_copy (*_12);         // scope 6 at $DIR/recursive.rs:+7:32: +7:33
          _13 = discriminant((*_18));      // scope 6 at $DIR/recursive.rs:+7:32: +7:33
          switchInt(move _13) -> [1_isize: bb6, otherwise: bb5]; // scope 6 at $DIR/recursive.rs:+7:26: +7:33
      }
  
      bb5: {
          StorageLive(_15);                // scope 6 at $DIR/recursive.rs:+9:22: +9:43
          _15 = exit(const 0_i32);         // scope 6 at $DIR/recursive.rs:+9:22: +9:43
                                           // mir::Constant
                                           // + span: $DIR/recursive.rs:18:22: 18:40
                                           // + literal: Const { ty: fn(i32) -> ! {exit}, val: Value(<ZST>) }
      }
  
      bb6: {
          StorageLive(_14);                // scope 6 at $DIR/recursive.rs:+8:24: +8:27
          _19 = deref_copy (*_12);         // scope 6 at $DIR/recursive.rs:+8:24: +8:27
          _14 = &(((*_19) as Num).0: u32); // scope 6 at $DIR/recursive.rs:+8:24: +8:27
          _8 = (*_14);                     // scope 7 at $DIR/recursive.rs:+8:32: +8:36
          StorageDead(_14);                // scope 6 at $DIR/recursive.rs:+8:35: +8:36
          StorageDead(_12);                // scope 5 at $DIR/recursive.rs:+10:13: +10:14
          StorageDead(_10);                // scope 3 at $DIR/recursive.rs:+12:9: +12:10
          _0 = const ();                   // scope 0 at $DIR/recursive.rs:+0:11: +15:2
          StorageDead(_8);                 // scope 3 at $DIR/recursive.rs:+15:1: +15:2
          StorageDead(_5);                 // scope 2 at $DIR/recursive.rs:+15:1: +15:2
          StorageDead(_2);                 // scope 1 at $DIR/recursive.rs:+15:1: +15:2
          StorageDead(_1);                 // scope 0 at $DIR/recursive.rs:+15:1: +15:2
          return;                          // scope 0 at $DIR/recursive.rs:+15:2: +15:2
      }
  }
  
