- // MIR for `main` before DataflowConstProp
+ // MIR for `main` after DataflowConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/static_ref.rs:+0:11: +0:11
      let _1: i32;                         // in scope 0 at $DIR/static_ref.rs:+3:9: +3:10
      let mut _3: &i32;                    // in scope 0 at $DIR/static_ref.rs:+5:9: +5:11
      let _4: &i32;                        // in scope 0 at $DIR/static_ref.rs:+5:9: +5:11
      let _5: &i32;                        // in scope 0 at $DIR/static_ref.rs:+5:10: +5:11
      scope 1 {
          debug x => _1;                   // in scope 1 at $DIR/static_ref.rs:+3:9: +3:10
          let mut _2: &i32;                // in scope 1 at $DIR/static_ref.rs:+4:9: +4:14
          scope 2 {
              debug r => _2;               // in scope 2 at $DIR/static_ref.rs:+4:9: +4:14
              let _6: i32;                 // in scope 2 at $DIR/static_ref.rs:+6:9: +6:10
              scope 3 {
                  debug y => _6;           // in scope 3 at $DIR/static_ref.rs:+6:9: +6:10
              }
          }
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/static_ref.rs:+3:9: +3:10
          _1 = const 0_i32;                // scope 0 at $DIR/static_ref.rs:+3:13: +3:14
          StorageLive(_2);                 // scope 1 at $DIR/static_ref.rs:+4:9: +4:14
          _2 = &_1;                        // scope 1 at $DIR/static_ref.rs:+4:17: +4:19
          StorageLive(_3);                 // scope 2 at $DIR/static_ref.rs:+5:9: +5:11
          StorageLive(_4);                 // scope 2 at $DIR/static_ref.rs:+5:9: +5:11
          StorageLive(_5);                 // scope 2 at $DIR/static_ref.rs:+5:10: +5:11
          _5 = const {alloc1: &i32};       // scope 2 at $DIR/static_ref.rs:+5:10: +5:11
                                           // mir::Constant
                                           // + span: $DIR/static_ref.rs:10:10: 10:11
                                           // + literal: Const { ty: &i32, val: Value(Scalar(alloc1)) }
          _4 = &(*_5);                     // scope 2 at $DIR/static_ref.rs:+5:9: +5:11
          _3 = &(*_4);                     // scope 2 at $DIR/static_ref.rs:+5:9: +5:11
          _2 = move _3;                    // scope 2 at $DIR/static_ref.rs:+5:5: +5:11
          StorageDead(_3);                 // scope 2 at $DIR/static_ref.rs:+5:10: +5:11
          StorageDead(_5);                 // scope 2 at $DIR/static_ref.rs:+5:11: +5:12
          StorageDead(_4);                 // scope 2 at $DIR/static_ref.rs:+5:11: +5:12
          StorageLive(_6);                 // scope 2 at $DIR/static_ref.rs:+6:9: +6:10
          _6 = (*_2);                      // scope 2 at $DIR/static_ref.rs:+6:13: +6:15
          _0 = const ();                   // scope 0 at $DIR/static_ref.rs:+0:11: +7:2
          StorageDead(_6);                 // scope 2 at $DIR/static_ref.rs:+7:1: +7:2
          StorageDead(_2);                 // scope 1 at $DIR/static_ref.rs:+7:1: +7:2
          StorageDead(_1);                 // scope 0 at $DIR/static_ref.rs:+7:1: +7:2
          return;                          // scope 0 at $DIR/static_ref.rs:+7:2: +7:2
      }
  }
  
  alloc1 (static: P, size: 4, align: 4) {
      05 00 00 00                                     │ ....
  }
  
