- // MIR for `test` before CopyPropagation
+ // MIR for `test` after CopyPropagation
  
  fn test(_1: u32) -> u32 {
      debug x => _1;                       // in scope 0 at $DIR/copy_propagation.rs:4:9: 4:10
      let mut _0: u32;                     // return place in scope 0 at $DIR/copy_propagation.rs:4:20: 4:23
      let _2: u32;                         // in scope 0 at $DIR/copy_propagation.rs:5:9: 5:10
      scope 1 {
          debug y => _0;                   // in scope 1 at $DIR/copy_propagation.rs:5:9: 5:10
      }
  
      bb0: {
          nop;                             // scope 0 at $DIR/copy_propagation.rs:5:9: 5:10
          _0 = _1;                         // scope 0 at $DIR/copy_propagation.rs:5:13: 5:14
          nop;                             // scope 1 at $DIR/copy_propagation.rs:6:5: 6:6
          nop;                             // scope 0 at $DIR/copy_propagation.rs:7:1: 7:2
          return;                          // scope 0 at $DIR/copy_propagation.rs:7:2: 7:2
      }
  }
  
