- // MIR for `id` before CopyPropagation
+ // MIR for `id` after CopyPropagation
  
  fn id(_1: T) -> T {
      debug a => _1;                       // in scope 0 at $DIR/copy_propagation.rs:9:20: 9:25
      let mut _0: T;                       // return place in scope 0 at $DIR/copy_propagation.rs:9:33: 9:34
      let mut _2: T;                       // in scope 0 at $DIR/copy_propagation.rs:11:9: 11:10
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/copy_propagation.rs:11:9: 11:10
          _2 = _1;                         // scope 0 at $DIR/copy_propagation.rs:11:9: 11:10
-         _1 = move _2;                    // scope 0 at $DIR/copy_propagation.rs:11:5: 11:10
+         _1 = _2;                         // scope 0 at $DIR/copy_propagation.rs:11:5: 11:10
          StorageDead(_2);                 // scope 0 at $DIR/copy_propagation.rs:11:9: 11:10
          _0 = _1;                         // scope 0 at $DIR/copy_propagation.rs:12:5: 12:6
          return;                          // scope 0 at $DIR/copy_propagation.rs:13:2: 13:2
      }
  }
  
