- // MIR for `arg_src` before CopyPropagation
+ // MIR for `arg_src` after CopyPropagation
  
  fn arg_src(_1: i32) -> i32 {
      debug x => _1;                       // in scope 0 at $DIR/copy_propagation_arg.rs:29:12: 29:17
      let mut _0: i32;                     // return place in scope 0 at $DIR/copy_propagation_arg.rs:29:27: 29:30
      let _2: i32;                         // in scope 0 at $DIR/copy_propagation_arg.rs:30:9: 30:10
      scope 1 {
          debug y => _0;                   // in scope 1 at $DIR/copy_propagation_arg.rs:30:9: 30:10
      }
  
      bb0: {
          nop;                             // scope 0 at $DIR/copy_propagation_arg.rs:30:9: 30:10
          _0 = _1;                         // scope 0 at $DIR/copy_propagation_arg.rs:30:13: 30:14
          _1 = const 123_i32;              // scope 1 at $DIR/copy_propagation_arg.rs:31:5: 31:12
          nop;                             // scope 1 at $DIR/copy_propagation_arg.rs:32:5: 32:6
          nop;                             // scope 0 at $DIR/copy_propagation_arg.rs:33:1: 33:2
          return;                          // scope 0 at $DIR/copy_propagation_arg.rs:33:2: 33:2
      }
  }
  
