- // MIR for `find_reads` before SimpleLocalDse
+ // MIR for `find_reads` after SimpleLocalDse
  
  fn find_reads() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/dead_store_elimination.rs:66:21: 66:21
      let mut _1: i32;                     // in scope 0 at $DIR/dead_store_elimination.rs:67:9: 67:14
      let mut _4: i32;                     // in scope 0 at $DIR/dead_store_elimination.rs:69:13: 69:14
      let mut _5: i32;                     // in scope 0 at $DIR/dead_store_elimination.rs:69:17: 69:18
      let _6: ();                          // in scope 0 at $DIR/dead_store_elimination.rs:70:5: 70:12
      let mut _7: i32;                     // in scope 0 at $DIR/dead_store_elimination.rs:70:10: 70:11
      let _10: ();                         // in scope 0 at $DIR/dead_store_elimination.rs:74:5: 74:12
      let mut _11: &i32;                   // in scope 0 at $DIR/dead_store_elimination.rs:74:10: 74:11
      let mut _14: i32;                    // in scope 0 at $DIR/dead_store_elimination.rs:77:18: 77:19
      let _15: ();                         // in scope 0 at $DIR/dead_store_elimination.rs:78:5: 78:12
      let mut _16: std::option::Option<i32>; // in scope 0 at $DIR/dead_store_elimination.rs:78:10: 78:11
      let mut _18: isize;                  // in scope 0 at $DIR/dead_store_elimination.rs:81:12: 81:19
      scope 1 {
          debug a => _1;                   // in scope 1 at $DIR/dead_store_elimination.rs:67:9: 67:14
          let mut _2: i32;                 // in scope 1 at $DIR/dead_store_elimination.rs:68:9: 68:14
          scope 2 {
              debug b => _2;               // in scope 2 at $DIR/dead_store_elimination.rs:68:9: 68:14
              let _3: i32;                 // in scope 2 at $DIR/dead_store_elimination.rs:69:9: 69:10
              scope 3 {
                  debug c => _3;           // in scope 3 at $DIR/dead_store_elimination.rs:69:9: 69:10
                  let mut _8: i32;         // in scope 3 at $DIR/dead_store_elimination.rs:72:9: 72:14
                  scope 4 {
                      debug a => _8;       // in scope 4 at $DIR/dead_store_elimination.rs:72:9: 72:14
                      let _9: &i32;        // in scope 4 at $DIR/dead_store_elimination.rs:73:9: 73:10
                      scope 5 {
                          debug r => _9;   // in scope 5 at $DIR/dead_store_elimination.rs:73:9: 73:10
                          let mut _12: i32; // in scope 5 at $DIR/dead_store_elimination.rs:76:9: 76:14
                          scope 6 {
                              debug a => _12; // in scope 6 at $DIR/dead_store_elimination.rs:76:9: 76:14
                              let _13: std::option::Option<i32>; // in scope 6 at $DIR/dead_store_elimination.rs:77:9: 77:10
                              scope 7 {
                                  debug e => _13; // in scope 7 at $DIR/dead_store_elimination.rs:77:9: 77:10
                                  let mut _17: std::option::Option<i32>; // in scope 7 at $DIR/dead_store_elimination.rs:80:9: 80:14
                                  scope 8 {
                                      debug a => _17; // in scope 8 at $DIR/dead_store_elimination.rs:80:9: 80:14
                                      let _19: i32; // in scope 8 at $DIR/dead_store_elimination.rs:81:17: 81:18
                                      scope 9 {
                                          debug x => _19; // in scope 9 at $DIR/dead_store_elimination.rs:81:17: 81:18
                                      }
                                  }
                              }
                          }
                      }
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/dead_store_elimination.rs:67:9: 67:14
          _1 = const 0_i32;                // scope 0 at $DIR/dead_store_elimination.rs:67:17: 67:18
          StorageLive(_2);                 // scope 1 at $DIR/dead_store_elimination.rs:68:9: 68:14
          _2 = const 1_i32;                // scope 1 at $DIR/dead_store_elimination.rs:68:17: 68:18
          StorageLive(_3);                 // scope 2 at $DIR/dead_store_elimination.rs:69:9: 69:10
          StorageLive(_4);                 // scope 2 at $DIR/dead_store_elimination.rs:69:13: 69:14
-         _4 = const 0_i32;                // scope 2 at $DIR/dead_store_elimination.rs:69:13: 69:14
+         nop;                             // scope 2 at $DIR/dead_store_elimination.rs:69:13: 69:14
          StorageLive(_5);                 // scope 2 at $DIR/dead_store_elimination.rs:69:17: 69:18
-         _5 = const 1_i32;                // scope 2 at $DIR/dead_store_elimination.rs:69:17: 69:18
+         nop;                             // scope 2 at $DIR/dead_store_elimination.rs:69:17: 69:18
          _3 = const 1_i32;                // scope 2 at $DIR/dead_store_elimination.rs:69:13: 69:18
          StorageDead(_5);                 // scope 2 at $DIR/dead_store_elimination.rs:69:17: 69:18
          StorageDead(_4);                 // scope 2 at $DIR/dead_store_elimination.rs:69:17: 69:18
          StorageLive(_6);                 // scope 3 at $DIR/dead_store_elimination.rs:70:5: 70:12
          StorageLive(_7);                 // scope 3 at $DIR/dead_store_elimination.rs:70:10: 70:11
          _7 = const 1_i32;                // scope 3 at $DIR/dead_store_elimination.rs:70:10: 70:11
          _6 = read::<i32>(const 1_i32) -> bb1; // scope 3 at $DIR/dead_store_elimination.rs:70:5: 70:12
                                           // mir::Constant
                                           // + span: $DIR/dead_store_elimination.rs:70:5: 70:9
                                           // + literal: Const { ty: fn(i32) {read::<i32>}, val: Value(Scalar(<ZST>)) }
      }
  
      bb1: {
          StorageDead(_7);                 // scope 3 at $DIR/dead_store_elimination.rs:70:11: 70:12
          StorageDead(_6);                 // scope 3 at $DIR/dead_store_elimination.rs:70:12: 70:13
          StorageLive(_8);                 // scope 3 at $DIR/dead_store_elimination.rs:72:9: 72:14
          _8 = const 10_i32;               // scope 3 at $DIR/dead_store_elimination.rs:72:17: 72:19
          StorageLive(_9);                 // scope 4 at $DIR/dead_store_elimination.rs:73:9: 73:10
          _9 = &_8;                        // scope 4 at $DIR/dead_store_elimination.rs:73:13: 73:15
          StorageLive(_10);                // scope 5 at $DIR/dead_store_elimination.rs:74:5: 74:12
          StorageLive(_11);                // scope 5 at $DIR/dead_store_elimination.rs:74:10: 74:11
          _11 = _9;                        // scope 5 at $DIR/dead_store_elimination.rs:74:10: 74:11
          _10 = read::<&i32>(move _11) -> bb2; // scope 5 at $DIR/dead_store_elimination.rs:74:5: 74:12
                                           // mir::Constant
                                           // + span: $DIR/dead_store_elimination.rs:74:5: 74:9
                                           // + literal: Const { ty: fn(&i32) {read::<&i32>}, val: Value(Scalar(<ZST>)) }
      }
  
      bb2: {
          StorageDead(_11);                // scope 5 at $DIR/dead_store_elimination.rs:74:11: 74:12
          StorageDead(_10);                // scope 5 at $DIR/dead_store_elimination.rs:74:12: 74:13
          StorageLive(_12);                // scope 5 at $DIR/dead_store_elimination.rs:76:9: 76:14
          _12 = const 20_i32;              // scope 5 at $DIR/dead_store_elimination.rs:76:17: 76:19
          StorageLive(_13);                // scope 6 at $DIR/dead_store_elimination.rs:77:9: 77:10
          StorageLive(_14);                // scope 6 at $DIR/dead_store_elimination.rs:77:18: 77:19
-         _14 = const 20_i32;              // scope 6 at $DIR/dead_store_elimination.rs:77:18: 77:19
+         nop;                             // scope 6 at $DIR/dead_store_elimination.rs:77:18: 77:19
          ((_13 as Some).0: i32) = const 20_i32; // scope 6 at $DIR/dead_store_elimination.rs:77:13: 77:20
          discriminant(_13) = 1;           // scope 6 at $DIR/dead_store_elimination.rs:77:13: 77:20
          StorageDead(_14);                // scope 6 at $DIR/dead_store_elimination.rs:77:19: 77:20
          StorageLive(_15);                // scope 7 at $DIR/dead_store_elimination.rs:78:5: 78:12
          StorageLive(_16);                // scope 7 at $DIR/dead_store_elimination.rs:78:10: 78:11
          _16 = _13;                       // scope 7 at $DIR/dead_store_elimination.rs:78:10: 78:11
          _15 = read::<Option<i32>>(move _16) -> bb3; // scope 7 at $DIR/dead_store_elimination.rs:78:5: 78:12
                                           // mir::Constant
                                           // + span: $DIR/dead_store_elimination.rs:78:5: 78:9
                                           // + literal: Const { ty: fn(std::option::Option<i32>) {read::<std::option::Option<i32>>}, val: Value(Scalar(<ZST>)) }
      }
  
      bb3: {
          StorageDead(_16);                // scope 7 at $DIR/dead_store_elimination.rs:78:11: 78:12
          StorageDead(_15);                // scope 7 at $DIR/dead_store_elimination.rs:78:12: 78:13
          StorageLive(_17);                // scope 7 at $DIR/dead_store_elimination.rs:80:9: 80:14
          ((_17 as Some).0: i32) = const 30_i32; // scope 7 at $DIR/dead_store_elimination.rs:80:17: 80:25
          discriminant(_17) = 1;           // scope 7 at $DIR/dead_store_elimination.rs:80:17: 80:25
          _18 = const 1_isize;             // scope 8 at $DIR/dead_store_elimination.rs:81:12: 81:19
          goto -> bb4;                     // scope 8 at $DIR/dead_store_elimination.rs:81:12: 81:19
      }
  
      bb4: {
          StorageLive(_19);                // scope 8 at $DIR/dead_store_elimination.rs:81:17: 81:18
-         _19 = ((_17 as Some).0: i32);    // scope 8 at $DIR/dead_store_elimination.rs:81:17: 81:18
+         nop;                             // scope 8 at $DIR/dead_store_elimination.rs:81:17: 81:18
          nop;                             // scope 8 at $DIR/dead_store_elimination.rs:81:24: 82:6
          StorageDead(_19);                // scope 8 at $DIR/dead_store_elimination.rs:82:5: 82:6
          goto -> bb6;                     // scope 8 at $DIR/dead_store_elimination.rs:81:5: 83:6
      }
  
      bb5: {
          nop;                             // scope 8 at $DIR/dead_store_elimination.rs:82:12: 83:6
          goto -> bb6;                     // scope 8 at $DIR/dead_store_elimination.rs:81:5: 83:6
      }
  
      bb6: {
          StorageDead(_17);                // scope 7 at $DIR/dead_store_elimination.rs:84:1: 84:2
          StorageDead(_13);                // scope 6 at $DIR/dead_store_elimination.rs:84:1: 84:2
          StorageDead(_12);                // scope 5 at $DIR/dead_store_elimination.rs:84:1: 84:2
          StorageDead(_9);                 // scope 4 at $DIR/dead_store_elimination.rs:84:1: 84:2
          StorageDead(_8);                 // scope 3 at $DIR/dead_store_elimination.rs:84:1: 84:2
          StorageDead(_3);                 // scope 2 at $DIR/dead_store_elimination.rs:84:1: 84:2
          StorageDead(_2);                 // scope 1 at $DIR/dead_store_elimination.rs:84:1: 84:2
          StorageDead(_1);                 // scope 0 at $DIR/dead_store_elimination.rs:84:1: 84:2
          return;                          // scope 0 at $DIR/dead_store_elimination.rs:84:2: 84:2
      }
  }
  
