- // MIR for `main` before Derefer
+ // MIR for `main` after Derefer
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/derefer_test.rs:2:11: 2:11
      let mut _1: (i32, i32);              // in scope 0 at $DIR/derefer_test.rs:3:9: 3:14
      let mut _3: &mut (i32, i32);         // in scope 0 at $DIR/derefer_test.rs:4:22: 4:28
+     let mut _6: &mut (i32, i32);         // in scope 0 at $DIR/derefer_test.rs:4:9: 4:14
+     let mut _7: &mut (i32, i32);         // in scope 0 at $DIR/derefer_test.rs:4:9: 4:14
      scope 1 {
          debug a => _1;                   // in scope 1 at $DIR/derefer_test.rs:3:9: 3:14
          let mut _2: (i32, &mut (i32, i32)); // in scope 1 at $DIR/derefer_test.rs:4:9: 4:14
          scope 2 {
              debug b => _2;               // in scope 2 at $DIR/derefer_test.rs:4:9: 4:14
              let _4: &mut i32;            // in scope 2 at $DIR/derefer_test.rs:5:9: 5:10
              scope 3 {
                  debug x => _4;           // in scope 3 at $DIR/derefer_test.rs:5:9: 5:10
                  let _5: &mut i32;        // in scope 3 at $DIR/derefer_test.rs:6:9: 6:10
                  scope 4 {
                      debug y => _5;       // in scope 4 at $DIR/derefer_test.rs:6:9: 6:10
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/derefer_test.rs:3:9: 3:14
          Deinit(_1);                      // scope 0 at $DIR/derefer_test.rs:3:17: 3:24
          (_1.0: i32) = const 42_i32;      // scope 0 at $DIR/derefer_test.rs:3:17: 3:24
          (_1.1: i32) = const 43_i32;      // scope 0 at $DIR/derefer_test.rs:3:17: 3:24
          StorageLive(_2);                 // scope 1 at $DIR/derefer_test.rs:4:9: 4:14
          StorageLive(_3);                 // scope 1 at $DIR/derefer_test.rs:4:22: 4:28
          _3 = &mut _1;                    // scope 1 at $DIR/derefer_test.rs:4:22: 4:28
          Deinit(_2);                      // scope 1 at $DIR/derefer_test.rs:4:17: 4:29
          (_2.0: i32) = const 99_i32;      // scope 1 at $DIR/derefer_test.rs:4:17: 4:29
          (_2.1: &mut (i32, i32)) = move _3; // scope 1 at $DIR/derefer_test.rs:4:17: 4:29
          StorageDead(_3);                 // scope 1 at $DIR/derefer_test.rs:4:28: 4:29
          StorageLive(_4);                 // scope 2 at $DIR/derefer_test.rs:5:9: 5:10
-         _4 = &mut ((*(_2.1: &mut (i32, i32))).0: i32); // scope 2 at $DIR/derefer_test.rs:5:13: 5:26
+         StorageLive(_6);                 // scope 2 at $DIR/derefer_test.rs:5:13: 5:26
+         _6 = move (_2.1: &mut (i32, i32)); // scope 2 at $DIR/derefer_test.rs:5:13: 5:26
+         _4 = &mut ((*_6).0: i32);        // scope 2 at $DIR/derefer_test.rs:5:13: 5:26
+         StorageDead(_6);                 // scope 3 at $DIR/derefer_test.rs:6:9: 6:10
          StorageLive(_5);                 // scope 3 at $DIR/derefer_test.rs:6:9: 6:10
-         _5 = &mut ((*(_2.1: &mut (i32, i32))).1: i32); // scope 3 at $DIR/derefer_test.rs:6:13: 6:26
+         StorageLive(_7);                 // scope 3 at $DIR/derefer_test.rs:6:13: 6:26
+         _7 = move (_2.1: &mut (i32, i32)); // scope 3 at $DIR/derefer_test.rs:6:13: 6:26
+         _5 = &mut ((*_7).1: i32);        // scope 3 at $DIR/derefer_test.rs:6:13: 6:26
+         StorageDead(_7);                 // scope 0 at $DIR/derefer_test.rs:2:11: 7:2
          _0 = const ();                   // scope 0 at $DIR/derefer_test.rs:2:11: 7:2
          StorageDead(_5);                 // scope 3 at $DIR/derefer_test.rs:7:1: 7:2
          StorageDead(_4);                 // scope 2 at $DIR/derefer_test.rs:7:1: 7:2
          StorageDead(_2);                 // scope 1 at $DIR/derefer_test.rs:7:1: 7:2
          StorageDead(_1);                 // scope 0 at $DIR/derefer_test.rs:7:1: 7:2
          return;                          // scope 0 at $DIR/derefer_test.rs:7:2: 7:2
+     }
+ 
+     bb1 (cleanup): {
+         resume;                          // scope 0 at $DIR/derefer_test.rs:2:1: 7:2
      }
  }
  
