- // MIR for `array_len` before InstCombine
+ // MIR for `array_len` after InstCombine
  
  fn array_len(_1: &[u8; N]) -> usize {
      debug arr => _1;                     // in scope 0 at $DIR/lower_array_len.rs:+0:34: +0:37
      let mut _0: usize;                   // return place in scope 0 at $DIR/lower_array_len.rs:+0:52: +0:57
      let mut _2: &[u8];                   // in scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
      let mut _3: &[u8; N];                // in scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
      let mut _4: &[u8; N];                // in scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
          StorageLive(_3);                 // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
-         _3 = &(*_1);                     // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
+         _3 = _1;                         // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
          StorageLive(_4);                 // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
          _4 = _3;                         // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
          _2 = move _3 as &[u8] (Pointer(Unsize)); // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
          StorageDead(_3);                 // scope 0 at $DIR/lower_array_len.rs:+1:7: +1:8
-         _0 = Len((*_4));                 // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
+         _0 = const N;                    // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
          StorageDead(_4);                 // scope 0 at $DIR/lower_array_len.rs:+1:5: +1:14
          StorageDead(_2);                 // scope 0 at $DIR/lower_array_len.rs:+1:13: +1:14
          return;                          // scope 0 at $DIR/lower_array_len.rs:+2:2: +2:2
      }
  }
  
