- // MIR for `id_result` before MatchIdentitySimplification
+ // MIR for `id_result` after MatchIdentitySimplification
  
  fn id_result(_1: std::result::Result<i32, u32>) -> std::result::Result<i32, u32> {
      debug a => _1;                       // in scope 0 at $DIR/match_identity.rs:8:18: 8:19
      let mut _0: std::result::Result<i32, u32>; // return place in scope 0 at $DIR/match_identity.rs:8:38: 8:50
      let mut _2: isize;                   // in scope 0 at $DIR/match_identity.rs:10:9: 10:14
      scope 1 {
          debug x => ((_0 as Ok).0: i32);  // in scope 1 at $DIR/match_identity.rs:10:12: 10:13
      }
      scope 2 {
          debug y => ((_0 as Err).0: u32); // in scope 2 at $DIR/match_identity.rs:11:13: 11:14
      }
  
      bb0: {
          _2 = discriminant(_1);           // scope 0 at $DIR/match_identity.rs:10:9: 10:14
          switchInt(move _2) -> [0_isize: bb2, otherwise: bb1]; // scope 0 at $DIR/match_identity.rs:10:9: 10:14
      }
  
      bb1: {
          ((_0 as Err).0: u32) = ((_1 as Err).0: u32); // scope 0 at $DIR/match_identity.rs:11:13: 11:14
          discriminant(_0) = 1;            // scope 2 at $DIR/match_identity.rs:11:19: 11:25
          return;                          // scope 0 at $DIR/match_identity.rs:9:5: 12:6
      }
  
      bb2: {
          ((_0 as Ok).0: i32) = ((_1 as Ok).0: i32); // scope 0 at $DIR/match_identity.rs:10:12: 10:13
          discriminant(_0) = 0;            // scope 1 at $DIR/match_identity.rs:10:18: 10:23
          return;                          // scope 0 at $DIR/match_identity.rs:9:5: 12:6
      }
  }
  
