- // MIR for `foo` before MatchBranchSimplification
+ // MIR for `foo` after MatchBranchSimplification
  
  fn foo(_1: Option<()>) -> () {
      debug bar => _1;                     // in scope 0 at $DIR/matches_reduce_branches.rs:7:8: 7:11
      let mut _0: ();                      // return place in scope 0 at $DIR/matches_reduce_branches.rs:7:25: 7:25
      let mut _2: isize;                   // in scope 0 at $DIR/matches_reduce_branches.rs:8:22: 8:26
+     let mut _3: isize;                   // in scope 0 at $SRC_DIR/core/src/macros/mod.rs:LL:COL
      scope 1 {
      }
  
      bb0: {
          _2 = discriminant(_1);           // scope 1 at $DIR/matches_reduce_branches.rs:8:17: 8:20
-         switchInt(move _2) -> [0_isize: bb2, otherwise: bb1]; // scope 1 at $SRC_DIR/core/src/macros/mod.rs:LL:COL
-     }
- 
-     bb1: {
-         goto -> bb3;                     // scope 1 at $SRC_DIR/core/src/macros/mod.rs:LL:COL
-     }
- 
-     bb2: {
-         goto -> bb3;                     // scope 1 at $SRC_DIR/core/src/macros/mod.rs:LL:COL
-     }
- 
-     bb3: {
+         StorageLive(_3);                 // scope 1 at $SRC_DIR/core/src/macros/mod.rs:LL:COL
+         _3 = move _2;                    // scope 1 at $SRC_DIR/core/src/macros/mod.rs:LL:COL
+         StorageDead(_3);                 // scope 1 at $SRC_DIR/core/src/macros/mod.rs:LL:COL
          return;                          // scope 0 at $DIR/matches_reduce_branches.rs:11:2: 11:2
      }
  }
  
