- // MIR for `t1` before SimplifyLocals
+ // MIR for `t1` after SimplifyLocals
  
  fn t1() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/simplify_locals.rs:+0:9: +0:9
-     let _1: u32;                         // in scope 0 at $DIR/simplify_locals.rs:+2:14: +2:15
-     let mut _2: *mut u32;                // in scope 0 at $DIR/simplify_locals.rs:+2:14: +2:15
      scope 1 {
      }
  
      bb0: {
-         StorageLive(_1);                 // scope 0 at $DIR/simplify_locals.rs:+2:5: +2:17
-         StorageLive(_2);                 // scope 1 at $DIR/simplify_locals.rs:+2:14: +2:15
-         _2 = &/*tls*/ mut X;             // scope 1 at $DIR/simplify_locals.rs:+2:14: +2:15
-         _1 = (*_2);                      // scope 1 at $DIR/simplify_locals.rs:+2:14: +2:15
-         StorageDead(_2);                 // scope 0 at $DIR/simplify_locals.rs:+2:17: +2:18
-         StorageDead(_1);                 // scope 0 at $DIR/simplify_locals.rs:+2:17: +2:18
          _0 = const ();                   // scope 0 at $DIR/simplify_locals.rs:+0:9: +3:2
          return;                          // scope 0 at $DIR/simplify_locals.rs:+3:2: +3:2
      }
  }
  
