- // MIR for `main` before SimplifyCfg-early-opt
+ // MIR for `main` after SimplifyCfg-early-opt
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/simplify_cfg.rs:7:11: 7:11
      let mut _1: ();                      // in scope 0 at $DIR/simplify_cfg.rs:7:1: 13:2
      let mut _2: bool;                    // in scope 0 at $DIR/simplify_cfg.rs:9:12: 9:17
      let mut _3: !;                       // in scope 0 at $DIR/simplify_cfg.rs:9:18: 11:10
      scope 1 {
      }
  
      bb0: {
          goto -> bb1;                     // scope 0 at $DIR/simplify_cfg.rs:8:5: 12:6
      }
  
      bb1: {
-         goto -> bb2;                     // scope 0 at $DIR/simplify_cfg.rs:8:5: 12:6
-     }
- 
-     bb2: {
          StorageLive(_2);                 // scope 1 at $DIR/simplify_cfg.rs:9:12: 9:17
-         _2 = bar() -> [return: bb3, unwind: bb6]; // scope 1 at $DIR/simplify_cfg.rs:9:12: 9:17
+         _2 = bar() -> [return: bb2, unwind: bb5]; // scope 1 at $DIR/simplify_cfg.rs:9:12: 9:17
                                           // mir::Constant
                                           // + span: $DIR/simplify_cfg.rs:9:12: 9:15
                                           // + literal: Const { ty: fn() -> bool {bar}, val: Value(Scalar(<ZST>)) }
      }
  
-     bb3: {
-         switchInt(move _2) -> [false: bb5, otherwise: bb4]; // scope 1 at $DIR/simplify_cfg.rs:9:12: 9:17
+     bb2: {
+         switchInt(move _2) -> [false: bb4, otherwise: bb3]; // scope 1 at $DIR/simplify_cfg.rs:9:12: 9:17
      }
  
-     bb4: {
+     bb3: {
          _0 = const ();                   // scope 1 at $DIR/simplify_cfg.rs:10:13: 10:18
          StorageDead(_2);                 // scope 0 at $DIR/simplify_cfg.rs:11:9: 11:10
          return;                          // scope 0 at $DIR/simplify_cfg.rs:13:2: 13:2
      }
  
-     bb5: {
+     bb4: {
          _1 = const ();                   // scope 0 at $DIR/simplify_cfg.rs:11:10: 11:10
          StorageDead(_2);                 // scope 0 at $DIR/simplify_cfg.rs:11:9: 11:10
          goto -> bb1;                     // scope 0 at $DIR/simplify_cfg.rs:8:5: 12:6
      }
  
-     bb6 (cleanup): {
+     bb5 (cleanup): {
          resume;                          // scope 0 at $DIR/simplify_cfg.rs:7:1: 13:2
      }
  }
  
