- // MIR for `id` before SimplifyArmIdentity
+ // MIR for `id` after SimplifyArmIdentity
  
  fn id(_1: Option<u8>) -> Option<u8> {
      debug o => _1;                       // in scope 0 at $DIR/simplify-arm.rs:+0:7: +0:8
      let mut _0: std::option::Option<u8>; // return place in scope 0 at $DIR/simplify-arm.rs:+0:25: +0:35
      let mut _2: isize;                   // in scope 0 at $DIR/simplify-arm.rs:+2:9: +2:16
      let _3: u8;                          // in scope 0 at $DIR/simplify-arm.rs:+2:14: +2:15
      let mut _4: u8;                      // in scope 0 at $DIR/simplify-arm.rs:+2:25: +2:26
      scope 1 {
          debug v => _3;                   // in scope 1 at $DIR/simplify-arm.rs:+2:14: +2:15
      }
  
      bb0: {
          _2 = discriminant(_1);           // scope 0 at $DIR/simplify-arm.rs:+1:11: +1:12
          switchInt(move _2) -> [0_isize: bb1, 1_isize: bb3, otherwise: bb2]; // scope 0 at $DIR/simplify-arm.rs:+1:5: +1:12
      }
  
      bb1: {
          Deinit(_0);                      // scope 0 at $DIR/simplify-arm.rs:+3:17: +3:21
          discriminant(_0) = 0;            // scope 0 at $DIR/simplify-arm.rs:+3:17: +3:21
          goto -> bb4;                     // scope 0 at $DIR/simplify-arm.rs:+3:17: +3:21
      }
  
      bb2: {
          unreachable;                     // scope 0 at $DIR/simplify-arm.rs:+1:11: +1:12
      }
  
      bb3: {
          StorageLive(_3);                 // scope 0 at $DIR/simplify-arm.rs:+2:14: +2:15
          _3 = ((_1 as Some).0: u8);       // scope 0 at $DIR/simplify-arm.rs:+2:14: +2:15
          StorageLive(_4);                 // scope 1 at $DIR/simplify-arm.rs:+2:25: +2:26
          _4 = _3;                         // scope 1 at $DIR/simplify-arm.rs:+2:25: +2:26
          Deinit(_0);                      // scope 1 at $DIR/simplify-arm.rs:+2:20: +2:27
          ((_0 as Some).0: u8) = move _4;  // scope 1 at $DIR/simplify-arm.rs:+2:20: +2:27
          discriminant(_0) = 1;            // scope 1 at $DIR/simplify-arm.rs:+2:20: +2:27
          StorageDead(_4);                 // scope 1 at $DIR/simplify-arm.rs:+2:26: +2:27
          StorageDead(_3);                 // scope 0 at $DIR/simplify-arm.rs:+2:26: +2:27
          goto -> bb4;                     // scope 0 at $DIR/simplify-arm.rs:+2:26: +2:27
      }
  
      bb4: {
          return;                          // scope 0 at $DIR/simplify-arm.rs:+5:2: +5:2
      }
  }
  
