- // MIR for `dropping` before ScalarReplacementOfAggregates
+ // MIR for `dropping` after ScalarReplacementOfAggregates
  
  fn dropping() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/sroa.rs:+0:19: +0:19
      let _1: Tag;                         // in scope 0 at $DIR/sroa.rs:+1:5: +1:32
      let mut _2: S;                       // in scope 0 at $DIR/sroa.rs:+1:5: +1:30
      let mut _3: Tag;                     // in scope 0 at $DIR/sroa.rs:+1:7: +1:13
      let mut _4: Tag;                     // in scope 0 at $DIR/sroa.rs:+1:15: +1:21
      let mut _5: Tag;                     // in scope 0 at $DIR/sroa.rs:+1:23: +1:29
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/sroa.rs:+1:5: +1:32
          StorageLive(_2);                 // scope 0 at $DIR/sroa.rs:+1:5: +1:30
          StorageLive(_3);                 // scope 0 at $DIR/sroa.rs:+1:7: +1:13
          Deinit(_3);                      // scope 0 at $DIR/sroa.rs:+1:7: +1:13
          (_3.0: usize) = const 0_usize;   // scope 0 at $DIR/sroa.rs:+1:7: +1:13
          StorageLive(_4);                 // scope 0 at $DIR/sroa.rs:+1:15: +1:21
          Deinit(_4);                      // scope 0 at $DIR/sroa.rs:+1:15: +1:21
          (_4.0: usize) = const 1_usize;   // scope 0 at $DIR/sroa.rs:+1:15: +1:21
          StorageLive(_5);                 // scope 0 at $DIR/sroa.rs:+1:23: +1:29
          Deinit(_5);                      // scope 0 at $DIR/sroa.rs:+1:23: +1:29
          (_5.0: usize) = const 2_usize;   // scope 0 at $DIR/sroa.rs:+1:23: +1:29
          Deinit(_2);                      // scope 0 at $DIR/sroa.rs:+1:5: +1:30
          (_2.0: Tag) = move _3;           // scope 0 at $DIR/sroa.rs:+1:5: +1:30
          (_2.1: Tag) = move _4;           // scope 0 at $DIR/sroa.rs:+1:5: +1:30
          (_2.2: Tag) = move _5;           // scope 0 at $DIR/sroa.rs:+1:5: +1:30
          StorageDead(_5);                 // scope 0 at $DIR/sroa.rs:+1:29: +1:30
          StorageDead(_4);                 // scope 0 at $DIR/sroa.rs:+1:29: +1:30
          StorageDead(_3);                 // scope 0 at $DIR/sroa.rs:+1:29: +1:30
          _1 = move (_2.1: Tag);           // scope 0 at $DIR/sroa.rs:+1:5: +1:32
          drop(_1) -> bb1;                 // scope 0 at $DIR/sroa.rs:+1:32: +1:33
      }
  
      bb1: {
          drop((_2.0: Tag)) -> bb3;        // scope 0 at $DIR/sroa.rs:+1:32: +1:33
      }
  
      bb2: {
          StorageDead(_2);                 // scope 0 at $DIR/sroa.rs:+1:32: +1:33
          StorageDead(_1);                 // scope 0 at $DIR/sroa.rs:+1:32: +1:33
          _0 = const ();                   // scope 0 at $DIR/sroa.rs:+0:19: +2:2
          return;                          // scope 0 at $DIR/sroa.rs:+2:2: +2:2
      }
  
      bb3: {
          drop((_2.2: Tag)) -> bb2;        // scope 0 at $DIR/sroa.rs:+1:32: +1:33
      }
  }
  
