- // MIR for `opt_different_bbs` before UnneededDeref
+ // MIR for `opt_different_bbs` after UnneededDeref
  
  fn opt_different_bbs(_1: bool) -> u64 {
      debug input => _1;                   // in scope 0 at $DIR/unneeded_deref.rs:70:22: 70:27
      let mut _0: u64;                     // return place in scope 0 at $DIR/unneeded_deref.rs:70:38: 70:41
      let _2: u64;                         // in scope 0 at $DIR/unneeded_deref.rs:71:9: 71:10
      let mut _4: i32;                     // in scope 0 at $DIR/unneeded_deref.rs:73:13: 73:38
      let mut _5: bool;                    // in scope 0 at $DIR/unneeded_deref.rs:73:16: 73:21
      scope 1 {
          debug x => _2;                   // in scope 1 at $DIR/unneeded_deref.rs:71:9: 71:10
          let _3: &u64;                    // in scope 1 at $DIR/unneeded_deref.rs:72:9: 72:10
          scope 2 {
              debug y => _3;               // in scope 2 at $DIR/unneeded_deref.rs:72:9: 72:10
              scope 3 {
                  let _6: u64;             // in scope 3 at $DIR/unneeded_deref.rs:74:9: 74:10
                  scope 4 {
                      debug z => _6;       // in scope 4 at $DIR/unneeded_deref.rs:74:9: 74:10
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/unneeded_deref.rs:71:9: 71:10
          _2 = const 5_u64;                // scope 0 at $DIR/unneeded_deref.rs:71:13: 71:14
          StorageLive(_3);                 // scope 1 at $DIR/unneeded_deref.rs:72:9: 72:10
          _3 = &_2;                        // scope 1 at $DIR/unneeded_deref.rs:72:13: 72:15
          StorageLive(_4);                 // scope 2 at $DIR/unneeded_deref.rs:73:13: 73:38
          StorageLive(_5);                 // scope 2 at $DIR/unneeded_deref.rs:73:16: 73:21
          _5 = _1;                         // scope 2 at $DIR/unneeded_deref.rs:73:16: 73:21
          switchInt(_5) -> [false: bb1, otherwise: bb2]; // scope 2 at $DIR/unneeded_deref.rs:73:13: 73:38
      }
  
      bb1: {
          _4 = const 3_i32;                // scope 2 at $DIR/unneeded_deref.rs:73:35: 73:36
          goto -> bb3;                     // scope 2 at $DIR/unneeded_deref.rs:73:13: 73:38
      }
  
      bb2: {
          _4 = const 2_i32;                // scope 2 at $DIR/unneeded_deref.rs:73:24: 73:25
          goto -> bb3;                     // scope 2 at $DIR/unneeded_deref.rs:73:13: 73:38
      }
  
      bb3: {
          StorageDead(_5);                 // scope 2 at $DIR/unneeded_deref.rs:73:38: 73:39
          StorageDead(_4);                 // scope 2 at $DIR/unneeded_deref.rs:73:38: 73:39
          StorageLive(_6);                 // scope 3 at $DIR/unneeded_deref.rs:74:9: 74:10
-         _6 = (*_3);                      // scope 3 at $DIR/unneeded_deref.rs:74:13: 74:15
+         _6 = _2;                         // scope 3 at $DIR/unneeded_deref.rs:74:13: 74:15
          _0 = _6;                         // scope 4 at $DIR/unneeded_deref.rs:75:5: 75:6
          StorageDead(_6);                 // scope 3 at $DIR/unneeded_deref.rs:76:1: 76:2
          StorageDead(_3);                 // scope 1 at $DIR/unneeded_deref.rs:76:1: 76:2
          StorageDead(_2);                 // scope 0 at $DIR/unneeded_deref.rs:76:1: 76:2
          return;                          // scope 0 at $DIR/unneeded_deref.rs:76:2: 76:2
      }
  }
  
