- // MIR for `opt_different_bbs2` before UnneededDeref
+ // MIR for `opt_different_bbs2` after UnneededDeref
  
  fn opt_different_bbs2(_1: bool) -> u64 {
      debug input => _1;                   // in scope 0 at $DIR/unneeded_deref.rs:79:23: 79:28
      let mut _0: u64;                     // return place in scope 0 at $DIR/unneeded_deref.rs:79:39: 79:42
      let _2: u64;                         // in scope 0 at $DIR/unneeded_deref.rs:80:9: 80:10
      let mut _5: bool;                    // in scope 0 at $DIR/unneeded_deref.rs:82:16: 82:21
      scope 1 {
          debug x => _2;                   // in scope 1 at $DIR/unneeded_deref.rs:80:9: 80:10
          let _3: &u64;                    // in scope 1 at $DIR/unneeded_deref.rs:81:9: 81:10
          scope 2 {
              debug y => _3;               // in scope 2 at $DIR/unneeded_deref.rs:81:9: 81:10
              let _4: u64;                 // in scope 2 at $DIR/unneeded_deref.rs:82:9: 82:10
              scope 3 {
                  debug z => _4;           // in scope 3 at $DIR/unneeded_deref.rs:82:9: 82:10
              }
          }
      }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/unneeded_deref.rs:80:9: 80:10
          _2 = const 5_u64;                // scope 0 at $DIR/unneeded_deref.rs:80:13: 80:14
          StorageLive(_3);                 // scope 1 at $DIR/unneeded_deref.rs:81:9: 81:10
          _3 = &_2;                        // scope 1 at $DIR/unneeded_deref.rs:81:13: 81:15
          StorageLive(_4);                 // scope 2 at $DIR/unneeded_deref.rs:82:9: 82:10
          StorageLive(_5);                 // scope 2 at $DIR/unneeded_deref.rs:82:16: 82:21
          _5 = _1;                         // scope 2 at $DIR/unneeded_deref.rs:82:16: 82:21
          switchInt(_5) -> [false: bb1, otherwise: bb2]; // scope 2 at $DIR/unneeded_deref.rs:82:13: 82:39
      }
  
      bb1: {
          _4 = const 3_u64;                // scope 2 at $DIR/unneeded_deref.rs:82:36: 82:37
          goto -> bb3;                     // scope 2 at $DIR/unneeded_deref.rs:82:13: 82:39
      }
  
      bb2: {
-         _4 = (*_3);                      // scope 2 at $DIR/unneeded_deref.rs:82:24: 82:26
+         _4 = _2;                         // scope 2 at $DIR/unneeded_deref.rs:82:24: 82:26
          goto -> bb3;                     // scope 2 at $DIR/unneeded_deref.rs:82:13: 82:39
      }
  
      bb3: {
          StorageDead(_5);                 // scope 2 at $DIR/unneeded_deref.rs:82:39: 82:40
          _0 = _4;                         // scope 3 at $DIR/unneeded_deref.rs:83:5: 83:6
          StorageDead(_4);                 // scope 2 at $DIR/unneeded_deref.rs:84:1: 84:2
          StorageDead(_3);                 // scope 1 at $DIR/unneeded_deref.rs:84:1: 84:2
          StorageDead(_2);                 // scope 0 at $DIR/unneeded_deref.rs:84:1: 84:2
          return;                          // scope 0 at $DIR/unneeded_deref.rs:84:2: 84:2
      }
  }
  
