- // MIR for `operand_opt` before UnneededDeref
+ // MIR for `operand_opt` after UnneededDeref
  
  fn operand_opt(_1: Option<T>) -> bool {
      debug input => _1;                   // in scope 0 at $DIR/unneeded_deref.rs:87:25: 87:30
      let mut _0: bool;                    // return place in scope 0 at $DIR/unneeded_deref.rs:87:46: 87:50
      let _2: bool;                        // in scope 0 at $DIR/unneeded_deref.rs:88:9: 88:10
      let mut _3: &std::option::Option<T>; // in scope 0 at $DIR/unneeded_deref.rs:88:13: 88:18
      let mut _5: &std::option::Option<T>; // in scope 0 at $DIR/unneeded_deref.rs:89:13: 89:18
      let mut _6: bool;                    // in scope 0 at $DIR/unneeded_deref.rs:90:5: 90:6
      let mut _7: bool;                    // in scope 0 at $DIR/unneeded_deref.rs:90:10: 90:11
      let mut _10: isize;                  // in scope 0 at $DIR/unneeded_deref.rs:88:13: 88:28
      let mut _11: isize;                  // in scope 0 at $DIR/unneeded_deref.rs:89:13: 89:28
      scope 1 {
          debug x => _2;                   // in scope 1 at $DIR/unneeded_deref.rs:88:9: 88:10
          let _4: bool;                    // in scope 1 at $DIR/unneeded_deref.rs:89:9: 89:10
          scope 2 {
              debug y => _4;               // in scope 2 at $DIR/unneeded_deref.rs:89:9: 89:10
          }
          scope 4 (inlined Option::<T>::is_some) { // at $DIR/unneeded_deref.rs:89:13: 89:28
              debug self => _5;            // in scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
              let mut _9: isize;           // in scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
          }
      }
      scope 3 (inlined Option::<T>::is_some) { // at $DIR/unneeded_deref.rs:88:13: 88:28
          debug self => _3;                // in scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
          let mut _8: isize;               // in scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
      }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/unneeded_deref.rs:88:9: 88:10
          StorageLive(_3);                 // scope 0 at $DIR/unneeded_deref.rs:88:13: 88:18
          _3 = &_1;                        // scope 0 at $DIR/unneeded_deref.rs:88:13: 88:18
-         _8 = discriminant((*_3));        // scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
+         _8 = discriminant(_1);           // scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
          StorageLive(_10);                // scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
          _10 = move _8;                   // scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
          _2 = Eq(_10, const 1_isize);     // scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
          StorageDead(_10);                // scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
          goto -> bb1;                     // scope 3 at $DIR/unneeded_deref.rs:88:13: 88:28
      }
  
      bb1: {
          StorageDead(_3);                 // scope 0 at $DIR/unneeded_deref.rs:88:27: 88:28
          StorageLive(_4);                 // scope 1 at $DIR/unneeded_deref.rs:89:9: 89:10
          StorageLive(_5);                 // scope 1 at $DIR/unneeded_deref.rs:89:13: 89:18
          _5 = &_1;                        // scope 1 at $DIR/unneeded_deref.rs:89:13: 89:18
-         _9 = discriminant((*_5));        // scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
+         _9 = discriminant(_1);           // scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
          StorageLive(_11);                // scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
          _11 = move _9;                   // scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
          _4 = Eq(_11, const 1_isize);     // scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
          StorageDead(_11);                // scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
          goto -> bb2;                     // scope 4 at $DIR/unneeded_deref.rs:89:13: 89:28
      }
  
      bb2: {
          StorageDead(_5);                 // scope 1 at $DIR/unneeded_deref.rs:89:27: 89:28
          StorageLive(_6);                 // scope 2 at $DIR/unneeded_deref.rs:90:5: 90:6
          _6 = _2;                         // scope 2 at $DIR/unneeded_deref.rs:90:5: 90:6
          StorageLive(_7);                 // scope 2 at $DIR/unneeded_deref.rs:90:10: 90:11
          _7 = _4;                         // scope 2 at $DIR/unneeded_deref.rs:90:10: 90:11
          _0 = Eq(move _6, move _7);       // scope 2 at $DIR/unneeded_deref.rs:90:5: 90:11
          StorageDead(_7);                 // scope 2 at $DIR/unneeded_deref.rs:90:10: 90:11
          StorageDead(_6);                 // scope 2 at $DIR/unneeded_deref.rs:90:10: 90:11
          StorageDead(_4);                 // scope 1 at $DIR/unneeded_deref.rs:91:1: 91:2
          StorageDead(_2);                 // scope 0 at $DIR/unneeded_deref.rs:91:1: 91:2
          return;                          // scope 0 at $DIR/unneeded_deref.rs:91:2: 91:2
      }
  }
  
