- // MIR for `dont_opt` before UnneededDeref
+ // MIR for `dont_opt` after UnneededDeref
  
  fn dont_opt() -> u64 {
      let mut _0: u64;                     // return place in scope 0 at $DIR/unneeded_deref_do_not_opt.rs:9:18: 9:21
      let _1: i32;                         // in scope 0 at $DIR/unneeded_deref_do_not_opt.rs:10:9: 10:10
      let mut _5: &i32;                    // in scope 0 at $DIR/unneeded_deref_do_not_opt.rs:14:10: 14:14
      scope 1 {
          debug y => _1;                   // in scope 1 at $DIR/unneeded_deref_do_not_opt.rs:10:9: 10:10
          let _2: &i32;                    // in scope 1 at $DIR/unneeded_deref_do_not_opt.rs:11:9: 11:13
          scope 2 {
              debug _ref => _2;            // in scope 2 at $DIR/unneeded_deref_do_not_opt.rs:11:9: 11:13
              let _3: i32;                 // in scope 2 at $DIR/unneeded_deref_do_not_opt.rs:12:9: 12:10
              scope 3 {
                  debug x => _3;           // in scope 3 at $DIR/unneeded_deref_do_not_opt.rs:12:9: 12:10
                  let mut _4: &i32;        // in scope 3 at $DIR/unneeded_deref_do_not_opt.rs:13:9: 13:15
                  scope 4 {
                      debug _1 => _4;      // in scope 4 at $DIR/unneeded_deref_do_not_opt.rs:13:9: 13:15
                      let _6: i32;         // in scope 4 at $DIR/unneeded_deref_do_not_opt.rs:15:9: 15:11
                      scope 5 {
                          debug _4 => _6;  // in scope 5 at $DIR/unneeded_deref_do_not_opt.rs:15:9: 15:11
                      }
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/unneeded_deref_do_not_opt.rs:10:9: 10:10
          _1 = const 5_i32;                // scope 0 at $DIR/unneeded_deref_do_not_opt.rs:10:13: 10:14
          StorageLive(_2);                 // scope 1 at $DIR/unneeded_deref_do_not_opt.rs:11:9: 11:13
          _2 = &_1;                        // scope 1 at $DIR/unneeded_deref_do_not_opt.rs:11:16: 11:18
          StorageLive(_3);                 // scope 2 at $DIR/unneeded_deref_do_not_opt.rs:12:9: 12:10
          _3 = const 5_i32;                // scope 2 at $DIR/unneeded_deref_do_not_opt.rs:12:13: 12:14
          StorageLive(_4);                 // scope 3 at $DIR/unneeded_deref_do_not_opt.rs:13:9: 13:15
          _4 = &_3;                        // scope 3 at $DIR/unneeded_deref_do_not_opt.rs:13:18: 13:20
          StorageLive(_5);                 // scope 4 at $DIR/unneeded_deref_do_not_opt.rs:14:10: 14:14
          _5 = _2;                         // scope 4 at $DIR/unneeded_deref_do_not_opt.rs:14:10: 14:14
          _4 = move _5;                    // scope 4 at $DIR/unneeded_deref_do_not_opt.rs:14:5: 14:14
          StorageDead(_5);                 // scope 4 at $DIR/unneeded_deref_do_not_opt.rs:14:13: 14:14
          StorageLive(_6);                 // scope 4 at $DIR/unneeded_deref_do_not_opt.rs:15:9: 15:11
          _6 = (*_4);                      // scope 4 at $DIR/unneeded_deref_do_not_opt.rs:15:14: 15:17
          _0 = const 0_u64;                // scope 5 at $DIR/unneeded_deref_do_not_opt.rs:16:5: 16:6
          StorageDead(_6);                 // scope 4 at $DIR/unneeded_deref_do_not_opt.rs:17:1: 17:2
          StorageDead(_4);                 // scope 3 at $DIR/unneeded_deref_do_not_opt.rs:17:1: 17:2
          StorageDead(_3);                 // scope 2 at $DIR/unneeded_deref_do_not_opt.rs:17:1: 17:2
          StorageDead(_2);                 // scope 1 at $DIR/unneeded_deref_do_not_opt.rs:17:1: 17:2
          StorageDead(_1);                 // scope 0 at $DIR/unneeded_deref_do_not_opt.rs:17:1: 17:2
          return;                          // scope 0 at $DIR/unneeded_deref_do_not_opt.rs:17:2: 17:2
      }
  }
  
