- // MIR for `elaborate_drops::{closure#0}` before StateTransform
+ // MIR for `elaborate_drops::{closure#0}` after StateTransform
  
- fn elaborate_drops::{closure#0}(_1: {async fn body of elaborate_drops()}, _2: std::future::ResumeTy) -> ()
- yields ()
-  {
-     debug _task_context => _2;
-     let mut _0: ();
+ fn elaborate_drops::{closure#0}(_1: Pin<&mut {async fn body of elaborate_drops()}>, _2: &mut Context<'_>) -> Poll<()> {
+     coroutine layout {
+         field _s0: ();
+         field _s1: SyncInt;
+         field _s2: AsyncInt;
+         field _s3: [AsyncInt; 2];
+         field _s4: AsyncStruct;
+         field _s5: SyncThenAsync;
+         field _s6: AsyncEnum;
+         field _s7: AsyncInt;
+         field _s8: AsyncReference<'_>;
+         field _s9: {closure@$DIR/async_drop.rs:78:25: 78:27};
+         field _s10: {async closure@$DIR/async_drop.rs:86:27: 86:35};
+         field _s11: impl Future<Output = ()>;
+         field _s12: impl Future<Output = ()>;
+         field _s13: impl Future<Output = ()>;
+         field _s14: impl Future<Output = ()>;
+         field _s15: impl Future<Output = ()>;
+         field _s16: impl Future<Output = ()>;
+         field _s17: impl Future<Output = ()>;
+         field _s18: impl Future<Output = ()>;
+         field _s19: impl Future<Output = ()>;
+         variant_fields = {
+             Unresumed(0): [],
+             Returned (1): [],
+             Panicked (2): [],
+             Suspend0 (3): [_s1, _s2, _s3, _s4, _s5, _s6, _s7, _s8, _s9, _s10, _s11],
+             Suspend1 (4): [_s0, _s1, _s2, _s3, _s4, _s5, _s6, _s7, _s8, _s9, _s10, _s11],
+             Suspend2 (5): [_s1, _s2, _s3, _s4, _s5, _s6, _s7, _s8, _s9, _s12],
+             Suspend3 (6): [_s0, _s1, _s2, _s3, _s4, _s5, _s6, _s7, _s8, _s9, _s12],
+             Suspend4 (7): [_s1, _s2, _s3, _s4, _s5, _s6, _s7, _s8, _s13],
+             Suspend5 (8): [_s0, _s1, _s2, _s3, _s4, _s5, _s6, _s7, _s8, _s13],
+             Suspend6 (9): [_s1, _s2, _s3, _s4, _s5, _s6, _s7, _s14],
+             Suspend7 (10): [_s0, _s1, _s2, _s3, _s4, _s5, _s6, _s7, _s14],
+             Suspend8 (11): [_s1, _s2, _s3, _s4, _s5, _s6, _s15],
+             Suspend9 (12): [_s0, _s1, _s2, _s3, _s4, _s5, _s6, _s15],
+             Suspend10(13): [_s1, _s2, _s3, _s4, _s5, _s16],
+             Suspend11(14): [_s0, _s1, _s2, _s3, _s4, _s5, _s16],
+             Suspend12(15): [_s1, _s2, _s3, _s4, _s17],
+             Suspend13(16): [_s0, _s1, _s2, _s3, _s4, _s17],
+             Suspend14(17): [_s1, _s2, _s3, _s18],
+             Suspend15(18): [_s0, _s1, _s2, _s3, _s18],
+             Suspend16(19): [_s1, _s2, _s19],
+             Suspend17(20): [_s0, _s1, _s2, _s19],
+         }
+         storage_conflicts = BitMatrix(20x20) {(_s0, _s0), (_s0, _s1), (_s0, _s2), (_s0, _s3), (_s0, _s4), (_s0, _s5), (_s0, _s6), (_s0, _s7), (_s0, _s8), (_s0, _s9), (_s0, _s10), (_s0, _s11), (_s0, _s12), (_s0, _s13), (_s0, _s14), (_s0, _s15), (_s0, _s16), (_s0, _s17), (_s0, _s18), (_s0, _s19), (_s1, _s0), (_s1, _s1), (_s1, _s2), (_s1, _s3), (_s1, _s4), (_s1, _s5), (_s1, _s6), (_s1, _s7), (_s1, _s8), (_s1, _s9), (_s1, _s10), (_s1, _s11), (_s1, _s12), (_s1, _s13), (_s1, _s14), (_s1, _s15), (_s1, _s16), (_s1, _s17), (_s1, _s18), (_s1, _s19), (_s2, _s0), (_s2, _s1), (_s2, _s2), (_s2, _s3), (_s2, _s4), (_s2, _s5), (_s2, _s6), (_s2, _s7), (_s2, _s8), (_s2, _s9), (_s2, _s10), (_s2, _s11), (_s2, _s12), (_s2, _s13), (_s2, _s14), (_s2, _s15), (_s2, _s16), (_s2, _s17), (_s2, _s18), (_s2, _s19), (_s3, _s0), (_s3, _s1), (_s3, _s2), (_s3, _s3), (_s3, _s4), (_s3, _s5), (_s3, _s6), (_s3, _s7), (_s3, _s8), (_s3, _s9), (_s3, _s10), (_s3, _s11), (_s3, _s12), (_s3, _s13), (_s3, _s14), (_s3, _s15), (_s3, _s16), (_s3, _s17), (_s3, _s18), (_s4, _s0), (_s4, _s1), (_s4, _s2), (_s4, _s3), (_s4, _s4), (_s4, _s5), (_s4, _s6), (_s4, _s7), (_s4, _s8), (_s4, _s9), (_s4, _s10), (_s4, _s11), (_s4, _s12), (_s4, _s13), (_s4, _s14), (_s4, _s15), (_s4, _s16), (_s4, _s17), (_s5, _s0), (_s5, _s1), (_s5, _s2), (_s5, _s3), (_s5, _s4), (_s5, _s5), (_s5, _s6), (_s5, _s7), (_s5, _s8), (_s5, _s9), (_s5, _s10), (_s5, _s11), (_s5, _s12), (_s5, _s13), (_s5, _s14), (_s5, _s15), (_s5, _s16), (_s6, _s0), (_s6, _s1), (_s6, _s2), (_s6, _s3), (_s6, _s4), (_s6, _s5), (_s6, _s6), (_s6, _s7), (_s6, _s8), (_s6, _s9), (_s6, _s10), (_s6, _s11), (_s6, _s12), (_s6, _s13), (_s6, _s14), (_s6, _s15), (_s7, _s0), (_s7, _s1), (_s7, _s2), (_s7, _s3), (_s7, _s4), (_s7, _s5), (_s7, _s6), (_s7, _s7), (_s7, _s8), (_s7, _s9), (_s7, _s10), (_s7, _s11), (_s7, _s12), (_s7, _s13), (_s7, _s14), (_s8, _s0), (_s8, _s1), (_s8, _s2), (_s8, _s3), (_s8, _s4), (_s8, _s5), (_s8, _s6), (_s8, _s7), (_s8, _s8), (_s8, _s9), (_s8, _s10), (_s8, _s11), (_s8, _s12), (_s8, _s13), (_s9, _s0), (_s9, _s1), (_s9, _s2), (_s9, _s3), (_s9, _s4), (_s9, _s5), (_s9, _s6), (_s9, _s7), (_s9, _s8), (_s9, _s9), (_s9, _s10), (_s9, _s11), (_s9, _s12), (_s10, _s0), (_s10, _s1), (_s10, _s2), (_s10, _s3), (_s10, _s4), (_s10, _s5), (_s10, _s6), (_s10, _s7), (_s10, _s8), (_s10, _s9), (_s10, _s10), (_s10, _s11), (_s11, _s0), (_s11, _s1), (_s11, _s2), (_s11, _s3), (_s11, _s4), (_s11, _s5), (_s11, _s6), (_s11, _s7), (_s11, _s8), (_s11, _s9), (_s11, _s10), (_s11, _s11), (_s12, _s0), (_s12, _s1), (_s12, _s2), (_s12, _s3), (_s12, _s4), (_s12, _s5), (_s12, _s6), (_s12, _s7), (_s12, _s8), (_s12, _s9), (_s12, _s12), (_s13, _s0), (_s13, _s1), (_s13, _s2), (_s13, _s3), (_s13, _s4), (_s13, _s5), (_s13, _s6), (_s13, _s7), (_s13, _s8), (_s13, _s13), (_s14, _s0), (_s14, _s1), (_s14, _s2), (_s14, _s3), (_s14, _s4), (_s14, _s5), (_s14, _s6), (_s14, _s7), (_s14, _s14), (_s15, _s0), (_s15, _s1), (_s15, _s2), (_s15, _s3), (_s15, _s4), (_s15, _s5), (_s15, _s6), (_s15, _s15), (_s16, _s0), (_s16, _s1), (_s16, _s2), (_s16, _s3), (_s16, _s4), (_s16, _s5), (_s16, _s16), (_s17, _s0), (_s17, _s1), (_s17, _s2), (_s17, _s3), (_s17, _s4), (_s17, _s17), (_s18, _s0), (_s18, _s1), (_s18, _s2), (_s18, _s3), (_s18, _s18), (_s19, _s0), (_s19, _s1), (_s19, _s2), (_s19, _s19)}
+     }
+     debug _task_context => _183;
+     coroutine debug sync_int => _s1;
+     let mut _0: std::task::Poll<()>;
      let _3: SyncInt;
      let mut _6: AsyncInt;
      let mut _7: AsyncInt;
      let mut _9: AsyncInt;
      let mut _10: AsyncInt;
      let mut _12: AsyncInt;
      let mut _13: SyncInt;
      let mut _14: AsyncInt;
      let mut _16: AsyncInt;
      let mut _18: AsyncInt;
      let mut _21: &AsyncInt;
      let _22: &AsyncInt;
      let mut _27: impl std::future::Future<Output = ()>;
      let mut _28: std::future::ResumeTy;
      let mut _29: std::task::Poll<()>;
      let mut _30: isize;
      let mut _31: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _32: &mut std::task::Context<'_>;
      let mut _33: std::future::ResumeTy;
      let mut _34: &mut impl std::future::Future<Output = ()>;
      let mut _35: std::future::ResumeTy;
      let mut _36: std::task::Poll<()>;
      let mut _37: isize;
      let mut _38: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _39: &mut std::task::Context<'_>;
      let mut _40: std::future::ResumeTy;
      let mut _41: &mut impl std::future::Future<Output = ()>;
      let mut _42: std::pin::Pin<&mut {async closure@$DIR/async_drop.rs:86:27: 86:35}>;
      let mut _43: &mut {async closure@$DIR/async_drop.rs:86:27: 86:35};
      let mut _44: impl std::future::Future<Output = ()>;
      let mut _45: std::future::ResumeTy;
      let mut _46: std::task::Poll<()>;
      let mut _47: isize;
      let mut _48: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _49: &mut std::task::Context<'_>;
      let mut _50: std::future::ResumeTy;
      let mut _51: &mut impl std::future::Future<Output = ()>;
      let mut _52: std::future::ResumeTy;
      let mut _53: std::task::Poll<()>;
      let mut _54: isize;
      let mut _55: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _56: &mut std::task::Context<'_>;
      let mut _57: std::future::ResumeTy;
      let mut _58: &mut impl std::future::Future<Output = ()>;
      let mut _59: std::pin::Pin<&mut {closure@$DIR/async_drop.rs:78:25: 78:27}>;
      let mut _60: &mut {closure@$DIR/async_drop.rs:78:25: 78:27};
      let mut _61: impl std::future::Future<Output = ()>;
      let mut _62: std::future::ResumeTy;
      let mut _63: std::task::Poll<()>;
      let mut _64: isize;
      let mut _65: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _66: &mut std::task::Context<'_>;
      let mut _67: std::future::ResumeTy;
      let mut _68: &mut impl std::future::Future<Output = ()>;
      let mut _69: std::future::ResumeTy;
      let mut _70: std::task::Poll<()>;
      let mut _71: isize;
      let mut _72: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _73: &mut std::task::Context<'_>;
      let mut _74: std::future::ResumeTy;
      let mut _75: &mut impl std::future::Future<Output = ()>;
      let mut _76: std::pin::Pin<&mut AsyncReference<'_>>;
      let mut _77: &mut AsyncReference<'_>;
      let mut _78: impl std::future::Future<Output = ()>;
      let mut _79: std::future::ResumeTy;
      let mut _80: std::task::Poll<()>;
      let mut _81: isize;
      let mut _82: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _83: &mut std::task::Context<'_>;
      let mut _84: std::future::ResumeTy;
      let mut _85: &mut impl std::future::Future<Output = ()>;
      let mut _86: std::future::ResumeTy;
      let mut _87: std::task::Poll<()>;
      let mut _88: isize;
      let mut _89: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _90: &mut std::task::Context<'_>;
      let mut _91: std::future::ResumeTy;
      let mut _92: &mut impl std::future::Future<Output = ()>;
      let mut _93: std::pin::Pin<&mut AsyncInt>;
      let mut _94: &mut AsyncInt;
      let mut _95: impl std::future::Future<Output = ()>;
      let mut _96: std::future::ResumeTy;
      let mut _97: std::task::Poll<()>;
      let mut _98: isize;
      let mut _99: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _100: &mut std::task::Context<'_>;
      let mut _101: std::future::ResumeTy;
      let mut _102: &mut impl std::future::Future<Output = ()>;
      let mut _103: std::future::ResumeTy;
      let mut _104: std::task::Poll<()>;
      let mut _105: isize;
      let mut _106: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _107: &mut std::task::Context<'_>;
      let mut _108: std::future::ResumeTy;
      let mut _109: &mut impl std::future::Future<Output = ()>;
      let mut _110: std::pin::Pin<&mut AsyncEnum>;
      let mut _111: &mut AsyncEnum;
      let mut _112: impl std::future::Future<Output = ()>;
      let mut _113: std::future::ResumeTy;
      let mut _114: std::task::Poll<()>;
      let mut _115: isize;
      let mut _116: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _117: &mut std::task::Context<'_>;
      let mut _118: std::future::ResumeTy;
      let mut _119: &mut impl std::future::Future<Output = ()>;
      let mut _120: std::future::ResumeTy;
      let mut _121: std::task::Poll<()>;
      let mut _122: isize;
      let mut _123: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _124: &mut std::task::Context<'_>;
      let mut _125: std::future::ResumeTy;
      let mut _126: &mut impl std::future::Future<Output = ()>;
      let mut _127: std::pin::Pin<&mut SyncThenAsync>;
      let mut _128: &mut SyncThenAsync;
      let mut _129: impl std::future::Future<Output = ()>;
      let mut _130: std::future::ResumeTy;
      let mut _131: std::task::Poll<()>;
      let mut _132: isize;
      let mut _133: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _134: &mut std::task::Context<'_>;
      let mut _135: std::future::ResumeTy;
      let mut _136: &mut impl std::future::Future<Output = ()>;
      let mut _137: std::future::ResumeTy;
      let mut _138: std::task::Poll<()>;
      let mut _139: isize;
      let mut _140: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _141: &mut std::task::Context<'_>;
      let mut _142: std::future::ResumeTy;
      let mut _143: &mut impl std::future::Future<Output = ()>;
      let mut _144: std::pin::Pin<&mut AsyncStruct>;
      let mut _145: &mut AsyncStruct;
      let mut _146: impl std::future::Future<Output = ()>;
      let mut _147: std::future::ResumeTy;
      let mut _148: std::task::Poll<()>;
      let mut _149: isize;
      let mut _150: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _151: &mut std::task::Context<'_>;
      let mut _152: std::future::ResumeTy;
      let mut _153: &mut impl std::future::Future<Output = ()>;
      let mut _154: std::future::ResumeTy;
      let mut _155: std::task::Poll<()>;
      let mut _156: isize;
      let mut _157: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _158: &mut std::task::Context<'_>;
      let mut _159: std::future::ResumeTy;
      let mut _160: &mut impl std::future::Future<Output = ()>;
      let mut _161: std::pin::Pin<&mut [AsyncInt; 2]>;
      let mut _162: &mut [AsyncInt; 2];
      let mut _163: impl std::future::Future<Output = ()>;
      let mut _164: std::future::ResumeTy;
      let mut _165: std::task::Poll<()>;
      let mut _166: isize;
      let mut _167: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _168: &mut std::task::Context<'_>;
      let mut _169: std::future::ResumeTy;
      let mut _170: &mut impl std::future::Future<Output = ()>;
      let mut _171: std::future::ResumeTy;
      let mut _172: std::task::Poll<()>;
      let mut _173: isize;
      let mut _174: std::pin::Pin<&mut impl std::future::Future<Output = ()>>;
      let mut _175: &mut std::task::Context<'_>;
      let mut _176: std::future::ResumeTy;
      let mut _177: &mut impl std::future::Future<Output = ()>;
      let mut _178: std::pin::Pin<&mut AsyncInt>;
      let mut _179: &mut AsyncInt;
+     let mut _180: ();
+     let mut _181: u32;
+     let mut _182: &mut {async fn body of elaborate_drops()};
+     let mut _183: std::future::ResumeTy;
+     let mut _184: std::ptr::NonNull<std::task::Context<'_>>;
      scope 1 {
-         debug sync_int => _3;
+         debug sync_int => (((*_182) as variant#20).1: SyncInt);
+         coroutine debug async_int => _s2;
          let _4: AsyncInt;
          scope 2 {
-             debug async_int => _4;
+             debug async_int => (((*_182) as variant#20).2: AsyncInt);
+             coroutine debug tuple => _s3;
              let _5: [AsyncInt; 2];
              scope 3 {
-                 debug tuple => _5;
+                 debug tuple => (((*_182) as variant#18).3: [AsyncInt; 2]);
+                 coroutine debug async_struct => _s4;
                  let _8: AsyncStruct;
                  scope 4 {
-                     debug async_struct => _8;
+                     debug async_struct => (((*_182) as variant#16).4: AsyncStruct);
+                     coroutine debug async_struct_mix => _s5;
                      let _11: SyncThenAsync;
                      scope 5 {
-                         debug async_struct_mix => _11;
+                         debug async_struct_mix => (((*_182) as variant#14).5: SyncThenAsync);
+                         coroutine debug async_enum => _s6;
                          let _15: AsyncEnum;
                          scope 6 {
-                             debug async_enum => _15;
+                             debug async_enum => (((*_182) as variant#12).6: AsyncEnum);
                              let _17: std::mem::ManuallyDrop<AsyncInt>;
                              scope 7 {
                                  debug manually_drop_async_int => _17;
+                                 coroutine debug foo => _s7;
                                  let _19: AsyncInt;
                                  scope 8 {
-                                     debug foo => _19;
+                                     debug foo => (((*_182) as variant#10).7: AsyncInt);
+                                     coroutine debug async_ref => _s8;
                                      let _20: AsyncReference<'_>;
                                      scope 9 {
-                                         debug async_ref => _20;
+                                         debug async_ref => (((*_182) as variant#8).8: AsyncReference<'_>);
                                          let _23: AsyncInt;
                                          scope 10 {
                                              debug foo => _23;
+                                             coroutine debug async_closure => _s9;
                                              let _24: {closure@$DIR/async_drop.rs:78:25: 78:27};
                                              scope 11 {
-                                                 debug async_closure => _24;
+                                                 debug async_closure => (((*_182) as variant#6).9: {closure@$DIR/async_drop.rs:78:25: 78:27});
                                                  let _25: AsyncInt;
                                                  scope 12 {
                                                      debug foo => _25;
+                                                     coroutine debug async_coroutine => _s10;
                                                      let _26: {async closure@$DIR/async_drop.rs:86:27: 86:35};
                                                      scope 13 {
-                                                         debug async_coroutine => _26;
+                                                         debug async_coroutine => (((*_182) as variant#4).10: {async closure@$DIR/async_drop.rs:86:27: 86:35});
                                                      }
                                                  }
                                              }
                                          }
                                      }
                                  }
                              }
                          }
                      }
                  }
              }
          }
      }
  
      bb0: {
-         StorageLive(_3);
-         _3 = SyncInt(const 0_i32);
-         StorageLive(_4);
-         _4 = AsyncInt(const 0_i32);
-         StorageLive(_5);
-         StorageLive(_6);
-         _6 = AsyncInt(const 1_i32);
-         StorageLive(_7);
-         _7 = AsyncInt(const 2_i32);
-         _5 = [move _6, move _7];
-         goto -> bb1;
+         _184 = move _2 as std::ptr::NonNull<std::task::Context<'_>> (Transmute);
+         _183 = std::future::ResumeTy(move _184);
+         _182 = copy (_1.0: &mut {async fn body of elaborate_drops()});
+         _181 = discriminant((*_182));
+         switchInt(move _181) -> [0: bb170, 1: bb169, 2: bb168, 3: bb150, 4: bb151, 5: bb152, 6: bb153, 7: bb154, 8: bb155, 9: bb156, 10: bb157, 11: bb158, 12: bb159, 13: bb160, 14: bb161, 15: bb162, 16: bb163, 17: bb164, 18: bb165, 19: bb166, 20: bb167, otherwise: bb43];
      }
  
      bb1: {
          StorageDead(_7);
          goto -> bb2;
      }
  
      bb2: {
          StorageDead(_6);
-         StorageLive(_8);
+         nop;
          StorageLive(_9);
          _9 = AsyncInt(const 5_i32);
          StorageLive(_10);
          _10 = AsyncInt(const 4_i32);
-         _8 = AsyncStruct { i: const 3_i32, a: move _10, b: move _9 };
+         (((*_182) as variant#16).4: AsyncStruct) = AsyncStruct { i: const 3_i32, a: move _10, b: move _9 };
          goto -> bb3;
      }
  
      bb3: {
          StorageDead(_10);
          goto -> bb4;
      }
  
      bb4: {
          StorageDead(_9);
-         StorageLive(_11);
+         nop;
          StorageLive(_12);
          _12 = AsyncInt(const 7_i32);
          StorageLive(_13);
          _13 = SyncInt(const 8_i32);
          StorageLive(_14);
          _14 = AsyncInt(const 9_i32);
-         _11 = SyncThenAsync { i: const 6_i32, a: move _12, b: move _13, c: move _14 };
+         (((*_182) as variant#14).5: SyncThenAsync) = SyncThenAsync { i: const 6_i32, a: move _12, b: move _13, c: move _14 };
          goto -> bb5;
      }
  
      bb5: {
          StorageDead(_14);
          goto -> bb6;
      }
  
      bb6: {
          StorageDead(_13);
          goto -> bb7;
      }
  
      bb7: {
          StorageDead(_12);
-         StorageLive(_15);
+         nop;
          StorageLive(_16);
          _16 = AsyncInt(const 10_i32);
-         _15 = AsyncEnum::A(move _16);
+         (((*_182) as variant#12).6: AsyncEnum) = AsyncEnum::A(move _16);
          goto -> bb8;
      }
  
      bb8: {
          StorageDead(_16);
          StorageLive(_17);
          StorageLive(_18);
          _18 = AsyncInt(const 11_i32);
-         _17 = ManuallyDrop::<AsyncInt>::new(move _18) -> [return: bb9, unwind: bb42];
+         _17 = ManuallyDrop::<AsyncInt>::new(move _18) -> [return: bb9, unwind: bb29];
      }
  
      bb9: {
          StorageDead(_18);
-         StorageLive(_19);
-         _19 = AsyncInt(const 12_i32);
-         StorageLive(_20);
+         nop;
+         (((*_182) as variant#10).7: AsyncInt) = AsyncInt(const 12_i32);
+         nop;
          StorageLive(_21);
          StorageLive(_22);
-         _22 = &_19;
+         _22 = &(((*_182) as variant#10).7: AsyncInt);
          _21 = &(*_22);
-         _20 = AsyncReference::<'_> { foo: move _21 };
+         (((*_182) as variant#8).8: AsyncReference<'_>) = AsyncReference::<'_> { foo: move _21 };
          StorageDead(_21);
          StorageDead(_22);
          StorageLive(_23);
          _23 = AsyncInt(const 14_i32);
-         StorageLive(_24);
-         _24 = {closure@$DIR/async_drop.rs:78:25: 78:27} { foo: move _23 };
+         nop;
+         (((*_182) as variant#6).9: {closure@$DIR/async_drop.rs:78:25: 78:27}) = {closure@$DIR/async_drop.rs:78:25: 78:27} { foo: move _23 };
          StorageLive(_25);
          _25 = AsyncInt(const 15_i32);
-         StorageLive(_26);
-         _26 = {closure@$DIR/async_drop.rs:86:27: 86:35} { foo: move _25 };
-         _0 = const ();
-         goto -> bb72;
+         nop;
+         (((*_182) as variant#4).10: {async closure@$DIR/async_drop.rs:86:27: 86:35}) = {closure@$DIR/async_drop.rs:86:27: 86:35} { foo: move _25 };
+         (((*_182) as variant#20).0: ()) = const ();
+         goto -> bb51;
      }
  
      bb10: {
-         StorageDead(_26);
+         nop;
          goto -> bb11;
      }
  
      bb11: {
          StorageDead(_25);
-         goto -> bb92;
+         goto -> bb63;
      }
  
      bb12: {
-         StorageDead(_24);
+         nop;
          goto -> bb13;
      }
  
      bb13: {
          StorageDead(_23);
-         goto -> bb112;
+         goto -> bb75;
      }
  
      bb14: {
-         StorageDead(_20);
-         goto -> bb132;
+         nop;
+         goto -> bb87;
      }
  
      bb15: {
-         StorageDead(_19);
+         nop;
          StorageDead(_17);
-         goto -> bb152;
+         goto -> bb99;
      }
  
      bb16: {
-         StorageDead(_15);
-         goto -> bb172;
+         nop;
+         goto -> bb111;
      }
  
      bb17: {
-         StorageDead(_11);
-         goto -> bb192;
+         nop;
+         goto -> bb123;
      }
  
      bb18: {
-         StorageDead(_8);
-         goto -> bb212;
+         nop;
+         goto -> bb135;
      }
  
      bb19: {
-         StorageDead(_5);
-         goto -> bb232;
+         nop;
+         goto -> bb147;
      }
  
      bb20: {
-         StorageDead(_4);
-         drop(_3) -> [return: bb21, unwind: bb50];
+         nop;
+         drop((((*_182) as variant#20).1: SyncInt)) -> [return: bb21, unwind: bb37];
      }
  
      bb21: {
-         StorageDead(_3);
-         drop(_1) -> [return: bb22, unwind: bb51];
+         nop;
+         goto -> bb148;
      }
  
      bb22: {
+         _0 = Poll::<()>::Ready(move (((*_182) as variant#20).0: ()));
+         discriminant((*_182)) = 1;
          return;
      }
  
-     bb23: {
-         StorageDead(_26);
+     bb23 (cleanup): {
+         nop;
          goto -> bb24;
      }
  
-     bb24: {
+     bb24 (cleanup): {
          StorageDead(_25);
-         goto -> bb25;
+         drop((((*_182) as variant#6).9: {closure@$DIR/async_drop.rs:78:25: 78:27})) -> [return: bb25, unwind terminate(cleanup)];
      }
  
-     bb25: {
-         StorageDead(_24);
+     bb25 (cleanup): {
+         nop;
          goto -> bb26;
      }
  
-     bb26: {
+     bb26 (cleanup): {
          StorageDead(_23);
-         goto -> bb27;
+         drop((((*_182) as variant#8).8: AsyncReference<'_>)) -> [return: bb27, unwind terminate(cleanup)];
      }
  
-     bb27: {
-         StorageDead(_20);
-         goto -> bb28;
+     bb27 (cleanup): {
+         nop;
+         drop((((*_182) as variant#10).7: AsyncInt)) -> [return: bb28, unwind terminate(cleanup)];
      }
  
-     bb28: {
-         StorageDead(_19);
-         StorageDead(_17);
-         goto -> bb29;
+     bb28 (cleanup): {
+         nop;
+         goto -> bb31;
      }
  
-     bb29: {
-         StorageDead(_15);
+     bb29 (cleanup): {
          goto -> bb30;
      }
  
-     bb30: {
-         StorageDead(_11);
+     bb30 (cleanup): {
+         StorageDead(_18);
          goto -> bb31;
      }
  
-     bb31: {
-         StorageDead(_8);
-         goto -> bb32;
+     bb31 (cleanup): {
+         StorageDead(_17);
+         drop((((*_182) as variant#12).6: AsyncEnum)) -> [return: bb32, unwind terminate(cleanup)];
      }
  
-     bb32: {
-         StorageDead(_5);
-         goto -> bb33;
+     bb32 (cleanup): {
+         nop;
+         drop((((*_182) as variant#14).5: SyncThenAsync)) -> [return: bb33, unwind terminate(cleanup)];
      }
  
-     bb33: {
-         StorageDead(_4);
-         goto -> bb34;
+     bb33 (cleanup): {
+         nop;
+         drop((((*_182) as variant#16).4: AsyncStruct)) -> [return: bb34, unwind terminate(cleanup)];
      }
  
-     bb34: {
-         StorageDead(_3);
-         goto -> bb35;
+     bb34 (cleanup): {
+         nop;
+         drop((((*_182) as variant#18).3: [AsyncInt; 2])) -> [return: bb35, unwind terminate(cleanup)];
      }
  
-     bb35: {
-         coroutine_drop;
+     bb35 (cleanup): {
+         nop;
+         drop((((*_182) as variant#20).2: AsyncInt)) -> [return: bb36, unwind terminate(cleanup)];
      }
  
      bb36 (cleanup): {
-         StorageDead(_26);
-         goto -> bb37;
+         nop;
+         drop((((*_182) as variant#20).1: SyncInt)) -> [return: bb37, unwind terminate(cleanup)];
      }
  
      bb37 (cleanup): {
-         StorageDead(_25);
-         drop(_24) -> [return: bb38, unwind terminate(cleanup)];
+         nop;
+         goto -> bb38;
      }
  
      bb38 (cleanup): {
-         StorageDead(_24);
-         goto -> bb39;
+         goto -> bb149;
      }
  
-     bb39 (cleanup): {
-         StorageDead(_23);
-         drop(_20) -> [return: bb40, unwind terminate(cleanup)];
+     bb39: {
+         nop;
+         goto -> bb10;
      }
  
      bb40 (cleanup): {
-         StorageDead(_20);
-         drop(_19) -> [return: bb41, unwind terminate(cleanup)];
+         nop;
+         goto -> bb23;
      }
  
-     bb41 (cleanup): {
-         StorageDead(_19);
-         goto -> bb44;
+     bb41: {
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb41, unwind: bb40];
      }
  
-     bb42 (cleanup): {
-         goto -> bb43;
+     bb42: {
+         _183 = move _28;
+         StorageDead(_28);
+         goto -> bb41;
      }
  
-     bb43 (cleanup): {
-         StorageDead(_18);
-         goto -> bb44;
+     bb43: {
+         unreachable;
      }
  
-     bb44 (cleanup): {
-         StorageDead(_17);
-         drop(_15) -> [return: bb45, unwind terminate(cleanup)];
+     bb44: {
+         _183 = move _35;
+         StorageDead(_35);
+         goto -> bb49;
      }
  
-     bb45 (cleanup): {
-         StorageDead(_15);
-         drop(_11) -> [return: bb46, unwind terminate(cleanup)];
+     bb45: {
+         StorageLive(_35);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_17);
+         StorageDead(_23);
+         StorageDead(_25);
+         StorageDead(_35);
+         discriminant((*_182)) = 4;
+         return;
      }
  
-     bb46 (cleanup): {
-         StorageDead(_11);
-         drop(_8) -> [return: bb47, unwind terminate(cleanup)];
+     bb46: {
+         _37 = discriminant(_36);
+         switchInt(move _37) -> [0: bb39, 1: bb45, otherwise: bb43];
      }
  
-     bb47 (cleanup): {
-         StorageDead(_8);
-         drop(_5) -> [return: bb48, unwind terminate(cleanup)];
+     bb47: {
+         _36 = <impl Future<Output = ()> as Future>::poll(move _38, move _39) -> [return: bb46, unwind: bb40];
      }
  
-     bb48 (cleanup): {
-         StorageDead(_5);
-         drop(_4) -> [return: bb49, unwind terminate(cleanup)];
+     bb48: {
+         _40 = move _183;
+         _39 = copy (_40.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb47;
      }
  
-     bb49 (cleanup): {
-         StorageDead(_4);
-         drop(_3) -> [return: bb50, unwind terminate(cleanup)];
+     bb49: {
+         _41 = &mut (((*_182) as variant#4).11: impl std::future::Future<Output = ()>);
+         _38 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _41) -> [return: bb48, unwind: bb40];
      }
  
-     bb50 (cleanup): {
-         StorageDead(_3);
-         drop(_1) -> [return: bb51, unwind terminate(cleanup)];
+     bb50: {
+         nop;
+         (((*_182) as variant#4).11: impl std::future::Future<Output = ()>) = async_drop_in_place::<{async closure@$DIR/async_drop.rs:86:27: 86:35}>(copy (_42.0: &mut {async closure@$DIR/async_drop.rs:86:27: 86:35})) -> [return: bb49, unwind: bb40];
      }
  
-     bb51 (cleanup): {
-         resume;
+     bb51: {
+         _43 = &mut (((*_182) as variant#4).10: {async closure@$DIR/async_drop.rs:86:27: 86:35});
+         _42 = Pin::<&mut {async closure@$DIR/async_drop.rs:86:27: 86:35}>::new_unchecked(move _43) -> [return: bb50, unwind: bb23];
      }
  
      bb52: {
-         StorageDead(_27);
-         goto -> bb10;
+         nop;
+         goto -> bb12;
      }
  
-     bb53: {
-         StorageDead(_27);
-         goto -> bb23;
+     bb53 (cleanup): {
+         nop;
+         goto -> bb25;
      }
  
-     bb54 (cleanup): {
-         StorageDead(_27);
-         goto -> bb36;
+     bb54: {
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb54, unwind: bb53];
      }
  
      bb55: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb55, unwind: bb54];
+         _183 = move _45;
+         StorageDead(_45);
+         goto -> bb54;
      }
  
      bb56: {
-         _2 = move _28;
-         StorageDead(_28);
-         goto -> bb55;
+         _183 = move _52;
+         StorageDead(_52);
+         goto -> bb61;
      }
  
      bb57: {
-         _2 = move _28;
-         StorageDead(_28);
-         goto -> bb63;
+         StorageLive(_52);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_17);
+         StorageDead(_23);
+         StorageDead(_52);
+         discriminant((*_182)) = 6;
+         return;
      }
  
      bb58: {
-         StorageLive(_28);
-         _28 = yield(const ()) -> [resume: bb56, drop: bb57];
+         _54 = discriminant(_53);
+         switchInt(move _54) -> [0: bb52, 1: bb57, otherwise: bb43];
      }
  
      bb59: {
-         unreachable;
+         _53 = <impl Future<Output = ()> as Future>::poll(move _55, move _56) -> [return: bb58, unwind: bb53];
      }
  
      bb60: {
-         _30 = discriminant(_29);
-         switchInt(move _30) -> [0: bb53, 1: bb58, otherwise: bb59];
+         _57 = move _183;
+         _56 = copy (_57.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb59;
      }
  
      bb61: {
-         _29 = <impl Future<Output = ()> as Future>::poll(move _31, move _32) -> [return: bb60, unwind: bb54];
+         _58 = &mut (((*_182) as variant#6).10: impl std::future::Future<Output = ()>);
+         _55 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _58) -> [return: bb60, unwind: bb53];
      }
  
      bb62: {
-         _33 = move _2;
-         _32 = std::future::get_context::<'_, '_>(move _33) -> [return: bb61, unwind: bb54];
+         nop;
+         (((*_182) as variant#6).10: impl std::future::Future<Output = ()>) = async_drop_in_place::<{closure@$DIR/async_drop.rs:78:25: 78:27}>(copy (_59.0: &mut {closure@$DIR/async_drop.rs:78:25: 78:27})) -> [return: bb61, unwind: bb53];
      }
  
      bb63: {
-         _34 = &mut _27;
-         _31 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _34) -> [return: bb62, unwind: bb54];
+         _60 = &mut (((*_182) as variant#6).9: {closure@$DIR/async_drop.rs:78:25: 78:27});
+         _59 = Pin::<&mut {closure@$DIR/async_drop.rs:78:25: 78:27}>::new_unchecked(move _60) -> [return: bb62, unwind: bb25];
      }
  
      bb64: {
-         _2 = move _35;
-         StorageDead(_35);
-         goto -> bb70;
+         nop;
+         goto -> bb14;
      }
  
-     bb65: {
-         _2 = move _35;
-         StorageDead(_35);
-         goto -> bb63;
+     bb65 (cleanup): {
+         nop;
+         goto -> bb27;
      }
  
      bb66: {
-         StorageLive(_35);
-         _35 = yield(const ()) -> [resume: bb64, drop: bb65];
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb66, unwind: bb65];
      }
  
      bb67: {
-         _37 = discriminant(_36);
-         switchInt(move _37) -> [0: bb52, 1: bb66, otherwise: bb59];
+         _183 = move _62;
+         StorageDead(_62);
+         goto -> bb66;
      }
  
      bb68: {
-         _36 = <impl Future<Output = ()> as Future>::poll(move _38, move _39) -> [return: bb67, unwind: bb54];
+         _183 = move _69;
+         StorageDead(_69);
+         goto -> bb73;
      }
  
      bb69: {
-         _40 = move _2;
-         _39 = std::future::get_context::<'_, '_>(move _40) -> [return: bb68, unwind: bb54];
+         StorageLive(_69);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_17);
+         StorageDead(_69);
+         discriminant((*_182)) = 8;
+         return;
      }
  
      bb70: {
-         _41 = &mut _27;
-         _38 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _41) -> [return: bb69, unwind: bb54];
+         _71 = discriminant(_70);
+         switchInt(move _71) -> [0: bb64, 1: bb69, otherwise: bb43];
      }
  
      bb71: {
-         StorageLive(_27);
-         _27 = async_drop_in_place::<{async closure@$DIR/async_drop.rs:86:27: 86:35}>(copy (_42.0: &mut {async closure@$DIR/async_drop.rs:86:27: 86:35})) -> [return: bb70, unwind: bb54];
+         _70 = <impl Future<Output = ()> as Future>::poll(move _72, move _73) -> [return: bb70, unwind: bb65];
      }
  
      bb72: {
-         _43 = &mut _26;
-         _42 = Pin::<&mut {async closure@$DIR/async_drop.rs:86:27: 86:35}>::new_unchecked(move _43) -> [return: bb71, unwind: bb36];
+         _74 = move _183;
+         _73 = copy (_74.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb71;
      }
  
      bb73: {
-         StorageDead(_44);
-         goto -> bb12;
+         _75 = &mut (((*_182) as variant#8).9: impl std::future::Future<Output = ()>);
+         _72 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _75) -> [return: bb72, unwind: bb65];
      }
  
      bb74: {
-         StorageDead(_44);
-         goto -> bb25;
+         nop;
+         (((*_182) as variant#8).9: impl std::future::Future<Output = ()>) = async_drop_in_place::<AsyncReference<'_>>(copy (_76.0: &mut AsyncReference<'_>)) -> [return: bb73, unwind: bb65];
      }
  
-     bb75 (cleanup): {
-         StorageDead(_44);
-         goto -> bb38;
+     bb75: {
+         _77 = &mut (((*_182) as variant#8).8: AsyncReference<'_>);
+         _76 = Pin::<&mut AsyncReference<'_>>::new_unchecked(move _77) -> [return: bb74, unwind: bb27];
      }
  
      bb76: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb76, unwind: bb75];
+         nop;
+         goto -> bb15;
      }
  
-     bb77: {
-         _2 = move _45;
-         StorageDead(_45);
-         goto -> bb76;
+     bb77 (cleanup): {
+         nop;
+         goto -> bb28;
      }
  
      bb78: {
-         _2 = move _45;
-         StorageDead(_45);
-         goto -> bb83;
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb78, unwind: bb77];
      }
  
      bb79: {
-         StorageLive(_45);
-         _45 = yield(const ()) -> [resume: bb77, drop: bb78];
+         _183 = move _79;
+         StorageDead(_79);
+         goto -> bb78;
      }
  
      bb80: {
-         _47 = discriminant(_46);
-         switchInt(move _47) -> [0: bb74, 1: bb79, otherwise: bb59];
+         _183 = move _86;
+         StorageDead(_86);
+         goto -> bb85;
      }
  
      bb81: {
-         _46 = <impl Future<Output = ()> as Future>::poll(move _48, move _49) -> [return: bb80, unwind: bb75];
+         StorageLive(_86);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_17);
+         StorageDead(_86);
+         discriminant((*_182)) = 10;
+         return;
      }
  
      bb82: {
-         _50 = move _2;
-         _49 = std::future::get_context::<'_, '_>(move _50) -> [return: bb81, unwind: bb75];
+         _88 = discriminant(_87);
+         switchInt(move _88) -> [0: bb76, 1: bb81, otherwise: bb43];
      }
  
      bb83: {
-         _51 = &mut _44;
-         _48 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _51) -> [return: bb82, unwind: bb75];
+         _87 = <impl Future<Output = ()> as Future>::poll(move _89, move _90) -> [return: bb82, unwind: bb77];
      }
  
      bb84: {
-         _2 = move _52;
-         StorageDead(_52);
-         goto -> bb90;
+         _91 = move _183;
+         _90 = copy (_91.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb83;
      }
  
      bb85: {
-         _2 = move _52;
-         StorageDead(_52);
-         goto -> bb83;
+         _92 = &mut (((*_182) as variant#10).8: impl std::future::Future<Output = ()>);
+         _89 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _92) -> [return: bb84, unwind: bb77];
      }
  
      bb86: {
-         StorageLive(_52);
-         _52 = yield(const ()) -> [resume: bb84, drop: bb85];
+         nop;
+         (((*_182) as variant#10).8: impl std::future::Future<Output = ()>) = async_drop_in_place::<AsyncInt>(copy (_93.0: &mut AsyncInt)) -> [return: bb85, unwind: bb77];
      }
  
      bb87: {
-         _54 = discriminant(_53);
-         switchInt(move _54) -> [0: bb73, 1: bb86, otherwise: bb59];
+         _94 = &mut (((*_182) as variant#10).7: AsyncInt);
+         _93 = Pin::<&mut AsyncInt>::new_unchecked(move _94) -> [return: bb86, unwind: bb28];
      }
  
      bb88: {
-         _53 = <impl Future<Output = ()> as Future>::poll(move _55, move _56) -> [return: bb87, unwind: bb75];
+         nop;
+         goto -> bb16;
      }
  
-     bb89: {
-         _57 = move _2;
-         _56 = std::future::get_context::<'_, '_>(move _57) -> [return: bb88, unwind: bb75];
+     bb89 (cleanup): {
+         nop;
+         goto -> bb32;
      }
  
      bb90: {
-         _58 = &mut _44;
-         _55 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _58) -> [return: bb89, unwind: bb75];
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb90, unwind: bb89];
      }
  
      bb91: {
-         StorageLive(_44);
-         _44 = async_drop_in_place::<{closure@$DIR/async_drop.rs:78:25: 78:27}>(copy (_59.0: &mut {closure@$DIR/async_drop.rs:78:25: 78:27})) -> [return: bb90, unwind: bb75];
+         _183 = move _96;
+         StorageDead(_96);
+         goto -> bb90;
      }
  
      bb92: {
-         _60 = &mut _24;
-         _59 = Pin::<&mut {closure@$DIR/async_drop.rs:78:25: 78:27}>::new_unchecked(move _60) -> [return: bb91, unwind: bb38];
+         _183 = move _103;
+         StorageDead(_103);
+         goto -> bb97;
      }
  
      bb93: {
-         StorageDead(_61);
-         goto -> bb14;
+         StorageLive(_103);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_103);
+         discriminant((*_182)) = 12;
+         return;
      }
  
      bb94: {
-         StorageDead(_61);
-         goto -> bb27;
+         _105 = discriminant(_104);
+         switchInt(move _105) -> [0: bb88, 1: bb93, otherwise: bb43];
      }
  
-     bb95 (cleanup): {
-         StorageDead(_61);
-         goto -> bb40;
+     bb95: {
+         _104 = <impl Future<Output = ()> as Future>::poll(move _106, move _107) -> [return: bb94, unwind: bb89];
      }
  
      bb96: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb96, unwind: bb95];
+         _108 = move _183;
+         _107 = copy (_108.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb95;
      }
  
      bb97: {
-         _2 = move _62;
-         StorageDead(_62);
-         goto -> bb96;
+         _109 = &mut (((*_182) as variant#12).7: impl std::future::Future<Output = ()>);
+         _106 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _109) -> [return: bb96, unwind: bb89];
      }
  
      bb98: {
-         _2 = move _62;
-         StorageDead(_62);
-         goto -> bb103;
+         nop;
+         (((*_182) as variant#12).7: impl std::future::Future<Output = ()>) = async_drop_in_place::<AsyncEnum>(copy (_110.0: &mut AsyncEnum)) -> [return: bb97, unwind: bb89];
      }
  
      bb99: {
-         StorageLive(_62);
-         _62 = yield(const ()) -> [resume: bb97, drop: bb98];
+         _111 = &mut (((*_182) as variant#12).6: AsyncEnum);
+         _110 = Pin::<&mut AsyncEnum>::new_unchecked(move _111) -> [return: bb98, unwind: bb32];
      }
  
      bb100: {
-         _64 = discriminant(_63);
-         switchInt(move _64) -> [0: bb94, 1: bb99, otherwise: bb59];
+         nop;
+         goto -> bb17;
      }
  
-     bb101: {
-         _63 = <impl Future<Output = ()> as Future>::poll(move _65, move _66) -> [return: bb100, unwind: bb95];
+     bb101 (cleanup): {
+         nop;
+         goto -> bb33;
      }
  
      bb102: {
-         _67 = move _2;
-         _66 = std::future::get_context::<'_, '_>(move _67) -> [return: bb101, unwind: bb95];
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb102, unwind: bb101];
      }
  
      bb103: {
-         _68 = &mut _61;
-         _65 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _68) -> [return: bb102, unwind: bb95];
+         _183 = move _113;
+         StorageDead(_113);
+         goto -> bb102;
      }
  
      bb104: {
-         _2 = move _69;
-         StorageDead(_69);
-         goto -> bb110;
+         _183 = move _120;
+         StorageDead(_120);
+         goto -> bb109;
      }
  
      bb105: {
-         _2 = move _69;
-         StorageDead(_69);
-         goto -> bb103;
+         StorageLive(_120);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_120);
+         discriminant((*_182)) = 14;
+         return;
      }
  
      bb106: {
-         StorageLive(_69);
-         _69 = yield(const ()) -> [resume: bb104, drop: bb105];
+         _122 = discriminant(_121);
+         switchInt(move _122) -> [0: bb100, 1: bb105, otherwise: bb43];
      }
  
      bb107: {
-         _71 = discriminant(_70);
-         switchInt(move _71) -> [0: bb93, 1: bb106, otherwise: bb59];
+         _121 = <impl Future<Output = ()> as Future>::poll(move _123, move _124) -> [return: bb106, unwind: bb101];
      }
  
      bb108: {
-         _70 = <impl Future<Output = ()> as Future>::poll(move _72, move _73) -> [return: bb107, unwind: bb95];
+         _125 = move _183;
+         _124 = copy (_125.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb107;
      }
  
      bb109: {
-         _74 = move _2;
-         _73 = std::future::get_context::<'_, '_>(move _74) -> [return: bb108, unwind: bb95];
+         _126 = &mut (((*_182) as variant#14).6: impl std::future::Future<Output = ()>);
+         _123 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _126) -> [return: bb108, unwind: bb101];
      }
  
      bb110: {
-         _75 = &mut _61;
-         _72 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _75) -> [return: bb109, unwind: bb95];
+         nop;
+         (((*_182) as variant#14).6: impl std::future::Future<Output = ()>) = async_drop_in_place::<SyncThenAsync>(copy (_127.0: &mut SyncThenAsync)) -> [return: bb109, unwind: bb101];
      }
  
      bb111: {
-         StorageLive(_61);
-         _61 = async_drop_in_place::<AsyncReference<'_>>(copy (_76.0: &mut AsyncReference<'_>)) -> [return: bb110, unwind: bb95];
+         _128 = &mut (((*_182) as variant#14).5: SyncThenAsync);
+         _127 = Pin::<&mut SyncThenAsync>::new_unchecked(move _128) -> [return: bb110, unwind: bb33];
      }
  
      bb112: {
-         _77 = &mut _20;
-         _76 = Pin::<&mut AsyncReference<'_>>::new_unchecked(move _77) -> [return: bb111, unwind: bb40];
+         nop;
+         goto -> bb18;
      }
  
-     bb113: {
-         StorageDead(_78);
-         goto -> bb15;
+     bb113 (cleanup): {
+         nop;
+         goto -> bb34;
      }
  
      bb114: {
-         StorageDead(_78);
-         goto -> bb28;
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb114, unwind: bb113];
      }
  
-     bb115 (cleanup): {
-         StorageDead(_78);
-         goto -> bb41;
+     bb115: {
+         _183 = move _130;
+         StorageDead(_130);
+         goto -> bb114;
      }
  
      bb116: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb116, unwind: bb115];
+         _183 = move _137;
+         StorageDead(_137);
+         goto -> bb121;
      }
  
      bb117: {
-         _2 = move _79;
-         StorageDead(_79);
-         goto -> bb116;
+         StorageLive(_137);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_137);
+         discriminant((*_182)) = 16;
+         return;
      }
  
      bb118: {
-         _2 = move _79;
-         StorageDead(_79);
-         goto -> bb123;
+         _139 = discriminant(_138);
+         switchInt(move _139) -> [0: bb112, 1: bb117, otherwise: bb43];
      }
  
      bb119: {
-         StorageLive(_79);
-         _79 = yield(const ()) -> [resume: bb117, drop: bb118];
+         _138 = <impl Future<Output = ()> as Future>::poll(move _140, move _141) -> [return: bb118, unwind: bb113];
      }
  
      bb120: {
-         _81 = discriminant(_80);
-         switchInt(move _81) -> [0: bb114, 1: bb119, otherwise: bb59];
+         _142 = move _183;
+         _141 = copy (_142.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb119;
      }
  
      bb121: {
-         _80 = <impl Future<Output = ()> as Future>::poll(move _82, move _83) -> [return: bb120, unwind: bb115];
+         _143 = &mut (((*_182) as variant#16).5: impl std::future::Future<Output = ()>);
+         _140 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _143) -> [return: bb120, unwind: bb113];
      }
  
      bb122: {
-         _84 = move _2;
-         _83 = std::future::get_context::<'_, '_>(move _84) -> [return: bb121, unwind: bb115];
+         nop;
+         (((*_182) as variant#16).5: impl std::future::Future<Output = ()>) = async_drop_in_place::<AsyncStruct>(copy (_144.0: &mut AsyncStruct)) -> [return: bb121, unwind: bb113];
      }
  
      bb123: {
-         _85 = &mut _78;
-         _82 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _85) -> [return: bb122, unwind: bb115];
+         _145 = &mut (((*_182) as variant#16).4: AsyncStruct);
+         _144 = Pin::<&mut AsyncStruct>::new_unchecked(move _145) -> [return: bb122, unwind: bb34];
      }
  
      bb124: {
-         _2 = move _86;
-         StorageDead(_86);
-         goto -> bb130;
+         nop;
+         goto -> bb19;
      }
  
-     bb125: {
-         _2 = move _86;
-         StorageDead(_86);
-         goto -> bb123;
+     bb125 (cleanup): {
+         nop;
+         goto -> bb35;
      }
  
      bb126: {
-         StorageLive(_86);
-         _86 = yield(const ()) -> [resume: bb124, drop: bb125];
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb126, unwind: bb125];
      }
  
      bb127: {
-         _88 = discriminant(_87);
-         switchInt(move _88) -> [0: bb113, 1: bb126, otherwise: bb59];
+         _183 = move _147;
+         StorageDead(_147);
+         goto -> bb126;
      }
  
      bb128: {
-         _87 = <impl Future<Output = ()> as Future>::poll(move _89, move _90) -> [return: bb127, unwind: bb115];
+         _183 = move _154;
+         StorageDead(_154);
+         goto -> bb133;
      }
  
      bb129: {
-         _91 = move _2;
-         _90 = std::future::get_context::<'_, '_>(move _91) -> [return: bb128, unwind: bb115];
+         StorageLive(_154);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_154);
+         discriminant((*_182)) = 18;
+         return;
      }
  
      bb130: {
-         _92 = &mut _78;
-         _89 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _92) -> [return: bb129, unwind: bb115];
+         _156 = discriminant(_155);
+         switchInt(move _156) -> [0: bb124, 1: bb129, otherwise: bb43];
      }
  
      bb131: {
-         StorageLive(_78);
-         _78 = async_drop_in_place::<AsyncInt>(copy (_93.0: &mut AsyncInt)) -> [return: bb130, unwind: bb115];
+         _155 = <impl Future<Output = ()> as Future>::poll(move _157, move _158) -> [return: bb130, unwind: bb125];
      }
  
      bb132: {
-         _94 = &mut _19;
-         _93 = Pin::<&mut AsyncInt>::new_unchecked(move _94) -> [return: bb131, unwind: bb41];
+         _159 = move _183;
+         _158 = copy (_159.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb131;
      }
  
      bb133: {
-         StorageDead(_95);
-         goto -> bb16;
+         _160 = &mut (((*_182) as variant#18).4: impl std::future::Future<Output = ()>);
+         _157 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _160) -> [return: bb132, unwind: bb125];
      }
  
      bb134: {
-         StorageDead(_95);
-         goto -> bb29;
+         nop;
+         (((*_182) as variant#18).4: impl std::future::Future<Output = ()>) = async_drop_in_place::<[AsyncInt; 2]>(copy (_161.0: &mut [AsyncInt; 2])) -> [return: bb133, unwind: bb125];
      }
  
-     bb135 (cleanup): {
-         StorageDead(_95);
-         goto -> bb45;
+     bb135: {
+         _162 = &mut (((*_182) as variant#18).3: [AsyncInt; 2]);
+         _161 = Pin::<&mut [AsyncInt; 2]>::new_unchecked(move _162) -> [return: bb134, unwind: bb35];
      }
  
      bb136: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb136, unwind: bb135];
+         nop;
+         goto -> bb20;
      }
  
-     bb137: {
-         _2 = move _96;
-         StorageDead(_96);
-         goto -> bb136;
+     bb137 (cleanup): {
+         nop;
+         goto -> bb36;
      }
  
      bb138: {
-         _2 = move _96;
-         StorageDead(_96);
-         goto -> bb143;
+         assert(const false, "`async fn` resumed after async drop") -> [success: bb138, unwind: bb137];
      }
  
      bb139: {
-         StorageLive(_96);
-         _96 = yield(const ()) -> [resume: bb137, drop: bb138];
+         _183 = move _164;
+         StorageDead(_164);
+         goto -> bb138;
      }
  
      bb140: {
-         _98 = discriminant(_97);
-         switchInt(move _98) -> [0: bb134, 1: bb139, otherwise: bb59];
+         _183 = move _171;
+         StorageDead(_171);
+         goto -> bb145;
      }
  
      bb141: {
-         _97 = <impl Future<Output = ()> as Future>::poll(move _99, move _100) -> [return: bb140, unwind: bb135];
+         StorageLive(_171);
+         _0 = Poll::<()>::Pending;
+         StorageDead(_171);
+         discriminant((*_182)) = 20;
+         return;
      }
  
      bb142: {
-         _101 = move _2;
-         _100 = std::future::get_context::<'_, '_>(move _101) -> [return: bb141, unwind: bb135];
+         _173 = discriminant(_172);
+         switchInt(move _173) -> [0: bb136, 1: bb141, otherwise: bb43];
      }
  
      bb143: {
-         _102 = &mut _95;
-         _99 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _102) -> [return: bb142, unwind: bb135];
+         _172 = <impl Future<Output = ()> as Future>::poll(move _174, move _175) -> [return: bb142, unwind: bb137];
      }
  
      bb144: {
-         _2 = move _103;
-         StorageDead(_103);
-         goto -> bb150;
+         _176 = move _183;
+         _175 = copy (_176.0: std::ptr::NonNull<std::task::Context<'_>>) as &mut std::task::Context<'_> (Transmute);
+         goto -> bb143;
      }
  
      bb145: {
-         _2 = move _103;
-         StorageDead(_103);
-         goto -> bb143;
+         _177 = &mut (((*_182) as variant#20).3: impl std::future::Future<Output = ()>);
+         _174 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _177) -> [return: bb144, unwind: bb137];
      }
  
      bb146: {
-         StorageLive(_103);
-         _103 = yield(const ()) -> [resume: bb144, drop: bb145];
+         nop;
+         (((*_182) as variant#20).3: impl std::future::Future<Output = ()>) = async_drop_in_place::<AsyncInt>(copy (_178.0: &mut AsyncInt)) -> [return: bb145, unwind: bb137];
      }
  
      bb147: {
-         _105 = discriminant(_104);
-         switchInt(move _105) -> [0: bb133, 1: bb146, otherwise: bb59];
+         _179 = &mut (((*_182) as variant#20).2: AsyncInt);
+         _178 = Pin::<&mut AsyncInt>::new_unchecked(move _179) -> [return: bb146, unwind: bb36];
      }
  
      bb148: {
-         _104 = <impl Future<Output = ()> as Future>::poll(move _106, move _107) -> [return: bb147, unwind: bb135];
+         goto -> bb22;
      }
  
-     bb149: {
-         _108 = move _2;
-         _107 = std::future::get_context::<'_, '_>(move _108) -> [return: bb148, unwind: bb135];
+     bb149 (cleanup): {
+         discriminant((*_182)) = 2;
+         resume;
      }
  
      bb150: {
-         _109 = &mut _95;
-         _106 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _109) -> [return: bb149, unwind: bb135];
+         StorageLive(_17);
+         StorageLive(_23);
+         StorageLive(_25);
+         StorageLive(_28);
+         _28 = move _183;
+         goto -> bb42;
      }
  
      bb151: {
-         StorageLive(_95);
-         _95 = async_drop_in_place::<AsyncEnum>(copy (_110.0: &mut AsyncEnum)) -> [return: bb150, unwind: bb135];
+         StorageLive(_17);
+         StorageLive(_23);
+         StorageLive(_25);
+         StorageLive(_35);
+         _35 = move _183;
+         goto -> bb44;
      }
  
      bb152: {
-         _111 = &mut _15;
-         _110 = Pin::<&mut AsyncEnum>::new_unchecked(move _111) -> [return: bb151, unwind: bb45];
+         StorageLive(_17);
+         StorageLive(_23);
+         StorageLive(_45);
+         _45 = move _183;
+         goto -> bb55;
      }
  
      bb153: {
-         StorageDead(_112);
-         goto -> bb17;
+         StorageLive(_17);
+         StorageLive(_23);
+         StorageLive(_52);
+         _52 = move _183;
+         goto -> bb56;
      }
  
      bb154: {
-         StorageDead(_112);
-         goto -> bb30;
+         StorageLive(_17);
+         StorageLive(_62);
+         _62 = move _183;
+         goto -> bb67;
      }
  
-     bb155 (cleanup): {
-         StorageDead(_112);
-         goto -> bb46;
+     bb155: {
+         StorageLive(_17);
+         StorageLive(_69);
+         _69 = move _183;
+         goto -> bb68;
      }
  
      bb156: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb156, unwind: bb155];
+         StorageLive(_17);
+         StorageLive(_79);
+         _79 = move _183;
+         goto -> bb79;
      }
  
      bb157: {
-         _2 = move _113;
-         StorageDead(_113);
-         goto -> bb156;
+         StorageLive(_17);
+         StorageLive(_86);
+         _86 = move _183;
+         goto -> bb80;
      }
  
      bb158: {
-         _2 = move _113;
-         StorageDead(_113);
-         goto -> bb163;
+         StorageLive(_96);
+         _96 = move _183;
+         goto -> bb91;
      }
  
      bb159: {
-         StorageLive(_113);
-         _113 = yield(const ()) -> [resume: bb157, drop: bb158];
+         StorageLive(_103);
+         _103 = move _183;
+         goto -> bb92;
      }
  
      bb160: {
-         _115 = discriminant(_114);
-         switchInt(move _115) -> [0: bb154, 1: bb159, otherwise: bb59];
+         StorageLive(_113);
+         _113 = move _183;
+         goto -> bb103;
      }
  
      bb161: {
-         _114 = <impl Future<Output = ()> as Future>::poll(move _116, move _117) -> [return: bb160, unwind: bb155];
+         StorageLive(_120);
+         _120 = move _183;
+         goto -> bb104;
      }
  
      bb162: {
-         _118 = move _2;
-         _117 = std::future::get_context::<'_, '_>(move _118) -> [return: bb161, unwind: bb155];
+         StorageLive(_130);
+         _130 = move _183;
+         goto -> bb115;
      }
  
      bb163: {
-         _119 = &mut _112;
-         _116 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _119) -> [return: bb162, unwind: bb155];
+         StorageLive(_137);
+         _137 = move _183;
+         goto -> bb116;
      }
  
      bb164: {
-         _2 = move _120;
-         StorageDead(_120);
-         goto -> bb170;
+         StorageLive(_147);
+         _147 = move _183;
+         goto -> bb127;
      }
  
      bb165: {
-         _2 = move _120;
-         StorageDead(_120);
-         goto -> bb163;
+         StorageLive(_154);
+         _154 = move _183;
+         goto -> bb128;
      }
  
      bb166: {
-         StorageLive(_120);
-         _120 = yield(const ()) -> [resume: bb164, drop: bb165];
+         StorageLive(_164);
+         _164 = move _183;
+         goto -> bb139;
      }
  
      bb167: {
-         _122 = discriminant(_121);
-         switchInt(move _122) -> [0: bb153, 1: bb166, otherwise: bb59];
+         StorageLive(_171);
+         _171 = move _183;
+         goto -> bb140;
      }
  
      bb168: {
-         _121 = <impl Future<Output = ()> as Future>::poll(move _123, move _124) -> [return: bb167, unwind: bb155];
+         assert(const false, "`async fn` resumed after panicking") -> [success: bb168, unwind continue];
      }
  
      bb169: {
-         _125 = move _2;
-         _124 = std::future::get_context::<'_, '_>(move _125) -> [return: bb168, unwind: bb155];
+         assert(const false, "`async fn` resumed after completion") -> [success: bb169, unwind continue];
      }
  
      bb170: {
-         _126 = &mut _112;
-         _123 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _126) -> [return: bb169, unwind: bb155];
-     }
- 
-     bb171: {
-         StorageLive(_112);
-         _112 = async_drop_in_place::<SyncThenAsync>(copy (_127.0: &mut SyncThenAsync)) -> [return: bb170, unwind: bb155];
-     }
- 
-     bb172: {
-         _128 = &mut _11;
-         _127 = Pin::<&mut SyncThenAsync>::new_unchecked(move _128) -> [return: bb171, unwind: bb46];
-     }
- 
-     bb173: {
-         StorageDead(_129);
-         goto -> bb18;
-     }
- 
-     bb174: {
-         StorageDead(_129);
-         goto -> bb31;
-     }
- 
-     bb175 (cleanup): {
-         StorageDead(_129);
-         goto -> bb47;
-     }
- 
-     bb176: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb176, unwind: bb175];
-     }
- 
-     bb177: {
-         _2 = move _130;
-         StorageDead(_130);
-         goto -> bb176;
-     }
- 
-     bb178: {
-         _2 = move _130;
-         StorageDead(_130);
-         goto -> bb183;
-     }
- 
-     bb179: {
-         StorageLive(_130);
-         _130 = yield(const ()) -> [resume: bb177, drop: bb178];
-     }
- 
-     bb180: {
-         _132 = discriminant(_131);
-         switchInt(move _132) -> [0: bb174, 1: bb179, otherwise: bb59];
-     }
- 
-     bb181: {
-         _131 = <impl Future<Output = ()> as Future>::poll(move _133, move _134) -> [return: bb180, unwind: bb175];
-     }
- 
-     bb182: {
-         _135 = move _2;
-         _134 = std::future::get_context::<'_, '_>(move _135) -> [return: bb181, unwind: bb175];
-     }
- 
-     bb183: {
-         _136 = &mut _129;
-         _133 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _136) -> [return: bb182, unwind: bb175];
-     }
- 
-     bb184: {
-         _2 = move _137;
-         StorageDead(_137);
-         goto -> bb190;
-     }
- 
-     bb185: {
-         _2 = move _137;
-         StorageDead(_137);
-         goto -> bb183;
-     }
- 
-     bb186: {
-         StorageLive(_137);
-         _137 = yield(const ()) -> [resume: bb184, drop: bb185];
-     }
- 
-     bb187: {
-         _139 = discriminant(_138);
-         switchInt(move _139) -> [0: bb173, 1: bb186, otherwise: bb59];
-     }
- 
-     bb188: {
-         _138 = <impl Future<Output = ()> as Future>::poll(move _140, move _141) -> [return: bb187, unwind: bb175];
-     }
- 
-     bb189: {
-         _142 = move _2;
-         _141 = std::future::get_context::<'_, '_>(move _142) -> [return: bb188, unwind: bb175];
-     }
- 
-     bb190: {
-         _143 = &mut _129;
-         _140 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _143) -> [return: bb189, unwind: bb175];
-     }
- 
-     bb191: {
-         StorageLive(_129);
-         _129 = async_drop_in_place::<AsyncStruct>(copy (_144.0: &mut AsyncStruct)) -> [return: bb190, unwind: bb175];
-     }
- 
-     bb192: {
-         _145 = &mut _8;
-         _144 = Pin::<&mut AsyncStruct>::new_unchecked(move _145) -> [return: bb191, unwind: bb47];
-     }
- 
-     bb193: {
-         StorageDead(_146);
-         goto -> bb19;
-     }
- 
-     bb194: {
-         StorageDead(_146);
-         goto -> bb32;
-     }
- 
-     bb195 (cleanup): {
-         StorageDead(_146);
-         goto -> bb48;
-     }
- 
-     bb196: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb196, unwind: bb195];
-     }
- 
-     bb197: {
-         _2 = move _147;
-         StorageDead(_147);
-         goto -> bb196;
-     }
- 
-     bb198: {
-         _2 = move _147;
-         StorageDead(_147);
-         goto -> bb203;
-     }
- 
-     bb199: {
-         StorageLive(_147);
-         _147 = yield(const ()) -> [resume: bb197, drop: bb198];
-     }
- 
-     bb200: {
-         _149 = discriminant(_148);
-         switchInt(move _149) -> [0: bb194, 1: bb199, otherwise: bb59];
-     }
- 
-     bb201: {
-         _148 = <impl Future<Output = ()> as Future>::poll(move _150, move _151) -> [return: bb200, unwind: bb195];
-     }
- 
-     bb202: {
-         _152 = move _2;
-         _151 = std::future::get_context::<'_, '_>(move _152) -> [return: bb201, unwind: bb195];
-     }
- 
-     bb203: {
-         _153 = &mut _146;
-         _150 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _153) -> [return: bb202, unwind: bb195];
-     }
- 
-     bb204: {
-         _2 = move _154;
-         StorageDead(_154);
-         goto -> bb210;
-     }
- 
-     bb205: {
-         _2 = move _154;
-         StorageDead(_154);
-         goto -> bb203;
-     }
- 
-     bb206: {
-         StorageLive(_154);
-         _154 = yield(const ()) -> [resume: bb204, drop: bb205];
-     }
- 
-     bb207: {
-         _156 = discriminant(_155);
-         switchInt(move _156) -> [0: bb193, 1: bb206, otherwise: bb59];
-     }
- 
-     bb208: {
-         _155 = <impl Future<Output = ()> as Future>::poll(move _157, move _158) -> [return: bb207, unwind: bb195];
-     }
- 
-     bb209: {
-         _159 = move _2;
-         _158 = std::future::get_context::<'_, '_>(move _159) -> [return: bb208, unwind: bb195];
-     }
- 
-     bb210: {
-         _160 = &mut _146;
-         _157 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _160) -> [return: bb209, unwind: bb195];
-     }
- 
-     bb211: {
-         StorageLive(_146);
-         _146 = async_drop_in_place::<[AsyncInt; 2]>(copy (_161.0: &mut [AsyncInt; 2])) -> [return: bb210, unwind: bb195];
-     }
- 
-     bb212: {
-         _162 = &mut _5;
-         _161 = Pin::<&mut [AsyncInt; 2]>::new_unchecked(move _162) -> [return: bb211, unwind: bb48];
-     }
- 
-     bb213: {
-         StorageDead(_163);
-         goto -> bb20;
-     }
- 
-     bb214: {
-         StorageDead(_163);
-         goto -> bb33;
-     }
- 
-     bb215 (cleanup): {
-         StorageDead(_163);
-         goto -> bb49;
-     }
- 
-     bb216: {
-         assert(const false, "`async fn` resumed after async drop") -> [success: bb216, unwind: bb215];
-     }
- 
-     bb217: {
-         _2 = move _164;
-         StorageDead(_164);
-         goto -> bb216;
-     }
- 
-     bb218: {
-         _2 = move _164;
-         StorageDead(_164);
-         goto -> bb223;
-     }
- 
-     bb219: {
-         StorageLive(_164);
-         _164 = yield(const ()) -> [resume: bb217, drop: bb218];
-     }
- 
-     bb220: {
-         _166 = discriminant(_165);
-         switchInt(move _166) -> [0: bb214, 1: bb219, otherwise: bb59];
-     }
- 
-     bb221: {
-         _165 = <impl Future<Output = ()> as Future>::poll(move _167, move _168) -> [return: bb220, unwind: bb215];
-     }
- 
-     bb222: {
-         _169 = move _2;
-         _168 = std::future::get_context::<'_, '_>(move _169) -> [return: bb221, unwind: bb215];
-     }
- 
-     bb223: {
-         _170 = &mut _163;
-         _167 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _170) -> [return: bb222, unwind: bb215];
-     }
- 
-     bb224: {
-         _2 = move _171;
-         StorageDead(_171);
-         goto -> bb230;
-     }
- 
-     bb225: {
-         _2 = move _171;
-         StorageDead(_171);
-         goto -> bb223;
-     }
- 
-     bb226: {
-         StorageLive(_171);
-         _171 = yield(const ()) -> [resume: bb224, drop: bb225];
-     }
- 
-     bb227: {
-         _173 = discriminant(_172);
-         switchInt(move _173) -> [0: bb213, 1: bb226, otherwise: bb59];
-     }
- 
-     bb228: {
-         _172 = <impl Future<Output = ()> as Future>::poll(move _174, move _175) -> [return: bb227, unwind: bb215];
-     }
- 
-     bb229: {
-         _176 = move _2;
-         _175 = std::future::get_context::<'_, '_>(move _176) -> [return: bb228, unwind: bb215];
-     }
- 
-     bb230: {
-         _177 = &mut _163;
-         _174 = Pin::<&mut impl Future<Output = ()>>::new_unchecked(move _177) -> [return: bb229, unwind: bb215];
-     }
- 
-     bb231: {
-         StorageLive(_163);
-         _163 = async_drop_in_place::<AsyncInt>(copy (_178.0: &mut AsyncInt)) -> [return: bb230, unwind: bb215];
-     }
- 
-     bb232: {
-         _179 = &mut _4;
-         _178 = Pin::<&mut AsyncInt>::new_unchecked(move _179) -> [return: bb231, unwind: bb49];
+         nop;
+         (((*_182) as variant#20).1: SyncInt) = SyncInt(const 0_i32);
+         nop;
+         (((*_182) as variant#20).2: AsyncInt) = AsyncInt(const 0_i32);
+         nop;
+         StorageLive(_6);
+         _6 = AsyncInt(const 1_i32);
+         StorageLive(_7);
+         _7 = AsyncInt(const 2_i32);
+         (((*_182) as variant#18).3: [AsyncInt; 2]) = [move _6, move _7];
+         goto -> bb1;
      }
  }
  
