- // MIR for `double::{closure#0}` before ElaborateDrops
+ // MIR for `double::{closure#0}` after ElaborateDrops
  
  fn double::{closure#0}(_1: {async fn body of double()}, _2: std::future::ResumeTy) -> ()
  yields ()
   {
      debug _task_context => _2;
      let mut _0: ();
      let _3: SyncInt;
+     let mut _6: impl std::future::Future<Output = ()>;
+     let mut _7: std::pin::Pin<&mut AsyncInt>;
+     let mut _8: &mut AsyncInt;
+     let mut _9: impl std::future::Future<Output = ()>;
+     let mut _10: std::pin::Pin<&mut AsyncInt>;
+     let mut _11: &mut AsyncInt;
+     let mut _12: impl std::future::Future<Output = ()>;
+     let mut _13: std::pin::Pin<&mut {async fn body of double()}>;
+     let mut _14: &mut {async fn body of double()};
      scope 1 {
          debug sync_int => _3;
          let _4: AsyncInt;
          scope 2 {
              debug async_int => _4;
              let _5: AsyncInt;
              scope 3 {
                  debug async_int_again => _5;
              }
          }
      }
  
      bb0: {
          StorageLive(_3);
          _3 = SyncInt(const 0_i32);
          StorageLive(_4);
          _4 = AsyncInt(const 0_i32);
          StorageLive(_5);
          _5 = AsyncInt(const 0_i32);
          _0 = const ();
-         drop(_5) -> [return: bb1, unwind: bb9, drop: bb5];
+         goto -> bb20;
      }
  
      bb1: {
          StorageDead(_5);
-         drop(_4) -> [return: bb2, unwind: bb10, drop: bb6];
+         goto -> bb26;
      }
  
      bb2: {
          StorageDead(_4);
          drop(_3) -> [return: bb3, unwind: bb11];
      }
  
      bb3: {
          StorageDead(_3);
-         drop(_1) -> [return: bb4, drop: bb8, unwind continue];
+         goto -> bb32;
      }
  
      bb4: {
          return;
      }
  
      bb5: {
          StorageDead(_5);
-         drop(_4) -> [return: bb6, unwind: bb13];
+         goto -> bb6;
      }
  
      bb6: {
          StorageDead(_4);
-         drop(_3) -> [return: bb7, unwind: bb14];
+         goto -> bb7;
      }
  
      bb7: {
          StorageDead(_3);
-         drop(_1) -> [return: bb8, unwind continue];
+         goto -> bb8;
      }
  
      bb8: {
          coroutine_drop;
      }
  
      bb9 (cleanup): {
          StorageDead(_5);
          drop(_4) -> [return: bb10, unwind terminate(cleanup)];
      }
  
      bb10 (cleanup): {
          StorageDead(_4);
          drop(_3) -> [return: bb11, unwind terminate(cleanup)];
      }
  
      bb11 (cleanup): {
          StorageDead(_3);
          drop(_1) -> [return: bb12, unwind terminate(cleanup)];
      }
  
      bb12 (cleanup): {
          resume;
      }
  
      bb13 (cleanup): {
          StorageDead(_4);
-         drop(_3) -> [return: bb14, unwind terminate(cleanup)];
+         goto -> bb14;
      }
  
      bb14 (cleanup): {
          StorageDead(_3);
-         drop(_1) -> [return: bb12, unwind terminate(cleanup)];
+         goto -> bb12;
+     }
+ 
+     bb15: {
+         StorageDead(_6);
+         goto -> bb1;
+     }
+ 
+     bb16: {
+         StorageDead(_6);
+         goto -> bb5;
+     }
+ 
+     bb17 (cleanup): {
+         StorageDead(_6);
+         goto -> bb9;
+     }
+ 
+     bb18: {
+         async drop(_5; poll=_6) -> [return: bb15, unwind: bb17, drop: bb16];
+     }
+ 
+     bb19: {
+         StorageLive(_6);
+         _6 = async_drop_in_place::<AsyncInt>(copy (_7.0: &mut AsyncInt)) -> [return: bb18, unwind: bb17];
+     }
+ 
+     bb20: {
+         _8 = &mut _5;
+         _7 = Pin::<&mut AsyncInt>::new_unchecked(move _8) -> [return: bb19, unwind: bb9];
+     }
+ 
+     bb21: {
+         StorageDead(_9);
+         goto -> bb2;
+     }
+ 
+     bb22: {
+         StorageDead(_9);
+         goto -> bb6;
+     }
+ 
+     bb23 (cleanup): {
+         StorageDead(_9);
+         goto -> bb10;
+     }
+ 
+     bb24: {
+         async drop(_4; poll=_9) -> [return: bb21, unwind: bb23, drop: bb22];
+     }
+ 
+     bb25: {
+         StorageLive(_9);
+         _9 = async_drop_in_place::<AsyncInt>(copy (_10.0: &mut AsyncInt)) -> [return: bb24, unwind: bb23];
+     }
+ 
+     bb26: {
+         _11 = &mut _4;
+         _10 = Pin::<&mut AsyncInt>::new_unchecked(move _11) -> [return: bb25, unwind: bb10];
+     }
+ 
+     bb27: {
+         StorageDead(_12);
+         goto -> bb4;
+     }
+ 
+     bb28: {
+         StorageDead(_12);
+         goto -> bb8;
+     }
+ 
+     bb29 (cleanup): {
+         StorageDead(_12);
+         goto -> bb12;
+     }
+ 
+     bb30: {
+         async drop(_1; poll=_12) -> [return: bb27, unwind: bb29, drop: bb28];
+     }
+ 
+     bb31: {
+         StorageLive(_12);
+         _12 = async_drop_in_place::<{async fn body of double()}>(copy (_13.0: &mut {async fn body of double()})) -> [return: bb30, unwind: bb29];
+     }
+ 
+     bb32: {
+         _14 = &mut _1;
+         _13 = Pin::<&mut {async fn body of double()}>::new_unchecked(move _14) -> [return: bb31, unwind: bb12];
      }
  }
  
