- // MIR for `elaborate_drops::{closure#0}` before ElaborateDrops
+ // MIR for `elaborate_drops::{closure#0}` after ElaborateDrops
  
  fn elaborate_drops::{closure#0}(_1: {async fn body of elaborate_drops()}, _2: std::future::ResumeTy) -> ()
  yields ()
   {
      debug _task_context => _2;
      let mut _0: ();
      let _3: SyncInt;
      let mut _6: AsyncInt;
      let mut _7: AsyncInt;
      let mut _9: AsyncInt;
      let mut _10: AsyncInt;
      let mut _12: AsyncInt;
      let mut _13: SyncInt;
      let mut _14: AsyncInt;
      let mut _16: AsyncInt;
      let mut _18: AsyncInt;
      let mut _21: &AsyncInt;
      let _22: &AsyncInt;
+     let mut _27: impl std::future::Future<Output = ()>;
+     let mut _28: std::pin::Pin<&mut {async closure@$DIR/async_drop.rs:80:27: 80:35}>;
+     let mut _29: &mut {async closure@$DIR/async_drop.rs:80:27: 80:35};
+     let mut _30: impl std::future::Future<Output = ()>;
+     let mut _31: std::pin::Pin<&mut {closure@$DIR/async_drop.rs:72:25: 72:27}>;
+     let mut _32: &mut {closure@$DIR/async_drop.rs:72:25: 72:27};
+     let mut _33: impl std::future::Future<Output = ()>;
+     let mut _34: std::pin::Pin<&mut AsyncReference<'_>>;
+     let mut _35: &mut AsyncReference<'_>;
+     let mut _36: impl std::future::Future<Output = ()>;
+     let mut _37: std::pin::Pin<&mut AsyncInt>;
+     let mut _38: &mut AsyncInt;
+     let mut _39: impl std::future::Future<Output = ()>;
+     let mut _40: std::pin::Pin<&mut AsyncEnum>;
+     let mut _41: &mut AsyncEnum;
+     let mut _42: impl std::future::Future<Output = ()>;
+     let mut _43: std::pin::Pin<&mut SyncThenAsync>;
+     let mut _44: &mut SyncThenAsync;
+     let mut _45: impl std::future::Future<Output = ()>;
+     let mut _46: std::pin::Pin<&mut AsyncStruct>;
+     let mut _47: &mut AsyncStruct;
+     let mut _48: impl std::future::Future<Output = ()>;
+     let mut _49: std::pin::Pin<&mut [AsyncInt; 2]>;
+     let mut _50: &mut [AsyncInt; 2];
+     let mut _51: impl std::future::Future<Output = ()>;
+     let mut _52: std::pin::Pin<&mut AsyncInt>;
+     let mut _53: &mut AsyncInt;
+     let mut _54: impl std::future::Future<Output = ()>;
+     let mut _55: std::pin::Pin<&mut {async fn body of elaborate_drops()}>;
+     let mut _56: &mut {async fn body of elaborate_drops()};
      scope 1 {
          debug sync_int => _3;
          let _4: AsyncInt;
          scope 2 {
              debug async_int => _4;
              let _5: [AsyncInt; 2];
              scope 3 {
                  debug tuple => _5;
                  let _8: AsyncStruct;
                  scope 4 {
                      debug async_struct => _8;
                      let _11: SyncThenAsync;
                      scope 5 {
                          debug async_struct_mix => _11;
                          let _15: AsyncEnum;
                          scope 6 {
                              debug async_enum => _15;
                              let _17: std::mem::ManuallyDrop<AsyncInt>;
                              scope 7 {
                                  debug manually_drop_async_int => _17;
                                  let _19: AsyncInt;
                                  scope 8 {
                                      debug foo => _19;
                                      let _20: AsyncReference<'_>;
                                      scope 9 {
                                          debug async_ref => _20;
                                          let _23: AsyncInt;
                                          scope 10 {
                                              debug foo => _23;
                                              let _24: {closure@$DIR/async_drop.rs:72:25: 72:27};
                                              scope 11 {
                                                  debug async_closure => _24;
                                                  let _25: AsyncInt;
                                                  scope 12 {
                                                      debug foo => _25;
                                                      let _26: {async closure@$DIR/async_drop.rs:80:27: 80:35};
                                                      scope 13 {
                                                          debug async_coroutine => _26;
                                                      }
                                                  }
                                              }
                                          }
                                      }
                                  }
                              }
                          }
                      }
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_3);
          _3 = SyncInt(const 0_i32);
          StorageLive(_4);
          _4 = AsyncInt(const 0_i32);
          StorageLive(_5);
          StorageLive(_6);
          _6 = AsyncInt(const 1_i32);
          StorageLive(_7);
          _7 = AsyncInt(const 2_i32);
          _5 = [move _6, move _7];
-         drop(_7) -> [return: bb1, unwind: bb62, drop: bb38];
+         goto -> bb1;
      }
  
      bb1: {
          StorageDead(_7);
-         drop(_6) -> [return: bb2, unwind: bb63, drop: bb39];
+         goto -> bb2;
      }
  
      bb2: {
          StorageDead(_6);
          StorageLive(_8);
          StorageLive(_9);
          _9 = AsyncInt(const 5_i32);
          StorageLive(_10);
          _10 = AsyncInt(const 4_i32);
          _8 = AsyncStruct { i: const 3_i32, a: move _10, b: move _9 };
-         drop(_10) -> [return: bb3, unwind: bb59, drop: bb35];
+         goto -> bb3;
      }
  
      bb3: {
          StorageDead(_10);
-         drop(_9) -> [return: bb4, unwind: bb60, drop: bb36];
+         goto -> bb4;
      }
  
      bb4: {
          StorageDead(_9);
          StorageLive(_11);
          StorageLive(_12);
          _12 = AsyncInt(const 7_i32);
          StorageLive(_13);
          _13 = SyncInt(const 8_i32);
          StorageLive(_14);
          _14 = AsyncInt(const 9_i32);
          _11 = SyncThenAsync { i: const 6_i32, a: move _12, b: move _13, c: move _14 };
-         drop(_14) -> [return: bb5, unwind: bb55, drop: bb31];
+         goto -> bb5;
      }
  
      bb5: {
          StorageDead(_14);
-         drop(_13) -> [return: bb6, unwind: bb56];
+         goto -> bb6;
      }
  
      bb6: {
          StorageDead(_13);
-         drop(_12) -> [return: bb7, unwind: bb57, drop: bb33];
+         goto -> bb7;
      }
  
      bb7: {
          StorageDead(_12);
          StorageLive(_15);
          StorageLive(_16);
          _16 = AsyncInt(const 10_i32);
          _15 = AsyncEnum::A(move _16);
-         drop(_16) -> [return: bb8, unwind: bb53, drop: bb29];
+         goto -> bb8;
      }
  
      bb8: {
          StorageDead(_16);
          StorageLive(_17);
          StorageLive(_18);
          _18 = AsyncInt(const 11_i32);
          _17 = ManuallyDrop::<AsyncInt>::new(move _18) -> [return: bb9, unwind: bb50];
      }
  
      bb9: {
          StorageDead(_18);
          StorageLive(_19);
          _19 = AsyncInt(const 12_i32);
          StorageLive(_20);
          StorageLive(_21);
          StorageLive(_22);
          _22 = &_19;
          _21 = &(*_22);
          _20 = AsyncReference::<'_> { foo: move _21 };
          StorageDead(_21);
          StorageDead(_22);
          StorageLive(_23);
          _23 = AsyncInt(const 14_i32);
          StorageLive(_24);
          _24 = {closure@$DIR/async_drop.rs:72:25: 72:27} { foo: move _23 };
          StorageLive(_25);
          _25 = AsyncInt(const 15_i32);
          StorageLive(_26);
          _26 = {closure@$DIR/async_drop.rs:80:27: 80:35} { foo: move _25 };
          _0 = const ();
-         drop(_26) -> [return: bb10, unwind: bb44, drop: bb23];
+         goto -> bb88;
      }
  
      bb10: {
          StorageDead(_26);
-         drop(_25) -> [return: bb11, unwind: bb45, drop: bb24];
+         goto -> bb11;
      }
  
      bb11: {
          StorageDead(_25);
-         drop(_24) -> [return: bb12, unwind: bb46, drop: bb25];
+         goto -> bb94;
      }
  
      bb12: {
          StorageDead(_24);
-         drop(_23) -> [return: bb13, unwind: bb47, drop: bb26];
+         goto -> bb13;
      }
  
      bb13: {
          StorageDead(_23);
-         drop(_20) -> [return: bb14, unwind: bb48, drop: bb27];
+         goto -> bb100;
      }
  
      bb14: {
          StorageDead(_20);
-         drop(_19) -> [return: bb15, unwind: bb49, drop: bb28];
+         goto -> bb106;
      }
  
      bb15: {
          StorageDead(_19);
          StorageDead(_17);
-         drop(_15) -> [return: bb16, unwind: bb54, drop: bb30];
+         goto -> bb112;
      }
  
      bb16: {
          StorageDead(_15);
-         drop(_11) -> [return: bb17, unwind: bb58, drop: bb34];
+         goto -> bb118;
      }
  
      bb17: {
          StorageDead(_11);
-         drop(_8) -> [return: bb18, unwind: bb61, drop: bb37];
+         goto -> bb124;
      }
  
      bb18: {
          StorageDead(_8);
-         drop(_5) -> [return: bb19, unwind: bb64, drop: bb40];
+         goto -> bb130;
      }
  
      bb19: {
          StorageDead(_5);
-         drop(_4) -> [return: bb20, unwind: bb65, drop: bb41];
+         goto -> bb136;
      }
  
      bb20: {
          StorageDead(_4);
          drop(_3) -> [return: bb21, unwind: bb66];
      }
  
      bb21: {
          StorageDead(_3);
-         drop(_1) -> [return: bb22, drop: bb43, unwind continue];
+         goto -> bb142;
      }
  
      bb22: {
          return;
      }
  
      bb23: {
          StorageDead(_26);
-         drop(_25) -> [return: bb24, unwind: bb68];
+         goto -> bb24;
      }
  
      bb24: {
          StorageDead(_25);
-         drop(_24) -> [return: bb25, unwind: bb69];
+         goto -> bb25;
      }
  
      bb25: {
          StorageDead(_24);
-         drop(_23) -> [return: bb26, unwind: bb70];
+         goto -> bb26;
      }
  
      bb26: {
          StorageDead(_23);
-         drop(_20) -> [return: bb27, unwind: bb71];
+         goto -> bb27;
      }
  
      bb27: {
          StorageDead(_20);
-         drop(_19) -> [return: bb28, unwind: bb72];
+         goto -> bb28;
      }
  
      bb28: {
          StorageDead(_19);
          StorageDead(_17);
-         drop(_15) -> [return: bb30, unwind: bb73];
+         goto -> bb30;
      }
  
      bb29: {
          StorageDead(_16);
          goto -> bb30;
      }
  
      bb30: {
          StorageDead(_15);
-         drop(_11) -> [return: bb34, unwind: bb76];
+         goto -> bb34;
      }
  
      bb31: {
          StorageDead(_14);
-         drop(_13) -> [return: bb32, unwind: bb74];
+         goto -> bb32;
      }
  
      bb32: {
          StorageDead(_13);
-         drop(_12) -> [return: bb33, unwind: bb75];
+         goto -> bb33;
      }
  
      bb33: {
          StorageDead(_12);
          goto -> bb34;
      }
  
      bb34: {
          StorageDead(_11);
-         drop(_8) -> [return: bb37, unwind: bb78];
+         goto -> bb37;
      }
  
      bb35: {
          StorageDead(_10);
-         drop(_9) -> [return: bb36, unwind: bb77];
+         goto -> bb36;
      }
  
      bb36: {
          StorageDead(_9);
          goto -> bb37;
      }
  
      bb37: {
          StorageDead(_8);
-         drop(_5) -> [return: bb40, unwind: bb80];
+         goto -> bb40;
      }
  
      bb38: {
          StorageDead(_7);
-         drop(_6) -> [return: bb39, unwind: bb79];
+         goto -> bb39;
      }
  
      bb39: {
          StorageDead(_6);
          goto -> bb40;
      }
  
      bb40: {
          StorageDead(_5);
-         drop(_4) -> [return: bb41, unwind: bb81];
+         goto -> bb41;
      }
  
      bb41: {
          StorageDead(_4);
-         drop(_3) -> [return: bb42, unwind: bb82];
+         goto -> bb42;
      }
  
      bb42: {
          StorageDead(_3);
-         drop(_1) -> [return: bb43, unwind continue];
+         goto -> bb43;
      }
  
      bb43: {
          coroutine_drop;
      }
  
      bb44 (cleanup): {
          StorageDead(_26);
-         drop(_25) -> [return: bb45, unwind terminate(cleanup)];
+         goto -> bb45;
      }
  
      bb45 (cleanup): {
          StorageDead(_25);
          drop(_24) -> [return: bb46, unwind terminate(cleanup)];
      }
  
      bb46 (cleanup): {
          StorageDead(_24);
-         drop(_23) -> [return: bb47, unwind terminate(cleanup)];
+         goto -> bb47;
      }
  
      bb47 (cleanup): {
          StorageDead(_23);
          drop(_20) -> [return: bb48, unwind terminate(cleanup)];
      }
  
      bb48 (cleanup): {
          StorageDead(_20);
          drop(_19) -> [return: bb49, unwind terminate(cleanup)];
      }
  
      bb49 (cleanup): {
          StorageDead(_19);
          goto -> bb52;
      }
  
      bb50 (cleanup): {
-         drop(_18) -> [return: bb51, unwind terminate(cleanup)];
+         goto -> bb51;
      }
  
      bb51 (cleanup): {
          StorageDead(_18);
          goto -> bb52;
      }
  
      bb52 (cleanup): {
          StorageDead(_17);
          drop(_15) -> [return: bb54, unwind terminate(cleanup)];
      }
  
      bb53 (cleanup): {
          StorageDead(_16);
          goto -> bb54;
      }
  
      bb54 (cleanup): {
          StorageDead(_15);
          drop(_11) -> [return: bb58, unwind terminate(cleanup)];
      }
  
      bb55 (cleanup): {
          StorageDead(_14);
-         drop(_13) -> [return: bb56, unwind terminate(cleanup)];
+         goto -> bb56;
      }
  
      bb56 (cleanup): {
          StorageDead(_13);
-         drop(_12) -> [return: bb57, unwind terminate(cleanup)];
+         goto -> bb57;
      }
  
      bb57 (cleanup): {
          StorageDead(_12);
          goto -> bb58;
      }
  
      bb58 (cleanup): {
          StorageDead(_11);
          drop(_8) -> [return: bb61, unwind terminate(cleanup)];
      }
  
      bb59 (cleanup): {
          StorageDead(_10);
-         drop(_9) -> [return: bb60, unwind terminate(cleanup)];
+         goto -> bb60;
      }
  
      bb60 (cleanup): {
          StorageDead(_9);
          goto -> bb61;
      }
  
      bb61 (cleanup): {
          StorageDead(_8);
          drop(_5) -> [return: bb64, unwind terminate(cleanup)];
      }
  
      bb62 (cleanup): {
          StorageDead(_7);
-         drop(_6) -> [return: bb63, unwind terminate(cleanup)];
+         goto -> bb63;
      }
  
      bb63 (cleanup): {
          StorageDead(_6);
          goto -> bb64;
      }
  
      bb64 (cleanup): {
          StorageDead(_5);
          drop(_4) -> [return: bb65, unwind terminate(cleanup)];
      }
  
      bb65 (cleanup): {
          StorageDead(_4);
          drop(_3) -> [return: bb66, unwind terminate(cleanup)];
      }
  
      bb66 (cleanup): {
          StorageDead(_3);
          drop(_1) -> [return: bb67, unwind terminate(cleanup)];
      }
  
      bb67 (cleanup): {
          resume;
      }
  
      bb68 (cleanup): {
          StorageDead(_25);
-         drop(_24) -> [return: bb69, unwind terminate(cleanup)];
+         goto -> bb69;
      }
  
      bb69 (cleanup): {
          StorageDead(_24);
-         drop(_23) -> [return: bb70, unwind terminate(cleanup)];
+         goto -> bb70;
      }
  
      bb70 (cleanup): {
          StorageDead(_23);
-         drop(_20) -> [return: bb71, unwind terminate(cleanup)];
+         goto -> bb71;
      }
  
      bb71 (cleanup): {
          StorageDead(_20);
-         drop(_19) -> [return: bb72, unwind terminate(cleanup)];
+         goto -> bb72;
      }
  
      bb72 (cleanup): {
          StorageDead(_19);
          StorageDead(_17);
-         drop(_15) -> [return: bb73, unwind terminate(cleanup)];
+         goto -> bb73;
      }
  
      bb73 (cleanup): {
          StorageDead(_15);
-         drop(_11) -> [return: bb76, unwind terminate(cleanup)];
+         goto -> bb76;
      }
  
      bb74 (cleanup): {
          StorageDead(_13);
-         drop(_12) -> [return: bb75, unwind terminate(cleanup)];
+         goto -> bb75;
      }
  
      bb75 (cleanup): {
          StorageDead(_12);
          goto -> bb76;
      }
  
      bb76 (cleanup): {
          StorageDead(_11);
-         drop(_8) -> [return: bb78, unwind terminate(cleanup)];
+         goto -> bb78;
      }
  
      bb77 (cleanup): {
          StorageDead(_9);
          goto -> bb78;
      }
  
      bb78 (cleanup): {
          StorageDead(_8);
-         drop(_5) -> [return: bb80, unwind terminate(cleanup)];
+         goto -> bb80;
      }
  
      bb79 (cleanup): {
          StorageDead(_6);
          goto -> bb80;
      }
  
      bb80 (cleanup): {
          StorageDead(_5);
-         drop(_4) -> [return: bb81, unwind terminate(cleanup)];
+         goto -> bb81;
      }
  
      bb81 (cleanup): {
          StorageDead(_4);
-         drop(_3) -> [return: bb82, unwind terminate(cleanup)];
+         goto -> bb82;
      }
  
      bb82 (cleanup): {
          StorageDead(_3);
-         drop(_1) -> [return: bb67, unwind terminate(cleanup)];
+         goto -> bb67;
+     }
+ 
+     bb83: {
+         StorageDead(_27);
+         goto -> bb10;
+     }
+ 
+     bb84: {
+         StorageDead(_27);
+         goto -> bb23;
+     }
+ 
+     bb85 (cleanup): {
+         StorageDead(_27);
+         goto -> bb44;
+     }
+ 
+     bb86: {
+         async drop(_26; poll=_27) -> [return: bb83, unwind: bb85, drop: bb84];
+     }
+ 
+     bb87: {
+         StorageLive(_27);
+         _27 = async_drop_in_place::<{async closure@$DIR/async_drop.rs:80:27: 80:35}>(copy (_28.0: &mut {async closure@$DIR/async_drop.rs:80:27: 80:35})) -> [return: bb86, unwind: bb85];
+     }
+ 
+     bb88: {
+         _29 = &mut _26;
+         _28 = Pin::<&mut {async closure@$DIR/async_drop.rs:80:27: 80:35}>::new_unchecked(move _29) -> [return: bb87, unwind: bb44];
+     }
+ 
+     bb89: {
+         StorageDead(_30);
+         goto -> bb12;
+     }
+ 
+     bb90: {
+         StorageDead(_30);
+         goto -> bb25;
+     }
+ 
+     bb91 (cleanup): {
+         StorageDead(_30);
+         goto -> bb46;
+     }
+ 
+     bb92: {
+         async drop(_24; poll=_30) -> [return: bb89, unwind: bb91, drop: bb90];
+     }
+ 
+     bb93: {
+         StorageLive(_30);
+         _30 = async_drop_in_place::<{closure@$DIR/async_drop.rs:72:25: 72:27}>(copy (_31.0: &mut {closure@$DIR/async_drop.rs:72:25: 72:27})) -> [return: bb92, unwind: bb91];
+     }
+ 
+     bb94: {
+         _32 = &mut _24;
+         _31 = Pin::<&mut {closure@$DIR/async_drop.rs:72:25: 72:27}>::new_unchecked(move _32) -> [return: bb93, unwind: bb46];
+     }
+ 
+     bb95: {
+         StorageDead(_33);
+         goto -> bb14;
+     }
+ 
+     bb96: {
+         StorageDead(_33);
+         goto -> bb27;
+     }
+ 
+     bb97 (cleanup): {
+         StorageDead(_33);
+         goto -> bb48;
+     }
+ 
+     bb98: {
+         async drop(_20; poll=_33) -> [return: bb95, unwind: bb97, drop: bb96];
+     }
+ 
+     bb99: {
+         StorageLive(_33);
+         _33 = async_drop_in_place::<AsyncReference<'_>>(copy (_34.0: &mut AsyncReference<'_>)) -> [return: bb98, unwind: bb97];
+     }
+ 
+     bb100: {
+         _35 = &mut _20;
+         _34 = Pin::<&mut AsyncReference<'_>>::new_unchecked(move _35) -> [return: bb99, unwind: bb48];
+     }
+ 
+     bb101: {
+         StorageDead(_36);
+         goto -> bb15;
+     }
+ 
+     bb102: {
+         StorageDead(_36);
+         goto -> bb28;
+     }
+ 
+     bb103 (cleanup): {
+         StorageDead(_36);
+         goto -> bb49;
+     }
+ 
+     bb104: {
+         async drop(_19; poll=_36) -> [return: bb101, unwind: bb103, drop: bb102];
+     }
+ 
+     bb105: {
+         StorageLive(_36);
+         _36 = async_drop_in_place::<AsyncInt>(copy (_37.0: &mut AsyncInt)) -> [return: bb104, unwind: bb103];
+     }
+ 
+     bb106: {
+         _38 = &mut _19;
+         _37 = Pin::<&mut AsyncInt>::new_unchecked(move _38) -> [return: bb105, unwind: bb49];
+     }
+ 
+     bb107: {
+         StorageDead(_39);
+         goto -> bb16;
+     }
+ 
+     bb108: {
+         StorageDead(_39);
+         goto -> bb30;
+     }
+ 
+     bb109 (cleanup): {
+         StorageDead(_39);
+         goto -> bb54;
+     }
+ 
+     bb110: {
+         async drop(_15; poll=_39) -> [return: bb107, unwind: bb109, drop: bb108];
+     }
+ 
+     bb111: {
+         StorageLive(_39);
+         _39 = async_drop_in_place::<AsyncEnum>(copy (_40.0: &mut AsyncEnum)) -> [return: bb110, unwind: bb109];
+     }
+ 
+     bb112: {
+         _41 = &mut _15;
+         _40 = Pin::<&mut AsyncEnum>::new_unchecked(move _41) -> [return: bb111, unwind: bb54];
+     }
+ 
+     bb113: {
+         StorageDead(_42);
+         goto -> bb17;
+     }
+ 
+     bb114: {
+         StorageDead(_42);
+         goto -> bb34;
+     }
+ 
+     bb115 (cleanup): {
+         StorageDead(_42);
+         goto -> bb58;
+     }
+ 
+     bb116: {
+         async drop(_11; poll=_42) -> [return: bb113, unwind: bb115, drop: bb114];
+     }
+ 
+     bb117: {
+         StorageLive(_42);
+         _42 = async_drop_in_place::<SyncThenAsync>(copy (_43.0: &mut SyncThenAsync)) -> [return: bb116, unwind: bb115];
+     }
+ 
+     bb118: {
+         _44 = &mut _11;
+         _43 = Pin::<&mut SyncThenAsync>::new_unchecked(move _44) -> [return: bb117, unwind: bb58];
+     }
+ 
+     bb119: {
+         StorageDead(_45);
+         goto -> bb18;
+     }
+ 
+     bb120: {
+         StorageDead(_45);
+         goto -> bb37;
+     }
+ 
+     bb121 (cleanup): {
+         StorageDead(_45);
+         goto -> bb61;
+     }
+ 
+     bb122: {
+         async drop(_8; poll=_45) -> [return: bb119, unwind: bb121, drop: bb120];
+     }
+ 
+     bb123: {
+         StorageLive(_45);
+         _45 = async_drop_in_place::<AsyncStruct>(copy (_46.0: &mut AsyncStruct)) -> [return: bb122, unwind: bb121];
+     }
+ 
+     bb124: {
+         _47 = &mut _8;
+         _46 = Pin::<&mut AsyncStruct>::new_unchecked(move _47) -> [return: bb123, unwind: bb61];
+     }
+ 
+     bb125: {
+         StorageDead(_48);
+         goto -> bb19;
+     }
+ 
+     bb126: {
+         StorageDead(_48);
+         goto -> bb40;
+     }
+ 
+     bb127 (cleanup): {
+         StorageDead(_48);
+         goto -> bb64;
+     }
+ 
+     bb128: {
+         async drop(_5; poll=_48) -> [return: bb125, unwind: bb127, drop: bb126];
+     }
+ 
+     bb129: {
+         StorageLive(_48);
+         _48 = async_drop_in_place::<[AsyncInt; 2]>(copy (_49.0: &mut [AsyncInt; 2])) -> [return: bb128, unwind: bb127];
+     }
+ 
+     bb130: {
+         _50 = &mut _5;
+         _49 = Pin::<&mut [AsyncInt; 2]>::new_unchecked(move _50) -> [return: bb129, unwind: bb64];
+     }
+ 
+     bb131: {
+         StorageDead(_51);
+         goto -> bb20;
+     }
+ 
+     bb132: {
+         StorageDead(_51);
+         goto -> bb41;
+     }
+ 
+     bb133 (cleanup): {
+         StorageDead(_51);
+         goto -> bb65;
+     }
+ 
+     bb134: {
+         async drop(_4; poll=_51) -> [return: bb131, unwind: bb133, drop: bb132];
+     }
+ 
+     bb135: {
+         StorageLive(_51);
+         _51 = async_drop_in_place::<AsyncInt>(copy (_52.0: &mut AsyncInt)) -> [return: bb134, unwind: bb133];
+     }
+ 
+     bb136: {
+         _53 = &mut _4;
+         _52 = Pin::<&mut AsyncInt>::new_unchecked(move _53) -> [return: bb135, unwind: bb65];
+     }
+ 
+     bb137: {
+         StorageDead(_54);
+         goto -> bb22;
+     }
+ 
+     bb138: {
+         StorageDead(_54);
+         goto -> bb43;
+     }
+ 
+     bb139 (cleanup): {
+         StorageDead(_54);
+         goto -> bb67;
+     }
+ 
+     bb140: {
+         async drop(_1; poll=_54) -> [return: bb137, unwind: bb139, drop: bb138];
+     }
+ 
+     bb141: {
+         StorageLive(_54);
+         _54 = async_drop_in_place::<{async fn body of elaborate_drops()}>(copy (_55.0: &mut {async fn body of elaborate_drops()})) -> [return: bb140, unwind: bb139];
+     }
+ 
+     bb142: {
+         _56 = &mut _1;
+         _55 = Pin::<&mut {async fn body of elaborate_drops()}>::new_unchecked(move _56) -> [return: bb141, unwind: bb67];
      }
  }
  
