- // MIR for `simple::{closure#0}` before ElaborateDrops
+ // MIR for `simple::{closure#0}` after ElaborateDrops
  
  fn simple::{closure#0}(_1: {async fn body of simple()}, _2: std::future::ResumeTy) -> ()
  yields ()
   {
      debug _task_context => _2;
      let mut _0: ();
      let _3: SyncInt;
+     let mut _5: impl std::future::Future<Output = ()>;
+     let mut _6: std::pin::Pin<&mut AsyncInt>;
+     let mut _7: &mut AsyncInt;
+     let mut _8: impl std::future::Future<Output = ()>;
+     let mut _9: std::pin::Pin<&mut {async fn body of simple()}>;
+     let mut _10: &mut {async fn body of simple()};
      scope 1 {
          debug sync_int => _3;
          let _4: AsyncInt;
          scope 2 {
              debug async_int => _4;
          }
      }
  
      bb0: {
          StorageLive(_3);
          _3 = SyncInt(const 0_i32);
          StorageLive(_4);
          _4 = AsyncInt(const 0_i32);
          _0 = const ();
-         drop(_4) -> [return: bb1, unwind: bb7, drop: bb4];
+         goto -> bb16;
      }
  
      bb1: {
          StorageDead(_4);
          drop(_3) -> [return: bb2, unwind: bb8];
      }
  
      bb2: {
          StorageDead(_3);
-         drop(_1) -> [return: bb3, drop: bb6, unwind continue];
+         goto -> bb22;
      }
  
      bb3: {
          return;
      }
  
      bb4: {
          StorageDead(_4);
-         drop(_3) -> [return: bb5, unwind: bb10];
+         goto -> bb5;
      }
  
      bb5: {
          StorageDead(_3);
-         drop(_1) -> [return: bb6, unwind continue];
+         goto -> bb6;
      }
  
      bb6: {
          coroutine_drop;
      }
  
      bb7 (cleanup): {
          StorageDead(_4);
          drop(_3) -> [return: bb8, unwind terminate(cleanup)];
      }
  
      bb8 (cleanup): {
          StorageDead(_3);
          drop(_1) -> [return: bb9, unwind terminate(cleanup)];
      }
  
      bb9 (cleanup): {
          resume;
      }
  
      bb10 (cleanup): {
          StorageDead(_3);
-         drop(_1) -> [return: bb9, unwind terminate(cleanup)];
+         goto -> bb9;
+     }
+ 
+     bb11: {
+         StorageDead(_5);
+         goto -> bb1;
+     }
+ 
+     bb12: {
+         StorageDead(_5);
+         goto -> bb4;
+     }
+ 
+     bb13 (cleanup): {
+         StorageDead(_5);
+         goto -> bb7;
+     }
+ 
+     bb14: {
+         async drop(_4; poll=_5) -> [return: bb11, unwind: bb13, drop: bb12];
+     }
+ 
+     bb15: {
+         StorageLive(_5);
+         _5 = async_drop_in_place::<AsyncInt>(copy (_6.0: &mut AsyncInt)) -> [return: bb14, unwind: bb13];
+     }
+ 
+     bb16: {
+         _7 = &mut _4;
+         _6 = Pin::<&mut AsyncInt>::new_unchecked(move _7) -> [return: bb15, unwind: bb7];
+     }
+ 
+     bb17: {
+         StorageDead(_8);
+         goto -> bb3;
+     }
+ 
+     bb18: {
+         StorageDead(_8);
+         goto -> bb6;
+     }
+ 
+     bb19 (cleanup): {
+         StorageDead(_8);
+         goto -> bb9;
+     }
+ 
+     bb20: {
+         async drop(_1; poll=_8) -> [return: bb17, unwind: bb19, drop: bb18];
+     }
+ 
+     bb21: {
+         StorageLive(_8);
+         _8 = async_drop_in_place::<{async fn body of simple()}>(copy (_9.0: &mut {async fn body of simple()})) -> [return: bb20, unwind: bb19];
+     }
+ 
+     bb22: {
+         _10 = &mut _1;
+         _9 = Pin::<&mut {async fn body of simple()}>::new_unchecked(move _10) -> [return: bb21, unwind: bb9];
      }
  }
  
