- // MIR for `niched_1` before AdjustDiscriminantSwitches
+ // MIR for `niched_1` after AdjustDiscriminantSwitches
  
  fn niched_1(_1: Niched1) -> u32 {
      debug e => _1;
      let mut _0: u32;
      let mut _2: isize;
      let _3: bool;
      let mut _4: u32;
      let mut _5: bool;
+     let mut _6: isize;
      scope 1 {
          debug b => _3;
      }
  
      bb0: {
          _2 = discriminant(_1);
-         switchInt(move _2) -> [0: bb4, 1: bb3, 2: bb2, otherwise: bb1];
+         _6 = Add(move _2, const 2_isize);
+         switchInt(move _6) -> [2: bb4, 3: bb3, 4: bb2, otherwise: bb1];
      }
  
      bb1: {
          unreachable;
      }
  
      bb2: {
          _0 = const 42_u32;
          goto -> bb5;
      }
  
      bb3: {
          StorageLive(_3);
          _3 = copy ((_1 as B).0: bool);
          StorageLive(_4);
          StorageLive(_5);
          _5 = copy _3;
          _4 = move _5 as u32 (IntToInt);
          _0 = copy _4;
          StorageDead(_5);
          StorageDead(_4);
          StorageDead(_3);
          goto -> bb5;
      }
  
      bb4: {
          _0 = const 7_u32;
          goto -> bb5;
      }
  
      bb5: {
          return;
      }
  }
  
