- // MIR for `redundant` before InstSimplify
+ // MIR for `redundant` after InstSimplify
  
  fn redundant(_1: *const &u8) -> *const &u8 {
      debug x => _1;
      let mut _0: *const &u8;
      let mut _2: *const &u8;
      let mut _3: *const &u8;
      scope 1 (inlined generic_cast::<&u8, &u8>) {
          debug x => _3;
      }
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = _1;
-         _2 = _3 as *const &u8 (PtrToPtr);
+         _2 = _3;
          StorageDead(_3);
          _0 = _2;
          StorageDead(_2);
          return;
      }
  }
  
