- // MIR for `f` before ConstGoto
+ // MIR for `f` after ConstGoto
  
  fn f() -> u64 {
      let mut _0: u64;
      let mut _1: bool;
      let mut _2: i32;
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
          _2 = const A;
          switchInt(_2) -> [1: bb2, 2: bb2, 3: bb2, otherwise: bb1];
      }
  
      bb1: {
          _1 = const true;
          goto -> bb3;
      }
  
      bb2: {
          _1 = const B;
-         goto -> bb3;
+         switchInt(_1) -> [0: bb4, otherwise: bb3];
      }
  
      bb3: {
-         switchInt(_1) -> [0: bb5, otherwise: bb4];
-     }
- 
-     bb4: {
          _0 = const 2_u64;
-         goto -> bb6;
+         goto -> bb5;
      }
  
-     bb5: {
+     bb4: {
          _0 = const 1_u64;
-         goto -> bb6;
+         goto -> bb5;
      }
  
-     bb6: {
+     bb5: {
          StorageDead(_2);
          StorageDead(_1);
          return;
      }
  }
  
