- // MIR for `f` before JumpThreading
+ // MIR for `f` after JumpThreading
  
  fn f() -> u64 {
      let mut _0: u64;
      let mut _1: bool;
  
      bb0: {
          StorageLive(_1);
          switchInt(const A) -> [1: bb2, 2: bb2, 3: bb2, otherwise: bb1];
      }
  
      bb1: {
          _1 = const true;
          goto -> bb3;
      }
  
      bb2: {
          _1 = const B;
          switchInt(copy _1) -> [0: bb4, otherwise: bb3];
      }
  
      bb3: {
          _0 = const 2_u64;
          goto -> bb5;
      }
  
      bb4: {
          _0 = const 1_u64;
          goto -> bb5;
      }
  
      bb5: {
          StorageDead(_1);
          return;
      }
  }
  
