- // MIR for `noopt1` before EarlyOtherwiseBranch
+ // MIR for `noopt1` after EarlyOtherwiseBranch
  
  fn noopt1(_1: Option<u32>, _2: Option<u32>) -> u32 {
      debug x => _1;
      debug y => _2;
      let mut _0: u32;
      let mut _3: (std::option::Option<u32>, std::option::Option<u32>);
      let mut _4: std::option::Option<u32>;
      let mut _5: std::option::Option<u32>;
      let mut _6: isize;
      let mut _7: isize;
      let mut _8: isize;
      let _9: u32;
      let _10: u32;
      let _11: u32;
      let _12: u32;
      scope 1 {
          debug a => _9;
          debug b => _10;
      }
      scope 2 {
          debug a => _11;
      }
      scope 3 {
          debug b => _12;
      }
  
      bb0: {
          StorageLive(_3);
          StorageLive(_4);
          _4 = _1;
          StorageLive(_5);
          _5 = _2;
          _3 = (move _4, move _5);
          StorageDead(_5);
          StorageDead(_4);
          _8 = discriminant((_3.0: std::option::Option<u32>));
          switchInt(move _8) -> [0: bb2, 1: bb4, otherwise: bb1];
      }
  
      bb1: {
          unreachable;
      }
  
      bb2: {
          _6 = discriminant((_3.1: std::option::Option<u32>));
          switchInt(move _6) -> [0: bb3, 1: bb7, otherwise: bb1];
      }
  
      bb3: {
          _0 = const 3_u32;
          goto -> bb8;
      }
  
      bb4: {
          _7 = discriminant((_3.1: std::option::Option<u32>));
          switchInt(move _7) -> [0: bb6, 1: bb5, otherwise: bb1];
      }
  
      bb5: {
          StorageLive(_9);
          _9 = (((_3.0: std::option::Option<u32>) as Some).0: u32);
          StorageLive(_10);
          _10 = (((_3.1: std::option::Option<u32>) as Some).0: u32);
          _0 = const 0_u32;
          StorageDead(_10);
          StorageDead(_9);
          goto -> bb8;
      }
  
      bb6: {
          StorageLive(_11);
          _11 = (((_3.0: std::option::Option<u32>) as Some).0: u32);
          _0 = const 1_u32;
          StorageDead(_11);
          goto -> bb8;
      }
  
      bb7: {
          StorageLive(_12);
          _12 = (((_3.1: std::option::Option<u32>) as Some).0: u32);
          _0 = const 2_u32;
          StorageDead(_12);
          goto -> bb8;
      }
  
      bb8: {
          StorageDead(_3);
          return;
      }
  }
  
