- // MIR for `no_downcast` before EarlyOtherwiseBranch
+ // MIR for `no_downcast` after EarlyOtherwiseBranch
  
  fn no_downcast(_1: &E<'_>) -> u32 {
      debug e => _1;
      let mut _0: u32;
      let mut _2: isize;
      let mut _3: isize;
      let mut _4: &E<'_>;
      scope 1 {
      }
  
      bb0: {
          _3 = discriminant((*_1));
          switchInt(move _3) -> [1: bb1, 0: bb3, otherwise: bb5];
      }
  
      bb1: {
          _4 = deref_copy (((*_1) as Some).0: &E<'_>);
          _2 = discriminant((*_4));
          switchInt(move _2) -> [1: bb2, 0: bb3, otherwise: bb5];
      }
  
      bb2: {
          _0 = const 1_u32;
          goto -> bb4;
      }
  
      bb3: {
          _0 = const 2_u32;
          goto -> bb4;
      }
  
      bb4: {
          return;
      }
  
      bb5: {
          unreachable;
      }
  }
  
