- // MIR for `main` before CheckEnums
+ // MIR for `main` after CheckEnums
  
  fn main() -> () {
      let mut _0: ();
      let _1: Nested;
+     let mut _2: [std::mem::MaybeUninit<u8>; 4];
+     let mut _3: u16;
+     let mut _4: u128;
+     let mut _5: u128;
+     let mut _6: bool;
      scope 1 {
          debug _val => _1;
      }
  
      bb0: {
          StorageLive(_1);
+         _2 = const 0_u32 as [std::mem::MaybeUninit<u8>; 4] (Transmute);
+         _3 = copy _2[0..2] as u16 (Transmute);
+         _4 = copy _3 as u128 (IntToInt);
+         _5 = Sub(copy _4, const 0_u128);
+         _6 = Le(copy _5, const 3_u128);
+         assert(copy _6, "trying to construct an enum from an invalid value {}", copy _4) -> [success: bb1, unwind unreachable];
+     }
+ 
+     bb1: {
          _1 = const 0_u32 as Nested (Transmute);
          _0 = const ();
          StorageDead(_1);
          return;
      }
  }
  
