- // MIR for `main` before CheckEnums
+ // MIR for `main` after CheckEnums
  
  fn main() -> () {
      let mut _0: ();
      let _1: Wrap;
      let mut _2: ();
+     let mut _3: bool;
      scope 1 {
          debug _val => _1;
      }
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
          _2 = ();
+         _3 = const false;
+         assert(copy _3, "trying to construct an enum from an invalid value {}", const 0_u128) -> [success: bb1, unwind unreachable];
+     }
+ 
+     bb1: {
          _1 = move _2 as Wrap (Transmute);
          unreachable;
      }
  }
  
