- // MIR for `field_borrow` before GVN
+ // MIR for `field_borrow` after GVN
  
  fn field_borrow(_1: &FieldBorrow<'_>) -> () {
      debug a => _1;
      let mut _0: ();
      let _2: &u8;
      scope 1 {
          debug b => _2;
          let _3: &u8;
          scope 2 {
              debug c => _3;
          }
      }
  
      bb0: {
          StorageLive(_2);
          _2 = copy ((*_1).0: &u8);
          StorageLive(_3);
-         _3 = copy ((*_1).0: &u8);
+         _3 = copy _2;
          _0 = const ();
          StorageDead(_3);
          StorageDead(_2);
          return;
      }
  }
  
