- // MIR for `field_borrow_2` before GVN
+ // MIR for `field_borrow_2` after GVN
  
  fn field_borrow_2(_1: &&FieldBorrow<'_>) -> () {
      debug a => _1;
      let mut _0: ();
      let _2: &FieldBorrow<'_>;
      scope 1 {
          debug b => _2;
          let _3: &u8;
          scope 2 {
              debug c => _3;
              let _4: &FieldBorrow<'_>;
              scope 3 {
                  debug d => _4;
                  let _5: &u8;
                  scope 4 {
                      debug e => _5;
                      let _6: &u8;
                      scope 5 {
                          debug f => _6;
                      }
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_2);
          _2 = copy (*_1);
          StorageLive(_3);
          _3 = copy ((*_2).0: &u8);
          StorageLive(_4);
          _4 = copy (*_1);
          StorageLive(_5);
          _5 = copy ((*_4).0: &u8);
          StorageLive(_6);
-         _6 = copy ((*_4).0: &u8);
+         _6 = copy _5;
          _0 = const ();
          StorageDead(_6);
          StorageDead(_5);
          StorageDead(_4);
          StorageDead(_3);
          StorageDead(_2);
          return;
      }
  }
  
