- // MIR for `same_type_different_index` before GVN
+ // MIR for `same_type_different_index` after GVN
  
  fn same_type_different_index(_1: &SameType) -> SameType {
      debug v => _1;
      let mut _0: SameType;
      let _2: i32;
      let mut _4: i32;
      let mut _5: i32;
      scope 1 {
          debug a => _2;
          let _3: i32;
          scope 2 {
              debug b => _3;
          }
      }
  
      bb0: {
-         StorageLive(_2);
+         nop;
          _2 = copy ((*_1).1: i32);
-         StorageLive(_3);
+         nop;
          _3 = copy ((*_1).0: i32);
          StorageLive(_4);
          _4 = copy _2;
          StorageLive(_5);
          _5 = copy _3;
-         _0 = SameType { a: move _4, b: move _5 };
+         _0 = SameType { a: copy _2, b: copy _3 };
          StorageDead(_5);
          StorageDead(_4);
-         StorageDead(_3);
-         StorageDead(_2);
+         nop;
+         nop;
          return;
      }
  }
  
