- // MIR for `truncate` before GVN
+ // MIR for `truncate` after GVN
  
  fn truncate(_1: SignedWrappingB, _2: SignedWrappingC, _3: SignedB) -> (bool, bool, bool) {
      debug s1 => _1;
      debug s2 => _2;
      debug s3 => _3;
      let mut _0: (bool, bool, bool);
      let mut _4: bool;
      let mut _5: i8;
      let _6: SignedWrappingB;
      let mut _7: i16;
      let mut _8: bool;
      let mut _9: i8;
      let _10: SignedWrappingC;
      let mut _11: i16;
      let mut _12: bool;
      let mut _13: i8;
      let _14: SignedB;
      let mut _15: i16;
  
      bb0: {
          StorageLive(_4);
          StorageLive(_5);
          StorageLive(_6);
-         _6 = move _1;
-         _7 = discriminant(_6);
+         _6 = copy _1;
+         _7 = discriminant(_1);
          _5 = move _7 as i8 (IntToInt);
          StorageDead(_6);
          _4 = Gt(move _5, const -1_i8);
          StorageDead(_5);
          StorageLive(_8);
          StorageLive(_9);
          StorageLive(_10);
-         _10 = move _2;
-         _11 = discriminant(_10);
+         _10 = copy _2;
+         _11 = discriminant(_2);
          _9 = move _11 as i8 (IntToInt);
          StorageDead(_10);
          _8 = Gt(move _9, const -1_i8);
          StorageDead(_9);
          StorageLive(_12);
          StorageLive(_13);
          StorageLive(_14);
-         _14 = move _3;
-         _15 = discriminant(_14);
+         _14 = copy _3;
+         _15 = discriminant(_3);
          _13 = move _15 as i8 (IntToInt);
          StorageDead(_14);
          _12 = Gt(move _13, const -1_i8);
          StorageDead(_13);
          _0 = (move _4, move _8, move _12);
          StorageDead(_12);
          StorageDead(_8);
          StorageDead(_4);
          return;
      }
  }
  
