- // MIR for `signed_extension` before GVN
+ // MIR for `signed_extension` after GVN
  
  fn signed_extension(_1: SignedA) -> (bool, bool, bool, bool) {
      debug s => _1;
      let mut _0: (bool, bool, bool, bool);
      let _2: u16;
      let _3: SignedA;
      let mut _4: i8;
      let _6: SignedA;
      let mut _7: i8;
      let mut _8: bool;
      let mut _9: u16;
      let mut _10: bool;
      let mut _11: u16;
      let mut _12: bool;
      let mut _13: i16;
      let mut _14: bool;
      let mut _15: i16;
      scope 1 {
          debug s2u => _2;
          let _5: i16;
          scope 2 {
              debug s2s => _5;
          }
      }
  
      bb0: {
-         StorageLive(_2);
+         nop;
          StorageLive(_3);
          _3 = copy _1;
-         _4 = discriminant(_3);
-         _2 = move _4 as u16 (IntToInt);
+         _4 = discriminant(_1);
+         _2 = copy _4 as u16 (IntToInt);
          StorageDead(_3);
-         StorageLive(_5);
+         nop;
          StorageLive(_6);
          _6 = copy _1;
-         _7 = discriminant(_6);
-         _5 = move _7 as i16 (IntToInt);
+         _7 = copy _4;
+         _5 = copy _4 as i16 (IntToInt);
          StorageDead(_6);
          StorageLive(_8);
          StorageLive(_9);
          _9 = copy _2;
-         _8 = Gt(move _9, const 254_u16);
+         _8 = Gt(copy _2, const 254_u16);
          StorageDead(_9);
          StorageLive(_10);
          StorageLive(_11);
          _11 = copy _2;
-         _10 = Gt(move _11, const 65534_u16);
+         _10 = Gt(copy _2, const 65534_u16);
          StorageDead(_11);
-         StorageLive(_12);
+         nop;
          StorageLive(_13);
          _13 = copy _5;
-         _12 = Lt(move _13, const -2_i16);
+         _12 = const false;
          StorageDead(_13);
          StorageLive(_14);
          StorageLive(_15);
          _15 = copy _5;
-         _14 = Gt(move _15, const 1_i16);
+         _14 = const false;
          StorageDead(_15);
-         _0 = (move _8, move _10, move _12, move _14);
+         _0 = (move _8, move _10, const false, const false);
          StorageDead(_14);
-         StorageDead(_12);
+         nop;
          StorageDead(_10);
          StorageDead(_8);
-         StorageDead(_5);
-         StorageDead(_2);
+         nop;
+         nop;
          return;
      }
  }
  
