- // MIR for `stable_projection_nonoverlapping` before GVN
+ // MIR for `stable_projection_nonoverlapping` after GVN
  
  fn stable_projection_nonoverlapping(_1: (Adt,)) -> () {
      let mut _0: ();
      let mut _2: *mut Adt;
      let mut _3: u32;
      let mut _4: &Adt;
      let mut _5: (Adt,);
  
      bb0: {
          _2 = &raw mut (_1.0: Adt);
          _4 = &(*_2);
          _3 = copy (((*_4) as variant#1).0: u32);
          (_5.0: Adt) = Adt::Some(copy _3);
          return;
      }
  }
  
