- // MIR for `f_borrowed` before GVN
+ // MIR for `f_borrowed` after GVN
  
  fn f_borrowed(_1: u32) -> () {
      let mut _0: ();
      let mut _2: S;
      let mut _3: S;
      let mut _4: &S;
      let mut _5: S;
  
      bb0: {
-         StorageLive(_2);
+         nop;
          _2 = S(copy _1, const 2_u32);
-         _3 = S(copy _1, const 2_u32);
+         _3 = copy _2;
          _4 = &_3;
-         StorageDead(_2);
-         _5 = copy (*_4);
+         nop;
+         _5 = copy _2;
          return;
      }
  }
  
