- // MIR for `fn2` before GVN
+ // MIR for `fn2` after GVN
  
  fn fn2() -> () {
      let mut _0: ();
      let mut _1: usize;
      let mut _2: [u128; 6];
      let mut _3: ([u128; 6],);
      let mut _4: ([u128; 6],);
      let mut _5: ();
  
      bb0: {
          _1 = const 1_usize;
          _2 = [const 42_u128; 6];
          _3 = (copy _2,);
-         _2[_1] = const 1_u128;
+         _2[1 of 2] = const 1_u128;
          _4 = copy _3;
-         _5 = fn1(move (_3.0: [u128; 6]), copy _4) -> [return: bb1, unwind unreachable];
+         _5 = fn1(copy (_3.0: [u128; 6]), copy _3) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          return;
      }
  }
  
