- // MIR for `cast_from_unsigned_wrapping` before GVN
+ // MIR for `cast_from_unsigned_wrapping` after GVN
  
  fn cast_from_unsigned_wrapping(_1: UnsignedWrappingA) -> (bool, bool) {
      debug s => _1;
      let mut _0: (bool, bool);
      let _2: i8;
      let _3: UnsignedWrappingA;
      let mut _4: u8;
      let mut _5: bool;
      let mut _6: i8;
      let mut _7: bool;
      let mut _8: i8;
      scope 1 {
          debug s => _2;
      }
  
      bb0: {
-         StorageLive(_2);
+         nop;
          StorageLive(_3);
          _3 = copy _1;
-         _4 = discriminant(_3);
+         _4 = discriminant(_1);
          _2 = move _4 as i8 (IntToInt);
          StorageDead(_3);
-         StorageLive(_5);
+         nop;
          StorageLive(_6);
          _6 = copy _2;
-         _5 = Lt(move _6, const -1_i8);
+         _5 = const false;
          StorageDead(_6);
          StorageLive(_7);
          StorageLive(_8);
          _8 = copy _2;
-         _7 = Gt(move _8, const 1_i8);
+         _7 = const false;
          StorageDead(_8);
-         _0 = (move _5, move _7);
+         _0 = const (false, false);
          StorageDead(_7);
-         StorageDead(_5);
-         StorageDead(_2);
+         nop;
+         nop;
          return;
      }
+ }
+ 
+ ALLOC0 (size: 2, align: 1) {
+     00 00                                           │ ..
  }
  
