- // MIR for `stable_projection` before GVN
+ // MIR for `stable_projection` after GVN
  
  fn stable_projection(_1: (Adt,)) -> () {
      let mut _0: ();
      let mut _2: &Adt;
      let mut _3: u32;
      let mut _4: &Adt;
      let mut _5: (Adt,);
  
      bb0: {
          _2 = &(_1.0: Adt);
          _4 = &(*_2);
-         _3 = copy (((*_4) as variant#1).0: u32);
-         (_5.0: Adt) = Adt::Some(copy _3);
+         _3 = copy (((_1.0: Adt) as variant#1).0: u32);
+         (_5.0: Adt) = copy (_1.0: Adt);
          return;
      }
  }
  
