- // MIR for `move_then_rebuild_droppy` before GVN
+ // MIR for `move_then_rebuild_droppy` after GVN
  
  fn move_then_rebuild_droppy() -> () {
      let mut _0: ();
      let mut _1: ();
      let mut _2: Wrap;
      let mut _3: Wrap;
      let mut _4: Wide;
      let mut _5: Wide;
  
      bb0: {
          _4 = Wide { a: const 1_u32, b: const 2_u32, c: const 3_u32, d: const 4_u32 };
          _2 = Wrap(move _4);
          _1 = consume::<Wrap>(move _2) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          _5 = Wide { a: const 1_u32, b: const 2_u32, c: const 3_u32, d: const 4_u32 };
          _3 = Wrap(move _5);
          _1 = consume::<Wrap>(move _3) -> [return: bb2, unwind unreachable];
      }
  
      bb2: {
          return;
      }
  }
  
