- // MIR for `cast_to_signed_wrapping` before GVN
+ // MIR for `cast_to_signed_wrapping` after GVN
  
  fn cast_to_signed_wrapping(_1: UnsignedA) -> bool {
      debug s => _1;
      let mut _0: bool;
      let mut _2: i8;
      let _3: UnsignedA;
      let mut _4: u8;
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = copy _1;
-         _4 = discriminant(_3);
+         _4 = discriminant(_1);
          _2 = move _4 as i8 (IntToInt);
          StorageDead(_3);
          _0 = Gt(move _2, const -126_i8);
          StorageDead(_2);
          return;
      }
  }
  
