- // MIR for `remove_storage_dead` before GVN
+ // MIR for `remove_storage_dead` after GVN
  
  fn remove_storage_dead(_1: fn() -> AlwaysSome<T>) -> AlwaysSome<T> {
      debug f => _1;
      let mut _0: AlwaysSome<T>;
      let _2: T;
      let mut _3: AlwaysSome<T>;
      let mut _4: fn() -> AlwaysSome<T>;
      let mut _5: isize;
      let _6: T;
      let mut _7: T;
      let mut _8: isize;
      let mut _9: isize;
      scope 1 {
          debug v => _2;
      }
      scope 2 {
          debug v => _6;
      }
  
      bb0: {
          StorageLive(_2);
-         StorageLive(_3);
+         nop;
          StorageLive(_4);
          _4 = copy _1;
-         _3 = move _4() -> [return: bb1, unwind unreachable];
+         _3 = copy _1() -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          StorageDead(_4);
          _5 = discriminant(_3);
-         switchInt(move _5) -> [0: bb3, otherwise: bb2];
+         switchInt(copy _5) -> [0: bb3, otherwise: bb2];
      }
  
      bb2: {
          unreachable;
      }
  
      bb3: {
-         StorageLive(_6);
-         _6 = move ((_3 as Some).0: T);
-         _2 = move _6;
-         StorageDead(_6);
-         _8 = discriminant(_3);
-         StorageDead(_3);
+         nop;
+         _6 = copy ((_3 as Some).0: T);
+         _2 = copy _6;
+         nop;
+         _8 = copy _5;
+         nop;
          StorageLive(_7);
-         _7 = move _2;
-         _0 = AlwaysSome::<T>::Some(move _7);
+         _7 = copy _6;
+         _0 = copy _3;
          StorageDead(_7);
          StorageDead(_2);
          return;
      }
  }
  
