- // MIR for `on_non_ssa_place` before SimplifyComparisonIntegral
+ // MIR for `on_non_ssa_place` after SimplifyComparisonIntegral
  
  fn on_non_ssa_place(_1: [u64; 10], _2: usize) -> i32 {
      let mut _0: i32;
      let mut _3: bool;
  
      bb0: {
          _3 = Eq(copy _1[_2], const 42_u64);
          _2 = const 10_usize;
-         switchInt(copy _3) -> [1: bb1, otherwise: bb2];
+         switchInt(move _1[_2]) -> [42: bb1, otherwise: bb2];
      }
  
      bb1: {
          _0 = const 0_i32;
          return;
      }
  
      bb2: {
          _0 = const 1_i32;
          return;
      }
  }
  
