- // MIR for `dont_remove_moved_comparison` before SimplifyComparisonIntegral
+ // MIR for `dont_remove_moved_comparison` after SimplifyComparisonIntegral
  
  fn dont_remove_moved_comparison(_1: i8) -> i32 {
      let mut _0: i32;
      let mut _2: bool;
      let mut _3: i32;
      let mut _4: i32;
  
      bb0: {
          _2 = Eq(copy _1, const 17_i8);
          _3 = copy _2 as i32 (IntToInt);
-         switchInt(move _2) -> [1: bb1, otherwise: bb2];
+         switchInt(copy _1) -> [17: bb1, otherwise: bb2];
      }
  
      bb1: {
          _0 = copy _3;
          return;
      }
  
      bb2: {
          _0 = Add(copy _3, const 1_i32);
          return;
      }
  }
  
