- // MIR for `on_non_ssa_switch` before SimplifyComparisonIntegral
+ // MIR for `on_non_ssa_switch` after SimplifyComparisonIntegral
  
  fn on_non_ssa_switch(_1: u64) -> i32 {
      let mut _0: i32;
      let mut _2: bool;
  
      bb0: {
          _2 = Eq(copy _1, const 42_u64);
          _2 = const false;
-         switchInt(copy _2) -> [1: bb1, otherwise: bb2];
+         switchInt(move _1) -> [42: bb1, otherwise: bb2];
      }
  
      bb1: {
          _0 = const 0_i32;
          return;
      }
  
      bb2: {
          _0 = const 1_i32;
          return;
      }
  }
  
