- // MIR for `panics` before InstSimplify
+ // MIR for `panics` after InstSimplify
  
  fn panics() -> () {
      let mut _0: ();
      let _1: ();
      let _2: ();
      let _3: ();
  
      bb0: {
          nop;
-         _1 = assert_inhabited::<Never>() -> [return: bb1, unwind unreachable];
+         _1 = assert_inhabited::<Never>() -> unwind unreachable;
      }
  
      bb1: {
          nop;
          nop;
-         _2 = assert_zero_valid::<&u8>() -> [return: bb2, unwind unreachable];
+         _2 = assert_zero_valid::<&u8>() -> unwind unreachable;
      }
  
      bb2: {
          nop;
          nop;
-         _3 = assert_mem_uninitialized_valid::<&u8>() -> [return: bb3, unwind unreachable];
+         _3 = assert_mem_uninitialized_valid::<&u8>() -> unwind unreachable;
      }
  
      bb3: {
          nop;
          nop;
          return;
      }
  }
  
