- // MIR for `removable` before InstSimplify
+ // MIR for `removable` after InstSimplify
  
  fn removable() -> () {
      let mut _0: ();
      let _1: ();
      let _2: ();
      let _3: ();
  
      bb0: {
          nop;
-         _1 = assert_inhabited::<()>() -> [return: bb1, unwind unreachable];
+         goto -> bb1;
      }
  
      bb1: {
          nop;
          nop;
-         _2 = assert_zero_valid::<u8>() -> [return: bb2, unwind unreachable];
+         goto -> bb2;
      }
  
      bb2: {
          nop;
          nop;
-         _3 = assert_mem_uninitialized_valid::<u8>() -> [return: bb3, unwind unreachable];
+         goto -> bb3;
      }
  
      bb3: {
          nop;
          nop;
          return;
      }
  }
  
