- // MIR for `f` before InstSimplify
+ // MIR for `f` after InstSimplify
  
  fn f(_1: &T) -> *const T {
      debug a => _1;
      let mut _0: *const T;
      let _2: &*const T;
      let _3: &*const T;
      let _4: *const T;
      scope 1 {
          debug b => _2;
      }
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          StorageLive(_4);
          _4 = &raw const (*_1);
          _3 = &_4;
-         _2 = &(*_3);
+         _2 = _3;
          StorageDead(_3);
          _0 = (*_2);
          StorageDead(_4);
          StorageDead(_2);
          return;
      }
  }
  
