- // MIR for `transmute_ref_dst` before LowerIntrinsics
+ // MIR for `transmute_ref_dst` after LowerIntrinsics
  
  fn transmute_ref_dst(_1: &T) -> *const T {
      debug u => _1;
      let mut _0: *const T;
      let mut _2: &T;
  
      bb0: {
          StorageLive(_2);
          _2 = copy _1;
-         _0 = transmute::<&T, *const T>(move _2) -> [return: bb1, unwind unreachable];
+         _0 = move _2 as *const T (Transmute);
+         goto -> bb1;
      }
  
      bb1: {
          StorageDead(_2);
          return;
      }
  }
  
