- // MIR for `read_field_via_copy_droppy` before LowerIntrinsics
+ // MIR for `read_field_via_copy_droppy` after LowerIntrinsics
  
  fn read_field_via_copy_droppy(_1: &Composite) -> String {
      debug r => _1;
      let mut _0: std::string::String;
      let mut _2: *const Composite;
  
      bb0: {
          StorageLive(_2);
          _2 = &raw const (*_1);
-         _0 = read_field_via_copy::<Composite, String, 1>(move _2) -> [return: bb1, unwind unreachable];
+         _0 = copy ((*_2).1: std::string::String);
+         goto -> bb1;
      }
  
      bb1: {
          StorageDead(_2);
          return;
      }
  }
  
