- // MIR for `match_trunc_i16_u8` before MatchBranchSimplification
+ // MIR for `match_trunc_i16_u8` after MatchBranchSimplification
  
  fn match_trunc_i16_u8(_1: EnumAi16) -> u8 {
      debug i => _1;
      let mut _0: u8;
      let mut _2: i16;
+     let mut _3: i16;
  
      bb0: {
          _2 = discriminant(_1);
-         switchInt(move _2) -> [128: bb11, 255: bb10, 0: bb9, 1: bb8, 127: bb7, 65408: bb6, 65535: bb5, 65280: bb4, 65281: bb3, 65407: bb2, otherwise: bb1];
-     }
- 
-     bb1: {
-         unreachable;
-     }
- 
-     bb2: {
-         _0 = const 127_u8;
-         goto -> bb12;
-     }
- 
-     bb3: {
-         _0 = const 1_u8;
-         goto -> bb12;
-     }
- 
-     bb4: {
-         _0 = const 0_u8;
-         goto -> bb12;
-     }
- 
-     bb5: {
-         _0 = const u8::MAX;
-         goto -> bb12;
-     }
- 
-     bb6: {
-         _0 = const 128_u8;
-         goto -> bb12;
-     }
- 
-     bb7: {
-         _0 = const 127_u8;
-         goto -> bb12;
-     }
- 
-     bb8: {
-         _0 = const 1_u8;
-         goto -> bb12;
-     }
- 
-     bb9: {
-         _0 = const 0_u8;
-         goto -> bb12;
-     }
- 
-     bb10: {
-         _0 = const u8::MAX;
-         goto -> bb12;
-     }
- 
-     bb11: {
-         _0 = const 128_u8;
-         goto -> bb12;
-     }
- 
-     bb12: {
+         StorageLive(_3);
+         _3 = move _2;
+         _0 = _3 as u8 (IntToInt);
+         StorageDead(_3);
          return;
      }
  }
  
