- // MIR for `match_u8_u16_2` before MatchBranchSimplification
+ // MIR for `match_u8_u16_2` after MatchBranchSimplification
  
  fn match_u8_u16_2(_1: EnumBu8) -> i16 {
      let mut _0: i16;
      let mut _2: u8;
  
      bb0: {
          _2 = discriminant(_1);
          switchInt(_2) -> [1: bb1, 2: bb2, 5: bb3, otherwise: bb4];
      }
  
      bb1: {
          _0 = const 1_i16;
          goto -> bb5;
      }
  
      bb2: {
          _0 = const 2_i16;
          goto -> bb5;
      }
  
      bb3: {
          _0 = const 5_i16;
          _0 = const 5_i16;
          goto -> bb5;
      }
  
      bb4: {
          unreachable;
      }
  
      bb5: {
          return;
      }
  }
  
