- // MIR for `match_i8_i16` before MatchBranchSimplification
+ // MIR for `match_i8_i16` after MatchBranchSimplification
  
  fn match_i8_i16(_1: EnumAi8) -> i16 {
      debug i => _1;
      let mut _0: i16;
      let mut _2: i8;
+     let mut _3: i8;
  
      bb0: {
          _2 = discriminant(_1);
-         switchInt(move _2) -> [255: bb3, 2: bb4, 253: bb2, otherwise: bb1];
-     }
- 
-     bb1: {
-         unreachable;
-     }
- 
-     bb2: {
-         _0 = const -3_i16;
-         goto -> bb5;
-     }
- 
-     bb3: {
-         _0 = const -1_i16;
-         goto -> bb5;
-     }
- 
-     bb4: {
-         _0 = const 2_i16;
-         goto -> bb5;
-     }
- 
-     bb5: {
+         StorageLive(_3);
+         _3 = move _2;
+         _0 = _3 as i16 (IntToInt);
+         StorageDead(_3);
          return;
      }
  }
  
