- // MIR for `match_i16_i8` before MatchBranchSimplification
+ // MIR for `match_i16_i8` after MatchBranchSimplification
  
  fn match_i16_i8(_1: EnumAi16) -> i8 {
      debug i => _1;
      let mut _0: i8;
      let mut _2: i16;
+     let mut _3: i16;
  
      bb0: {
          _2 = discriminant(_1);
-         switchInt(move _2) -> [65535: bb3, 2: bb4, 65533: bb2, otherwise: bb1];
-     }
- 
-     bb1: {
-         unreachable;
-     }
- 
-     bb2: {
-         _0 = const -3_i8;
-         goto -> bb5;
-     }
- 
-     bb3: {
-         _0 = const -1_i8;
-         goto -> bb5;
-     }
- 
-     bb4: {
-         _0 = const 2_i8;
-         goto -> bb5;
-     }
- 
-     bb5: {
+         StorageLive(_3);
+         _3 = move _2;
+         _0 = _3 as i8 (IntToInt);
+         StorageDead(_3);
          return;
      }
  }
  
