- // MIR for `match_u8_u16` before MatchBranchSimplification
+ // MIR for `match_u8_u16` after MatchBranchSimplification
  
  fn match_u8_u16(_1: EnumBu8) -> u16 {
      debug i => _1;
      let mut _0: u16;
      let mut _2: u8;
  
      bb0: {
          _2 = discriminant(_1);
          switchInt(move _2) -> [1: bb4, 2: bb3, 5: bb2, otherwise: bb1];
      }
  
      bb1: {
          unreachable;
      }
  
      bb2: {
          _0 = const 5_u16;
          goto -> bb5;
      }
  
      bb3: {
          _0 = const 2_u16;
          goto -> bb5;
      }
  
      bb4: {
          _0 = const 1_u16;
          goto -> bb5;
      }
  
      bb5: {
          return;
      }
  }
  
