- // MIR for `test` before SimplifyCfg-final
+ // MIR for `test` after SimplifyCfg-final
  
  fn test(_1: bool) -> i32 {
      debug x => _1;
      let mut _0: i32;
      let mut _2: bool;
  
      bb0: {
          StorageLive(_2);
          _2 = copy _1;
          switchInt(move _2) -> [0: bb2, otherwise: bb1];
      }
  
      bb1: {
          _0 = const 42_i32;
          StorageDead(_2);
          return;
      }
  
      bb2: {
          _0 = const 2015_i32;
-         StorageDead(_2);
-         return;
-     }
- 
-     bb3: {
          StorageDead(_2);
          return;
      }
  }
  
