- // MIR for `remove_generic_array` before RemoveZsts
+ // MIR for `remove_generic_array` after RemoveZsts
  
  fn remove_generic_array(_1: T) -> () {
      debug x => _1;
      let mut _0: ();
      let _2: [T; 0];
      let mut _3: T;
      scope 1 {
-         debug a => _2;
+         debug a => const ZeroSized: [T; 0];
      }
  
      bb0: {
-         StorageLive(_2);
+         nop;
          StorageLive(_3);
          _3 = copy _1;
-         _2 = [];
+         nop;
          StorageDead(_3);
-         _0 = const ();
-         StorageDead(_2);
+         nop;
+         nop;
          return;
      }
  }
  
