- // MIR for `expose` before SimplifyLocals-before-const-prop
+ // MIR for `expose` after SimplifyLocals-before-const-prop
  
  fn expose(_1: *const usize) -> () {
      debug p => _1;
      let mut _0: ();
      let _2: usize;
      let mut _3: *const usize;
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = _1;
          _2 = move _3 as usize (PointerExpose);
          StorageDead(_3);
          StorageDead(_2);
          _0 = const ();
          return;
      }
  }
  
