- // MIR for `main` before GVN
+ // MIR for `main` after GVN
  
  fn main() -> () {
      let mut _0: ();
      let mut _1: bool;
      let _2: bool;
      scope 1 {
          debug x => _2;
      }
  
      bb0: {
          _2 = const false;
-         switchInt(_2) -> [0: bb1, otherwise: bb2];
+         switchInt(const false) -> [0: bb1, otherwise: bb2];
      }
  
      bb1: {
          goto -> bb3;
      }
  
      bb2: {
          _0 = noop() -> [return: bb3, unwind continue];
      }
  
      bb3: {
          return;
      }
  }
  
