- // MIR for `never_used_debug` before SingleUseConsts-initial
+ // MIR for `never_used_debug` after SingleUseConsts-initial
  
  fn never_used_debug() -> () {
      let mut _0: ();
      let _1: i32;
      scope 1 {
-         debug my_int => _1;
+         debug my_int => const <T as MyTrait>::ASSOC_INT;
      }
  
      bb0: {
          StorageLive(_1);
-         _1 = const <T as MyTrait>::ASSOC_INT;
+         nop;
          _0 = const ();
          StorageDead(_1);
          return;
      }
  }
  
