- // MIR for `enums` before ScalarReplacementOfAggregates
+ // MIR for `enums` after ScalarReplacementOfAggregates
  
  fn enums(_1: usize) -> usize {
      debug a => _1;                       // in scope 0 at $DIR/sroa.rs:+0:14: +0:15
      let mut _0: usize;                   // return place in scope 0 at $DIR/sroa.rs:+0:27: +0:32
      let mut _2: std::option::Option<usize>; // in scope 0 at $DIR/sroa.rs:+1:22: +1:29
      let mut _3: usize;                   // in scope 0 at $DIR/sroa.rs:+1:27: +1:28
      let mut _4: isize;                   // in scope 0 at $DIR/sroa.rs:+1:12: +1:19
      scope 1 {
          debug a => _5;                   // in scope 1 at $DIR/sroa.rs:+1:17: +1:18
          let _5: usize;                   // in scope 1 at $DIR/sroa.rs:+1:17: +1:18
      }
  
      bb0: {
          StorageLive(_2);                 // scope 1 at $DIR/sroa.rs:+1:22: +1:29
          StorageLive(_3);                 // scope 1 at $DIR/sroa.rs:+1:27: +1:28
          _3 = _1;                         // scope 1 at $DIR/sroa.rs:+1:27: +1:28
          _2 = Option::<usize>::Some(move _3); // scope 1 at $DIR/sroa.rs:+1:22: +1:29
          StorageDead(_3);                 // scope 1 at $DIR/sroa.rs:+1:28: +1:29
          _4 = discriminant(_2);           // scope 1 at $DIR/sroa.rs:+1:12: +1:19
          switchInt(move _4) -> [1: bb1, otherwise: bb2]; // scope 1 at $DIR/sroa.rs:+1:12: +1:19
      }
  
      bb1: {
          StorageLive(_5);                 // scope 1 at $DIR/sroa.rs:+1:17: +1:18
          _5 = ((_2 as Some).0: usize);    // scope 1 at $DIR/sroa.rs:+1:17: +1:18
          _0 = _5;                         // scope 1 at $DIR/sroa.rs:+1:32: +1:33
          StorageDead(_5);                 // scope 0 at $DIR/sroa.rs:+1:34: +1:35
          goto -> bb3;                     // scope 0 at $DIR/sroa.rs:+1:5: +1:46
      }
  
      bb2: {
          _0 = const 0_usize;              // scope 0 at $DIR/sroa.rs:+1:43: +1:44
          goto -> bb3;                     // scope 0 at $DIR/sroa.rs:+1:5: +1:46
      }
  
      bb3: {
          StorageDead(_2);                 // scope 0 at $DIR/sroa.rs:+2:1: +2:2
          return;                          // scope 0 at $DIR/sroa.rs:+2:2: +2:2
      }
  }
  
