- // MIR for `unions` before ScalarReplacementOfAggregates
+ // MIR for `unions` after ScalarReplacementOfAggregates
  
  fn unions(_1: f32) -> u32 {
      debug a => _1;                       // in scope 0 at $DIR/sroa.rs:+0:15: +0:16
      let mut _0: u32;                     // return place in scope 0 at $DIR/sroa.rs:+0:26: +0:29
      let mut _2: unions::Repr;            // in scope 0 at $DIR/sroa.rs:+5:14: +5:27
      let mut _3: f32;                     // in scope 0 at $DIR/sroa.rs:+5:24: +5:25
      scope 1 {
      }
  
      bb0: {
          StorageLive(_2);                 // scope 1 at $DIR/sroa.rs:+5:14: +5:27
          StorageLive(_3);                 // scope 1 at $DIR/sroa.rs:+5:24: +5:25
          _3 = _1;                         // scope 1 at $DIR/sroa.rs:+5:24: +5:25
          _2 = Repr { f: move _3 };        // scope 1 at $DIR/sroa.rs:+5:14: +5:27
          StorageDead(_3);                 // scope 1 at $DIR/sroa.rs:+5:26: +5:27
          _0 = (_2.1: u32);                // scope 1 at $DIR/sroa.rs:+5:14: +5:29
          StorageDead(_2);                 // scope 0 at $DIR/sroa.rs:+6:1: +6:2
          return;                          // scope 0 at $DIR/sroa.rs:+6:2: +6:2
      }
  }
  
