- // MIR for `aggregate` before TailCopyToMove
+ // MIR for `aggregate` after TailCopyToMove
  
  fn aggregate(_1: u32, _2: u32) -> Pair {
      debug x => _1;
      debug y => _2;
      let mut _0: Pair;
      let mut _3: u32;
      let mut _4: u32;
  
      bb0: {
          StorageLive(_3);
-         _3 = copy _1;
+         _3 = move _1;
          StorageLive(_4);
-         _4 = copy _2;
+         _4 = move _2;
          _0 = Pair { a: move _3, b: move _4 };
          StorageDead(_4);
          StorageDead(_3);
          return;
      }
  }
  
