- // MIR for `shared_return` before TailCopyToMove
+ // MIR for `shared_return` after TailCopyToMove
  
  fn shared_return(_1: u32, _2: u32, _3: bool) -> u32 {
      debug x => _1;
      debug y => _2;
      debug take_x => _3;
      let mut _0: u32;
      let mut _4: bool;
  
      bb0: {
          StorageLive(_4);
          _4 = copy _3;
          switchInt(move _4) -> [0: bb2, otherwise: bb1];
      }
  
      bb1: {
-         _0 = copy _1;
+         _0 = move _1;
          goto -> bb3;
      }
  
      bb2: {
-         _0 = copy _2;
+         _0 = move _2;
          goto -> bb3;
      }
  
      bb3: {
          StorageDead(_4);
          return;
      }
  }
  
