- // MIR for `otherwise_t5_uninhabited_default` before UninhabitedEnumBranching
+ // MIR for `otherwise_t5_uninhabited_default` after UninhabitedEnumBranching
  
  fn otherwise_t5_uninhabited_default() -> () {
      let mut _0: ();
      let _1: &str;
      let mut _2: Test5<T>;
      let mut _3: isize;
      let _4: &str;
      let _5: &str;
      let _6: &str;
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
          _2 = Test5::<T>::C;
          _3 = discriminant(_2);
          switchInt(move _3) -> [0: bb2, 1: bb3, 2: bb4, otherwise: bb1];
      }
  
      bb1: {
          StorageLive(_6);
          _6 = const "D";
          _1 = &(*_6);
          StorageDead(_6);
          goto -> bb5;
      }
  
      bb2: {
          _1 = const "A(T)";
          goto -> bb5;
      }
  
      bb3: {
          StorageLive(_4);
          _4 = const "B(T)";
          _1 = &(*_4);
          StorageDead(_4);
          goto -> bb5;
      }
  
      bb4: {
          StorageLive(_5);
          _5 = const "C";
          _1 = &(*_5);
          StorageDead(_5);
          goto -> bb5;
      }
  
      bb5: {
          drop(_2) -> [return: bb6, unwind unreachable];
      }
  
      bb6: {
          StorageDead(_2);
          StorageDead(_1);
          _0 = const ();
          return;
      }
  }
  
