- // MIR for `main` before UnreachablePropagation-initial
+ // MIR for `main` after UnreachablePropagation-initial
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/unreachable.rs:+0:11: +0:11
      let mut _1: std::option::Option<Empty>; // in scope 0 at $DIR/unreachable.rs:+1:23: +1:30
      let mut _2: isize;                   // in scope 0 at $DIR/unreachable.rs:+1:12: +1:20
      let _5: ();                          // in scope 0 at $DIR/unreachable.rs:+4:9: +8:10
      let mut _6: bool;                    // in scope 0 at $DIR/unreachable.rs:+4:12: +4:16
      let mut _7: !;                       // in scope 0 at $DIR/unreachable.rs:+10:9: +10:21
      scope 1 {
          debug _x => _3;                  // in scope 1 at $DIR/unreachable.rs:+1:17: +1:19
          let _3: Empty;                   // in scope 1 at $DIR/unreachable.rs:+1:17: +1:19
          let mut _4: i32;                 // in scope 1 at $DIR/unreachable.rs:+2:13: +2:19
          scope 2 {
              debug _y => _4;              // in scope 2 at $DIR/unreachable.rs:+2:13: +2:19
          }
      }
  
      bb0: {
          StorageLive(_1);                 // scope 1 at $DIR/unreachable.rs:+1:23: +1:30
          _1 = empty() -> bb1;             // scope 1 at $DIR/unreachable.rs:+1:23: +1:30
                                           // mir::Constant
                                           // + span: $DIR/unreachable.rs:11:23: 11:28
                                           // + literal: Const { ty: fn() -> Option<Empty> {empty}, val: Value(<ZST>) }
      }
  
      bb1: {
          _2 = discriminant(_1);           // scope 1 at $DIR/unreachable.rs:+1:12: +1:20
-         switchInt(move _2) -> [1: bb2, otherwise: bb6]; // scope 1 at $DIR/unreachable.rs:+1:12: +1:20
+         switchInt(move _2) -> [1: bb2, otherwise: bb3]; // scope 1 at $DIR/unreachable.rs:+1:12: +1:20
      }
  
      bb2: {
-         StorageLive(_3);                 // scope 1 at $DIR/unreachable.rs:+1:17: +1:19
-         _3 = move ((_1 as Some).0: Empty); // scope 1 at $DIR/unreachable.rs:+1:17: +1:19
-         StorageLive(_4);                 // scope 1 at $DIR/unreachable.rs:+2:13: +2:19
-         StorageLive(_5);                 // scope 2 at $DIR/unreachable.rs:+4:9: +8:10
-         StorageLive(_6);                 // scope 2 at $DIR/unreachable.rs:+4:12: +4:16
-         _6 = const true;                 // scope 2 at $DIR/unreachable.rs:+4:12: +4:16
-         switchInt(move _6) -> [0: bb4, otherwise: bb3]; // scope 2 at $DIR/unreachable.rs:+4:12: +4:16
+         unreachable;                     // scope 2 at $DIR/unreachable.rs:+4:12: +4:16
      }
  
      bb3: {
-         _4 = const 21_i32;               // scope 2 at $DIR/unreachable.rs:+5:13: +5:20
-         _5 = const ();                   // scope 2 at $DIR/unreachable.rs:+4:17: +6:10
-         goto -> bb5;                     // scope 2 at $DIR/unreachable.rs:+4:9: +8:10
-     }
- 
-     bb4: {
-         _4 = const 42_i32;               // scope 2 at $DIR/unreachable.rs:+7:13: +7:20
-         _5 = const ();                   // scope 2 at $DIR/unreachable.rs:+6:16: +8:10
-         goto -> bb5;                     // scope 2 at $DIR/unreachable.rs:+4:9: +8:10
-     }
- 
-     bb5: {
-         StorageDead(_6);                 // scope 2 at $DIR/unreachable.rs:+8:9: +8:10
-         StorageDead(_5);                 // scope 2 at $DIR/unreachable.rs:+8:9: +8:10
-         StorageLive(_7);                 // scope 2 at $DIR/unreachable.rs:+10:9: +10:21
-         unreachable;                     // scope 2 at $DIR/unreachable.rs:+10:15: +10:17
-     }
- 
-     bb6: {
          _0 = const ();                   // scope 0 at $DIR/unreachable.rs:+11:6: +11:6
          StorageDead(_1);                 // scope 0 at $DIR/unreachable.rs:+12:1: +12:2
          return;                          // scope 0 at $DIR/unreachable.rs:+12:2: +12:2
      }
  }
  
