name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push: { branches: [main] }

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-24.04
    environment: publish
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Rust (rustup)
        run: rustup update nightly --no-self-update && rustup default nightly
      - name: Run release-plz
        uses: release-plz/action@e8792575c7f2366cf6ff3ccc33ead9ace5b691c7 # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
