- // MIR for `main` before Inline
+ // MIR for `main` after Inline
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/cycle.rs:+0:11: +0:11
      let _1: ();                          // in scope 0 at $DIR/cycle.rs:+1:5: +1:9
+     let mut _2: fn() {g};                // in scope 0 at $DIR/cycle.rs:+1:5: +1:9
+     let mut _5: ();                      // in scope 0 at $DIR/cycle.rs:6:5: 6:8
+     scope 1 (inlined f::<fn() {g}>) {    // at $DIR/cycle.rs:17:5: 17:9
+         debug g => _2;                   // in scope 1 at $DIR/cycle.rs:5:6: 5:7
+         let mut _3: &fn() {g};           // in scope 1 at $DIR/cycle.rs:6:5: 6:6
+         let _4: ();                      // in scope 1 at $DIR/cycle.rs:6:5: 6:8
+         scope 2 (inlined <fn() {g} as Fn<()>>::call - shim(fn() {g})) { // at $DIR/cycle.rs:6:5: 6:8
+             scope 3 (inlined g) {        // at $SRC_DIR/core/src/ops/function.rs:LL:COL
+                 scope 4 (inlined f::<fn() {main}>) { // at $DIR/cycle.rs:12:5: 12:12
+                     debug g => main;     // in scope 4 at $DIR/cycle.rs:5:6: 5:7
+                     let _6: ();          // in scope 4 at $DIR/cycle.rs:6:5: 6:8
+                     scope 5 (inlined <fn() {main} as Fn<()>>::call - shim(fn() {main})) { // at $DIR/cycle.rs:6:5: 6:8
+                     }
+                 }
+             }
+         }
+     }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/cycle.rs:+1:5: +1:9
-         _1 = f::<fn() {g}>(g) -> bb1;    // scope 0 at $DIR/cycle.rs:+1:5: +1:9
+         StorageLive(_2);                 // scope 0 at $DIR/cycle.rs:+1:5: +1:9
+         _2 = g;                          // scope 0 at $DIR/cycle.rs:+1:5: +1:9
                                           // mir::Constant
-                                          // + span: $DIR/cycle.rs:17:5: 17:6
-                                          // + literal: Const { ty: fn(fn() {g}) {f::<fn() {g}>}, val: Value(<ZST>) }
-                                          // mir::Constant
                                           // + span: $DIR/cycle.rs:17:7: 17:8
                                           // + literal: Const { ty: fn() {g}, val: Value(<ZST>) }
+         StorageLive(_4);                 // scope 0 at $DIR/cycle.rs:+1:5: +1:9
+         StorageLive(_3);                 // scope 1 at $DIR/cycle.rs:6:5: 6:6
+         _3 = &_2;                        // scope 1 at $DIR/cycle.rs:6:5: 6:6
+         StorageLive(_5);                 // scope 1 at $DIR/cycle.rs:6:5: 6:8
+         _5 = const ();                   // scope 1 at $DIR/cycle.rs:6:5: 6:8
+         StorageLive(_6);                 // scope 2 at $SRC_DIR/core/src/ops/function.rs:LL:COL
+         _6 = main() -> [return: bb4, unwind: bb2]; // scope 5 at $SRC_DIR/core/src/ops/function.rs:LL:COL
+                                          // mir::Constant
+                                          // + span: no-location
+                                          // + literal: Const { ty: fn() {main}, val: Value(<ZST>) }
      }
  
      bb1: {
+         StorageDead(_4);                 // scope 0 at $DIR/cycle.rs:+1:5: +1:9
+         StorageDead(_2);                 // scope 0 at $DIR/cycle.rs:+1:5: +1:9
          StorageDead(_1);                 // scope 0 at $DIR/cycle.rs:+1:9: +1:10
          _0 = const ();                   // scope 0 at $DIR/cycle.rs:+0:11: +2:2
          return;                          // scope 0 at $DIR/cycle.rs:+2:2: +2:2
+     }
+ 
+     bb2 (cleanup): {
+         drop(_2) -> [return: bb3, unwind terminate]; // scope 1 at $DIR/cycle.rs:7:1: 7:2
+     }
+ 
+     bb3 (cleanup): {
+         resume;                          // scope 1 at $DIR/cycle.rs:5:1: 7:2
+     }
+ 
+     bb4: {
+         StorageDead(_6);                 // scope 2 at $SRC_DIR/core/src/ops/function.rs:LL:COL
+         StorageDead(_5);                 // scope 1 at $DIR/cycle.rs:6:5: 6:8
+         StorageDead(_3);                 // scope 1 at $DIR/cycle.rs:6:7: 6:8
+         drop(_2) -> bb1;                 // scope 1 at $DIR/cycle.rs:7:1: 7:2
      }
  }
  
