- // MIR for `try_execute_query` before Inline
+ // MIR for `try_execute_query` after Inline
  
  fn try_execute_query(_1: &C) -> () {
      debug c => _1;                       // in scope 0 at $DIR/dyn_trait.rs:+0:36: +0:37
      let mut _0: ();                      // return place in scope 0 at $DIR/dyn_trait.rs:+0:43: +0:43
      let mut _2: &dyn Cache<V = <C as Cache>::V>; // in scope 0 at $DIR/dyn_trait.rs:+1:14: +1:15
      let mut _3: &C;                      // in scope 0 at $DIR/dyn_trait.rs:+1:14: +1:15
+     scope 1 (inlined mk_cycle::<<C as Cache>::V>) { // at $DIR/dyn_trait.rs:28:5: 28:16
+         debug c => _2;                   // in scope 1 at $DIR/dyn_trait.rs:21:27: 21:28
+     }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/dyn_trait.rs:+1:14: +1:15
          StorageLive(_3);                 // scope 0 at $DIR/dyn_trait.rs:+1:14: +1:15
          _3 = &(*_1);                     // scope 0 at $DIR/dyn_trait.rs:+1:14: +1:15
          _2 = move _3 as &dyn Cache<V = <C as Cache>::V> (Pointer(Unsize)); // scope 0 at $DIR/dyn_trait.rs:+1:14: +1:15
          StorageDead(_3);                 // scope 0 at $DIR/dyn_trait.rs:+1:14: +1:15
-         _0 = mk_cycle::<<C as Cache>::V>(move _2) -> bb1; // scope 0 at $DIR/dyn_trait.rs:+1:5: +1:16
+         _0 = <dyn Cache<V = <C as Cache>::V> as Cache>::store_nocache(_2) -> bb1; // scope 1 at $DIR/dyn_trait.rs:22:5: 22:22
                                           // mir::Constant
-                                          // + span: $DIR/dyn_trait.rs:28:5: 28:13
-                                          // + literal: Const { ty: for<'a> fn(&'a (dyn Cache<V = <C as Cache>::V> + 'a)) {mk_cycle::<<C as Cache>::V>}, val: Value(<ZST>) }
+                                          // + span: $DIR/dyn_trait.rs:22:7: 22:20
+                                          // + literal: Const { ty: for<'a> fn(&'a dyn Cache<V = <C as Cache>::V>) {<dyn Cache<V = <C as Cache>::V> as Cache>::store_nocache}, val: Value(<ZST>) }
      }
  
      bb1: {
          StorageDead(_2);                 // scope 0 at $DIR/dyn_trait.rs:+1:15: +1:16
          return;                          // scope 0 at $DIR/dyn_trait.rs:+2:2: +2:2
      }
  }
  
