- // MIR for `drop` before Inline
+ // MIR for `drop` after Inline
  
  fn drop(_1: *mut Vec<A>, _2: *mut Option<B>) -> () {
      debug a => _1;
      debug b => _2;
      let mut _0: ();
      let _3: ();
      let mut _4: *mut std::vec::Vec<A>;
      let mut _5: *mut std::option::Option<B>;
+     scope 1 (inlined drop_in_place::<Vec<A>>) {
+         let mut _6: &mut std::vec::Vec<A>;
+     }
+     scope 2 (inlined drop_in_place::<Option<B>>) {
+         let mut _7: &mut std::option::Option<B>;
+         scope 3 (inlined std::ptr::drop_glue::<Option<B>> - shim(Some(Option<B>))) {
+             let mut _8: isize;
+             let mut _9: isize;
+         }
+     }
  
      bb0: {
          StorageLive(_3);
          StorageLive(_4);
          _4 = copy _1;
-         _3 = drop_in_place::<Vec<A>>(move _4) -> [return: bb1, unwind continue];
+         StorageLive(_6);
+         _6 = &mut (*_4);
+         _3 = std::ptr::drop_glue::<Vec<A>>(move _6) -> [return: bb1, unwind continue];
      }
  
      bb1: {
+         StorageDead(_6);
          StorageDead(_4);
          StorageDead(_3);
          StorageLive(_5);
          _5 = copy _2;
-         _0 = drop_in_place::<Option<B>>(move _5) -> [return: bb2, unwind continue];
+         StorageLive(_7);
+         _7 = &mut (*_5);
+         StorageLive(_8);
+         _8 = discriminant((*_7));
+         switchInt(move _8) -> [0: bb2, otherwise: bb3];
      }
  
      bb2: {
+         StorageDead(_8);
+         StorageDead(_7);
          StorageDead(_5);
          return;
+     }
+ 
+     bb3: {
+         drop((((*_7) as Some).0: B)) -> [return: bb2, unwind continue];
      }
  }
  
