- // MIR for `f` before Inline
+ // MIR for `f` after Inline
  
  fn f() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/inline_diverging.rs:+0:12: +0:12
      let mut _1: !;                       // in scope 0 at $DIR/inline_diverging.rs:+0:12: +2:2
      let _2: !;                           // in scope 0 at $DIR/inline_diverging.rs:+1:5: +1:12
+     scope 1 (inlined sleep) {            // at $DIR/inline_diverging.rs:8:5: 8:12
+     }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/inline_diverging.rs:+1:5: +1:12
-         _2 = sleep() -> unwind unreachable; // scope 0 at $DIR/inline_diverging.rs:+1:5: +1:12
-                                          // mir::Constant
-                                          // + span: $DIR/inline_diverging.rs:8:5: 8:10
-                                          // + literal: Const { ty: fn() -> ! {sleep}, val: Value(<ZST>) }
+         goto -> bb1;                     // scope 0 at $DIR/inline_diverging.rs:+1:5: +1:12
+     }
+ 
+     bb1: {
+         goto -> bb1;                     // scope 1 at $DIR/inline_diverging.rs:39:5: 39:12
      }
  }
  
