- // MIR for `call` before Inline
+ // MIR for `call` after Inline
  
  fn call(_1: Box<dyn Fn(i32)>) -> () {
      debug x => _1;
      let mut _0: ();
      let _2: ();
      let mut _3: &std::boxed::Box<dyn std::ops::Fn(i32)>;
      let mut _4: (i32,);
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = &_1;
          StorageLive(_4);
          _4 = (const 1_i32,);
          _2 = <Box<dyn Fn(i32)> as Fn<(i32,)>>::call(move _3, move _4) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          StorageDead(_4);
          StorageDead(_3);
          StorageDead(_2);
          _0 = const ();
          drop(_1) -> [return: bb2, unwind unreachable];
      }
  
      bb2: {
          return;
      }
  }
  
