- // MIR for `not_inlined_c_variadic` before Inline
+ // MIR for `not_inlined_c_variadic` after Inline
  
  fn not_inlined_c_variadic() -> () {
      let mut _0: ();
      let _1: u32;
      scope 1 {
          debug s => _1;
      }
  
      bb0: {
          StorageLive(_1);
          _1 = sum(const 4_u32, const 4_u32, const 30_u32, const 200_u32, const 1000_u32) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          _0 = const ();
          StorageDead(_1);
          return;
      }
  }
  
