- // MIR for `not_inlined_target_feature` before Inline
+ // MIR for `not_inlined_target_feature` after Inline
  
  fn not_inlined_target_feature() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/inline_compatibility.rs:+0:44: +0:44
      let _1: ();                          // in scope 0 at $DIR/inline_compatibility.rs:+1:5: +1:21
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/inline_compatibility.rs:+1:5: +1:21
          _1 = target_feature() -> bb1;    // scope 0 at $DIR/inline_compatibility.rs:+1:5: +1:21
                                           // mir::Constant
                                           // + span: $DIR/inline_compatibility.rs:19:5: 19:19
                                           // + literal: Const { ty: unsafe fn() {target_feature}, val: Value(<ZST>) }
      }
  
      bb1: {
          StorageDead(_1);                 // scope 0 at $DIR/inline_compatibility.rs:+1:21: +1:22
          _0 = const ();                   // scope 0 at $DIR/inline_compatibility.rs:+0:44: +2:2
          return;                          // scope 0 at $DIR/inline_compatibility.rs:+2:2: +2:2
      }
  }
  
