- // MIR for `bar` before Inline
+ // MIR for `bar` after Inline
  
  fn bar(_1: P) -> () {
      debug _baz => _1;                    // in scope 0 at $DIR/issue_78442.rs:+2:5: +2:9
      let mut _0: ();                      // return place in scope 0 at $DIR/issue_78442.rs:+3:3: +3:3
      let _2: ();                          // in scope 0 at $DIR/issue_78442.rs:+4:5: +4:17
      let mut _3: &fn() {foo};             // in scope 0 at $DIR/issue_78442.rs:+4:5: +4:15
      let _4: fn() {foo};                  // in scope 0 at $DIR/issue_78442.rs:+4:5: +4:15
      let mut _5: ();                      // in scope 0 at $DIR/issue_78442.rs:+4:5: +4:17
+     scope 1 (inlined <fn() {foo} as Fn<()>>::call - shim(fn() {foo})) { // at $DIR/issue_78442.rs:11:5: 11:17
+     }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/issue_78442.rs:+4:5: +4:17
          StorageLive(_3);                 // scope 0 at $DIR/issue_78442.rs:+4:5: +4:15
          StorageLive(_4);                 // scope 0 at $DIR/issue_78442.rs:+4:5: +4:15
-         _4 = hide_foo() -> [return: bb1, unwind: bb4]; // scope 0 at $DIR/issue_78442.rs:+4:5: +4:15
+         _4 = hide_foo() -> [return: bb1, unwind: bb3]; // scope 0 at $DIR/issue_78442.rs:+4:5: +4:15
                                           // mir::Constant
                                           // + span: $DIR/issue_78442.rs:11:5: 11:13
                                           // + literal: Const { ty: fn() -> impl Fn() {hide_foo}, val: Value(<ZST>) }
      }
  
      bb1: {
          _3 = &_4;                        // scope 0 at $DIR/issue_78442.rs:+4:5: +4:15
          StorageLive(_5);                 // scope 0 at $DIR/issue_78442.rs:+4:5: +4:17
          _5 = ();                         // scope 0 at $DIR/issue_78442.rs:+4:5: +4:17
-         _2 = <fn() {foo} as Fn<()>>::call(move _3, move _5) -> [return: bb2, unwind: bb4]; // scope 0 at $DIR/issue_78442.rs:+4:5: +4:17
-                                          // mir::Constant
-                                          // + span: $DIR/issue_78442.rs:11:5: 11:15
-                                          // + literal: Const { ty: for<'a> extern "rust-call" fn(&'a fn() {foo}, ()) -> <fn() {foo} as FnOnce<()>>::Output {<fn() {foo} as Fn<()>>::call}, val: Value(<ZST>) }
+         _2 = move (*_3)() -> [return: bb5, unwind: bb3]; // scope 1 at $SRC_DIR/core/src/ops/function.rs:LL:COL
      }
  
      bb2: {
-         StorageDead(_5);                 // scope 0 at $DIR/issue_78442.rs:+4:16: +4:17
-         StorageDead(_3);                 // scope 0 at $DIR/issue_78442.rs:+4:16: +4:17
-         StorageDead(_4);                 // scope 0 at $DIR/issue_78442.rs:+4:17: +4:18
-         StorageDead(_2);                 // scope 0 at $DIR/issue_78442.rs:+4:17: +4:18
-         _0 = const ();                   // scope 0 at $DIR/issue_78442.rs:+3:3: +5:2
-         drop(_1) -> [return: bb3, unwind: bb5]; // scope 0 at $DIR/issue_78442.rs:+5:1: +5:2
+         return;                          // scope 0 at $DIR/issue_78442.rs:+5:2: +5:2
      }
  
-     bb3: {
-         return;                          // scope 0 at $DIR/issue_78442.rs:+5:2: +5:2
+     bb3 (cleanup): {
+         drop(_1) -> [return: bb4, unwind terminate]; // scope 0 at $DIR/issue_78442.rs:+5:1: +5:2
      }
  
      bb4 (cleanup): {
-         drop(_1) -> [return: bb5, unwind terminate]; // scope 0 at $DIR/issue_78442.rs:+5:1: +5:2
+         resume;                          // scope 0 at $DIR/issue_78442.rs:+0:1: +5:2
      }
  
-     bb5 (cleanup): {
-         resume;                          // scope 0 at $DIR/issue_78442.rs:+0:1: +5:2
+     bb5: {
+         StorageDead(_5);                 // scope 0 at $DIR/issue_78442.rs:+4:16: +4:17
+         StorageDead(_3);                 // scope 0 at $DIR/issue_78442.rs:+4:16: +4:17
+         StorageDead(_4);                 // scope 0 at $DIR/issue_78442.rs:+4:17: +4:18
+         StorageDead(_2);                 // scope 0 at $DIR/issue_78442.rs:+4:17: +4:18
+         _0 = const ();                   // scope 0 at $DIR/issue_78442.rs:+3:3: +5:2
+         drop(_1) -> [return: bb2, unwind: bb4]; // scope 0 at $DIR/issue_78442.rs:+5:1: +5:2
      }
  }
  
