- // MIR for `caller` before Inline
+ // MIR for `caller` after Inline
  
  fn caller() -> () {
      let mut _0: ();
      let _1: ();
      let _2: ();
+     scope 1 (inlined callee_required) {
+     }
+     scope 2 (inlined callee_must) {
+     }
  
      bb0: {
          StorageLive(_1);
-         _1 = callee_required() -> [return: bb1, unwind continue];
-     }
- 
-     bb1: {
          StorageDead(_1);
          StorageLive(_2);
-         _2 = callee_must() -> [return: bb2, unwind continue];
-     }
- 
-     bb2: {
          StorageDead(_2);
          _0 = const ();
          return;
      }
  }
  
