- // MIR for `wrapper` before Inline
+ // MIR for `wrapper` after Inline
  
  fn wrapper(_1: &Thing) -> u8 {
      debug t => _1;
      let mut _0: u8;
      let mut _2: &Thing;
+     scope 1 (inlined Thing::get) {
+         debug self => _2;
+     }
  
      bb0: {
          StorageLive(_2);
          _2 = &(*_1);
-         _0 = Thing::get(move _2) -> [return: bb1, unwind unreachable];
-     }
- 
-     bb1: {
+         _0 = ((*_2).0: u8);
          StorageDead(_2);
          return;
      }
  }
  
