- // MIR for `unwrap_unchecked` before Inline
+ // MIR for `unwrap_unchecked` after Inline
  
  fn unwrap_unchecked(_1: Option<T>) -> T {
      debug slf => _1;
      let mut _0: T;
      let mut _2: std::option::Option<T>;
+     scope 1 (inlined #[track_caller] Option::<T>::unwrap_unchecked) {
+         let mut _3: isize;
+         scope 2 {
+         }
+         scope 3 (inlined #[track_caller] unreachable_unchecked) {
+             let _4: ();
+             scope 4 (inlined core::ub_checks::check_language_ub) {
+                 scope 5 (inlined core::ub_checks::check_language_ub::runtime) {
+                 }
+             }
+         }
+     }
  
      bb0: {
          StorageLive(_2);
          _2 = move _1;
-         _0 = Option::<T>::unwrap_unchecked(move _2) -> [return: bb1, unwind: bb2];
+         StorageLive(_3);
+         StorageLive(_4);
+         _3 = discriminant(_2);
+         switchInt(move _3) -> [0: bb2, 1: bb3, otherwise: bb1];
      }
  
      bb1: {
-         StorageDead(_2);
-         return;
+         unreachable;
      }
  
-     bb2 (cleanup): {
-         resume;
+     bb2: {
+         assume(const UbChecks);
+         _4 = unreachable_unchecked::precondition_check() -> [return: bb1, unwind unreachable];
+     }
+ 
+     bb3: {
+         _0 = move ((_2 as Some).0: T);
+         StorageDead(_4);
+         StorageDead(_3);
+         StorageDead(_2);
+         return;
      }
  }
  
