FROM library/ubuntu:18.04
RUN apt-get update
RUN apt-get install -y --no-install-recommends cmake
RUN apt-get install -y --no-install-recommends build-essential
RUN apt-get install -y --no-install-recommends ssh
RUN apt-get install -y --no-install-recommends git
RUN apt-get install -y --no-install-recommends python
RUN apt-get install -y --no-install-recommends binutils-gold binutils-dev
