- // MIR for `move_out_by_subslice` before ElaborateDrops
+ // MIR for `move_out_by_subslice` after ElaborateDrops
  
  fn move_out_by_subslice() -> () {
      let mut _0: ();
      let _1: [std::boxed::Box<i32>; 3];
      let mut _2: std::boxed::Box<i32>;
      let mut _3: std::boxed::Box<i32>;
      let mut _4: std::boxed::Box<i32>;
      scope 1 {
          debug a => _1;
          let _5: [std::boxed::Box<i32>; 2];
          scope 2 {
              debug _y => _5;
          }
      }
  
      bb0: {
          StorageLive(_1);
          StorageLive(_2);
          _2 = Box::<i32>::new(const 1_i32) -> [return: bb1, unwind continue];
      }
  
      bb1: {
          StorageLive(_3);
          _3 = Box::<i32>::new(const 2_i32) -> [return: bb2, unwind: bb11];
      }
  
      bb2: {
          StorageLive(_4);
          _4 = Box::<i32>::new(const 3_i32) -> [return: bb3, unwind: bb10];
      }
  
      bb3: {
          _1 = [move _2, move _3, move _4];
-         drop(_4) -> [return: bb4, unwind: bb10];
+         goto -> bb4;
      }
  
      bb4: {
          StorageDead(_4);
-         drop(_3) -> [return: bb5, unwind: bb11];
+         goto -> bb5;
      }
  
      bb5: {
          StorageDead(_3);
-         drop(_2) -> [return: bb6, unwind continue];
+         goto -> bb6;
      }
  
      bb6: {
          StorageDead(_2);
          PlaceMention(_1);
          StorageLive(_5);
          _5 = move _1[0..2];
          _0 = const ();
          drop(_5) -> [return: bb7, unwind: bb9];
      }
  
      bb7: {
          StorageDead(_5);
-         drop(_1) -> [return: bb8, unwind continue];
+         goto -> bb19;
      }
  
      bb8: {
          StorageDead(_1);
          return;
      }
  
      bb9 (cleanup): {
-         drop(_1) -> [return: bb12, unwind terminate(cleanup)];
+         goto -> bb22;
      }
  
      bb10 (cleanup): {
          drop(_3) -> [return: bb11, unwind terminate(cleanup)];
      }
  
      bb11 (cleanup): {
          drop(_2) -> [return: bb12, unwind terminate(cleanup)];
      }
  
      bb12 (cleanup): {
          resume;
+     }
+ 
+     bb13: {
+         goto -> bb8;
+     }
+ 
+     bb14 (cleanup): {
+         goto -> bb12;
+     }
+ 
+     bb15 (cleanup): {
+         goto -> bb14;
+     }
+ 
+     bb16 (cleanup): {
+         drop(_1[2..3]) -> [return: bb15, unwind terminate(cleanup)];
+     }
+ 
+     bb17: {
+         goto -> bb13;
+     }
+ 
+     bb18: {
+         goto -> bb17;
+     }
+ 
+     bb19: {
+         drop(_1[2..3]) -> [return: bb18, unwind: bb15];
+     }
+ 
+     bb20 (cleanup): {
+         goto -> bb12;
+     }
+ 
+     bb21 (cleanup): {
+         goto -> bb20;
+     }
+ 
+     bb22 (cleanup): {
+         drop(_1[2..3]) -> [return: bb21, unwind terminate(cleanup)];
      }
  }
  
