test_utils::marks!(
    bogus_paths
    name_res_works_for_broken_modules
    can_import_enum_variant
    type_var_cycles_resolve_completely
    type_var_cycles_resolve_as_possible
    type_var_resolves_to_int_var
    glob_enum
    glob_across_crates
    std_prelude
    match_ergonomics_ref
    trait_resolution_on_fn_type
    infer_while_let
);
