test_utils::marks!(
    name_res_works_for_broken_modules
    can_import_enum_variant
    type_var_cycles_resolve_completely
    type_var_cycles_resolve_as_possible
    type_var_resolves_to_int_var
    glob_enum
    glob_across_crates
    std_prelude
);
