pub static RENAMED_LINTS: &[(&str, &str)] = &[
    ("clippy::stutter", "clippy::module_name_repetitions"),
    ("clippy::new_without_default_derive", "clippy::new_without_default"),
    ("clippy::cyclomatic_complexity", "clippy::cognitive_complexity"),
    ("clippy::const_static_lifetime", "clippy::redundant_static_lifetimes"),
    ("clippy::option_and_then_some", "clippy::bind_instead_of_map"),
    ("clippy::box_vec", "clippy::box_collection"),
    ("clippy::block_in_if_condition_expr", "clippy::blocks_in_if_conditions"),
    ("clippy::block_in_if_condition_stmt", "clippy::blocks_in_if_conditions"),
    ("clippy::option_map_unwrap_or", "clippy::map_unwrap_or"),
    ("clippy::option_map_unwrap_or_else", "clippy::map_unwrap_or"),
    ("clippy::result_map_unwrap_or_else", "clippy::map_unwrap_or"),
    ("clippy::option_unwrap_used", "clippy::unwrap_used"),
    ("clippy::result_unwrap_used", "clippy::unwrap_used"),
    ("clippy::option_expect_used", "clippy::expect_used"),
    ("clippy::result_expect_used", "clippy::expect_used"),
    ("clippy::for_loop_over_option", "clippy::for_loops_over_fallibles"),
    ("clippy::for_loop_over_result", "clippy::for_loops_over_fallibles"),
    ("clippy::identity_conversion", "clippy::useless_conversion"),
    ("clippy::zero_width_space", "clippy::invisible_characters"),
    ("clippy::single_char_push_str", "clippy::single_char_add_str"),
    ("clippy::if_let_some_result", "clippy::match_result_ok"),
    ("clippy::disallowed_type", "clippy::disallowed_types"),
    ("clippy::disallowed_method", "clippy::disallowed_methods"),
    ("clippy::ref_in_deref", "clippy::needless_borrow"),
    ("clippy::to_string_in_display", "clippy::recursive_format_impl"),
    // uplifted lints
    ("clippy::invalid_ref", "invalid_value"),
    ("clippy::into_iter_on_array", "array_into_iter"),
    ("clippy::unused_label", "unused_labels"),
    ("clippy::drop_bounds", "drop_bounds"),
    ("clippy::temporary_cstring_as_ptr", "temporary_cstring_as_ptr"),
    ("clippy::panic_params", "non_fmt_panics"),
    ("clippy::unknown_clippy_lints", "unknown_lints"),
    ("clippy::invalid_atomic_ordering", "invalid_atomic_ordering"),
    ("clippy::mem_discriminant_non_enum", "enum_intrinsics_non_enums"),
];
