- // MIR for `ptr_cast` before InstCombine
+ // MIR for `ptr_cast` after InstCombine
  
  fn ptr_cast(_1: *const u8) -> *mut () {
      debug p => _1;
      let mut _0: *mut ();
      let mut _2: *mut u8;
      let mut _3: *const u8;
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = _1;
-         _2 = move _3 as *mut u8 (PtrToPtr);
+         _0 = move _3 as *mut () (PtrToPtr);
+         nop;
          StorageDead(_3);
-         _0 = move _2 as *mut () (PtrToPtr);
          StorageDead(_2);
          return;
      }
  }
  
