//@ compile-flags: -Z unstable-options

#![crate_type = "lib"]
#![feature(rustc_private)]
#![deny(rustc::missing_generic_type_visitable_derive)]

extern crate rustc_type_ir;
extern crate rustc_type_ir_macros;

use rustc_type_ir::{GenericTypeVisitable, TypeVisitable};
use rustc_type_ir::{Interner, TypeVisitor, VisitorResult};
use rustc_type_ir_macros::{GenericTypeVisitable, TypeVisitable_Generic};
use std::{fmt::Debug, hash::Hash};

// Should lint: `TypeVisitable` is implemented, but `GenericTypeVisitable` isn't

#[derive(Debug, TypeVisitable_Generic)]
struct DerivesRegular;
//~^ ERROR missing `#[derive(GenericTypeVisitable)]` on a type which implements `TypeVisitable`

#[derive(Debug)]
struct ImplsRegular;
//~^ ERROR missing `#[derive(GenericTypeVisitable)]` on a type which implements `TypeVisitable`

impl<I: Interner> TypeVisitable<I> for ImplsRegular {
    fn visit_with<F: TypeVisitor<I>>(&self, _f: &mut F) -> F::Result {
        F::Result::output()
    }
}

// Same but with an enum

#[derive(Debug, TypeVisitable_Generic)]
enum EnumDerivesRegular {}
//~^ ERROR missing `#[derive(GenericTypeVisitable)]` on a type which implements `TypeVisitable`

// Same but the type is generic, over the interner

#[derive(TypeVisitable_Generic)]
struct GenericOverIDerivesRegular<I: Interner>(I::Clause);
//~^ ERROR missing `#[derive(GenericTypeVisitable)]` on a type which implements `TypeVisitable`

// manually hand-rolled `#[derive_where(Debug; I: Interner)]`
impl<I: Interner> std::fmt::Debug for GenericOverIDerivesRegular<I> {
    fn fmt(&self, _f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        todo!()
    }
}

// Same but the type is generic, over an unrelated type

#[derive(TypeVisitable_Generic)]
struct GenericOverTDerivesRegular<T>([T; 67]);
//~^ ERROR missing `#[derive(GenericTypeVisitable)]` on a type which implements `TypeVisitable`

// manually hand-rolled `#[derive(Debug)]`, to avoid the spurious bound on `T`
impl<T> Debug for GenericOverTDerivesRegular<T> {
    fn fmt(&self, _f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        todo!()
    }
}

// Should not lint: both traits are implemented

#[derive(Debug, TypeVisitable_Generic, GenericTypeVisitable)]
struct DerivesBoth;

#[derive(Debug, GenericTypeVisitable)]
struct ImplsAndDerives;

impl<I: Interner> TypeVisitable<I> for ImplsAndDerives {
    fn visit_with<F: TypeVisitor<I>>(&self, _f: &mut F) -> F::Result {
        F::Result::output()
    }
}

#[derive(Debug, TypeVisitable_Generic)]
struct DerivesAndImpls;

unsafe impl<V> GenericTypeVisitable<V> for DerivesAndImpls {
    fn generic_visit_with(&self, _visitor: &mut V) {}
}

#[derive(Debug)]
struct ImplsBoth;

impl<I: Interner> TypeVisitable<I> for ImplsBoth {
    fn visit_with<F: TypeVisitor<I>>(&self, _f: &mut F) -> F::Result {
        F::Result::output()
    }
}

unsafe impl<V> GenericTypeVisitable<V> for ImplsBoth {
    fn generic_visit_with(&self, _visitor: &mut V) {}
}

// Should not lint: `TypeVisitable` isn't implemented, so `GenericTypeVisitable` doesn't need to be
// either

struct ImplsNone;

// Should not lint: `GenericTypeVisitable` is implemented but `TypeVisitable` isn't -- weird, but
// okay for the purposes of this lint

#[derive(GenericTypeVisitable)]
struct DerivesGeneric;

struct ImplsGeneric;

unsafe impl<V> GenericTypeVisitable<V> for ImplsGeneric {
    fn generic_visit_with(&self, _visitor: &mut V) {}
}

// FIXME(ada4a): this will currently lint, and suggest adding a derive, even though ther's already
// one present. The actual problem is that the item has a _field_ that doesn't implement the trait,
// which makes the impl generated by the derive on this item unusable due to unsatisfied bounds.
//
// There are two ways of solving this:
// - in the lint, emit a different suggestion -- namely, to add a derive to the problematic field's
//   type -- if we see that the linted type already has a derive.
// - change the derive to add _assertions_ that the bound holds for each field type, and not just
//   trait bounds on the impl.
#[derive(Debug)]
#[derive(TypeVisitable_Generic, GenericTypeVisitable)]
struct FieldDoesntImplGeneric {
    //~^ ERROR missing `#[derive(GenericTypeVisitable)]` on a type which implements `TypeVisitable`
    field: ImplsRegular,
}
