- // MIR for `foo` before Refinements
+ // MIR for `foo` after Refinements
  
  fn foo(_1: u32) -> u32 {
      debug a => _1;                       // in scope 0 at $DIR/refine_from_removal.rs:3:8: 3:9
      let mut _0: u32;                     // return place in scope 0 at $DIR/refine_from_removal.rs:3:19: 3:22
      let _2: i32;                         // in scope 0 at $DIR/refine_from_removal.rs:4:9: 4:10
      let _3: u32;                         // in scope 0 at $DIR/refine_from_removal.rs:5:9: 5:20
      scope 1 {
          debug c => _2;                   // in scope 1 at $DIR/refine_from_removal.rs:4:9: 4:10
      }
      scope 2 {
          debug b => _3;                   // in scope 2 at $DIR/refine_from_removal.rs:5:9: 5:20
      }
  
      bb0: {
          StorageLive(_2);                 // scope 0 at $DIR/refine_from_removal.rs:4:9: 4:10
          switchInt(_1) -> [1_u32: bb3, 2_u32: bb4, otherwise: bb1]; // scope 0 at $DIR/refine_from_removal.rs:4:13: 4:20
      }
  
      bb1: {
          _2 = const 1_i32;                // scope 0 at $DIR/refine_from_removal.rs:11:14: 11:15
          goto -> bb10;                    // scope 0 at $DIR/refine_from_removal.rs:11:14: 11:15
      }
  
      bb2: {
-         switchInt(_3) -> [1_u32: bb6, 2_u32: bb7, 3_u32: bb8, otherwise: bb5]; // scope 2 at $DIR/refine_from_removal.rs:5:24: 5:31
+         switchInt(_3) -> [1_u32: bb6, otherwise: bb7]; // scope 2 at $DIR/refine_from_removal.rs:5:24: 5:31
      }
  
      bb3: {
          StorageLive(_3);                 // scope 0 at $DIR/refine_from_removal.rs:5:9: 5:20
          _3 = _1;                         // scope 0 at $DIR/refine_from_removal.rs:5:9: 5:20
          goto -> bb2;                     // scope 0 at $DIR/refine_from_removal.rs:4:13: 12:6
      }
  
      bb4: {
          StorageLive(_3);                 // scope 0 at $DIR/refine_from_removal.rs:5:9: 5:20
          _3 = _1;                         // scope 0 at $DIR/refine_from_removal.rs:5:9: 5:20
          goto -> bb2;                     // scope 0 at $DIR/refine_from_removal.rs:4:13: 12:6
      }
  
      bb5: {
          _2 = const 8594_i32;             // scope 2 at $DIR/refine_from_removal.rs:9:18: 9:22
          goto -> bb9;                     // scope 2 at $DIR/refine_from_removal.rs:9:18: 9:22
      }
  
      bb6: {
          _2 = const 18_i32;               // scope 2 at $DIR/refine_from_removal.rs:6:18: 6:20
          goto -> bb9;                     // scope 2 at $DIR/refine_from_removal.rs:6:18: 6:20
      }
  
      bb7: {
          _2 = const 384_i32;              // scope 2 at $DIR/refine_from_removal.rs:7:18: 7:21
          goto -> bb9;                     // scope 2 at $DIR/refine_from_removal.rs:7:18: 7:21
      }
  
      bb8: {
          _2 = const 28732897_i32;         // scope 2 at $DIR/refine_from_removal.rs:8:18: 8:26
          goto -> bb9;                     // scope 2 at $DIR/refine_from_removal.rs:8:18: 8:26
      }
  
      bb9: {
          StorageDead(_3);                 // scope 0 at $DIR/refine_from_removal.rs:10:9: 10:10
          goto -> bb10;                    // scope 0 at $DIR/refine_from_removal.rs:10:9: 10:10
      }
  
      bb10: {
          switchInt(_2) -> [18_i32: bb12, 384_i32: bb13, 1_i32: bb14, otherwise: bb11]; // scope 1 at $DIR/refine_from_removal.rs:14:5: 14:12
      }
  
      bb11: {
          _0 = const 6_u32;                // scope 1 at $DIR/refine_from_removal.rs:18:14: 18:15
          goto -> bb15;                    // scope 1 at $DIR/refine_from_removal.rs:18:14: 18:15
      }
  
      bb12: {
          _0 = const 3_u32;                // scope 1 at $DIR/refine_from_removal.rs:15:15: 15:16
          goto -> bb15;                    // scope 1 at $DIR/refine_from_removal.rs:15:15: 15:16
      }
  
      bb13: {
          _0 = const 4_u32;                // scope 1 at $DIR/refine_from_removal.rs:16:16: 16:17
          goto -> bb15;                    // scope 1 at $DIR/refine_from_removal.rs:16:16: 16:17
      }
  
      bb14: {
          _0 = const 5_u32;                // scope 1 at $DIR/refine_from_removal.rs:17:14: 17:15
          goto -> bb15;                    // scope 1 at $DIR/refine_from_removal.rs:17:14: 17:15
      }
  
      bb15: {
          StorageDead(_2);                 // scope 0 at $DIR/refine_from_removal.rs:21:1: 21:2
          return;                          // scope 0 at $DIR/refine_from_removal.rs:21:2: 21:2
      }
  }
  
