source "http://rubygems.org"

ruby '2.1.1'

gem 'builder'
gem 'coderay'
gem 'kramdown', '~> 0.13.2'
gem 'mime-types', '~> 1.16'
gem 'nanoc'
gem 'nokogiri', '~> 1.6.0'
gem 'pygments.rb'
gem 'rake', '~> 0.9.2'
gem 'thin'
gem 'yajl-ruby', '~> 0.8.2'

group :development do
  gem 'adsf'
  gem 'fssm'
end