#![allow(clippy::unused_unit, clippy::missing_safety_doc)]
#![warn(clippy::too_many_lines)]

fn good_lines() {
    /* println!("This is good."); */
    // println!("This is good.");
    /* */ // println!("This is good.");
    /* */ // println!("This is good.");
    /* */ // println!("This is good.");
    /* */ // println!("This is good.");
    /* println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good."); */
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
    println!("This is good.");
}

#[allow(unused)] // the attr shouldn't get included in the highlight
pub async unsafe extern "Rust" fn bad_lines() -> () {
    //~^ too_many_lines

    println!("Dont get confused by braces: {{}}");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
    println!("This is bad.");
}

struct Foo;
impl Foo {
    #[allow(unused)] // the attr shouldn't get included in the highlight
    pub async unsafe extern "Rust" fn bad_lines() -> () {
        //~^ too_many_lines

        println!("Dont get confused by braces: {{}}");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
        println!("This is bad.");
    }
}

fn main() {}
