- // MIR for `structs` before ScalarReplacementOfAggregates
+ // MIR for `structs` after ScalarReplacementOfAggregates
  
  fn structs(_1: f32) -> f32 {
      debug a => _1;                       // in scope 0 at $DIR/structs.rs:+0:16: +0:17
      let mut _0: f32;                     // return place in scope 0 at $DIR/structs.rs:+0:27: +0:30
      let mut _2: structs::U;              // in scope 0 at $DIR/structs.rs:+6:5: +6:21
      let mut _3: f32;                     // in scope 0 at $DIR/structs.rs:+6:18: +6:19
+     let mut _4: usize;                   // in scope 0 at $DIR/structs.rs:+6:5: +6:21
+     let mut _5: f32;                     // in scope 0 at $DIR/structs.rs:+6:5: +6:21
  
      bb0: {
-         StorageLive(_2);                 // scope 0 at $DIR/structs.rs:+6:5: +6:21
+         StorageLive(_4);                 // scope 0 at $DIR/structs.rs:+6:5: +6:21
+         StorageLive(_5);                 // scope 0 at $DIR/structs.rs:+6:5: +6:21
+         nop;                             // scope 0 at $DIR/structs.rs:+6:5: +6:21
          StorageLive(_3);                 // scope 0 at $DIR/structs.rs:+6:18: +6:19
          _3 = _1;                         // scope 0 at $DIR/structs.rs:+6:18: +6:19
-         _2 = U { _foo: const 0_usize, a: move _3 }; // scope 0 at $DIR/structs.rs:+6:5: +6:21
+         _4 = const 0_usize;              // scope 0 at $DIR/structs.rs:+6:5: +6:21
+         _5 = move _3;                    // scope 0 at $DIR/structs.rs:+6:5: +6:21
+         nop;                             // scope 0 at $DIR/structs.rs:+6:5: +6:21
          StorageDead(_3);                 // scope 0 at $DIR/structs.rs:+6:20: +6:21
-         _0 = (_2.1: f32);                // scope 0 at $DIR/structs.rs:+6:5: +6:23
-         StorageDead(_2);                 // scope 0 at $DIR/structs.rs:+7:1: +7:2
+         _0 = _5;                         // scope 0 at $DIR/structs.rs:+6:5: +6:23
+         StorageDead(_4);                 // scope 0 at $DIR/structs.rs:+7:1: +7:2
+         StorageDead(_5);                 // scope 0 at $DIR/structs.rs:+7:1: +7:2
+         nop;                             // scope 0 at $DIR/structs.rs:+7:1: +7:2
          return;                          // scope 0 at $DIR/structs.rs:+7:2: +7:2
      }
  }
  
