- // MIR for `escaping` before ScalarReplacementOfAggregates
+ // MIR for `escaping` after ScalarReplacementOfAggregates
  
  fn escaping() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/structs.rs:+0:19: +0:19
      let _1: ();                          // in scope 0 at $DIR/structs.rs:+1:5: +1:42
      let mut _2: *const u32;              // in scope 0 at $DIR/structs.rs:+1:7: +1:41
      let _3: &u32;                        // in scope 0 at $DIR/structs.rs:+1:7: +1:41
      let _4: Escaping;                    // in scope 0 at $DIR/structs.rs:+1:8: +1:39
      let mut _5: u32;                     // in scope 0 at $DIR/structs.rs:+1:34: +1:37
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/structs.rs:+1:5: +1:42
          StorageLive(_2);                 // scope 0 at $DIR/structs.rs:+1:7: +1:41
          StorageLive(_3);                 // scope 0 at $DIR/structs.rs:+1:7: +1:41
          StorageLive(_4);                 // scope 0 at $DIR/structs.rs:+1:8: +1:39
          StorageLive(_5);                 // scope 0 at $DIR/structs.rs:+1:34: +1:37
          _5 = g() -> [return: bb1, unwind unreachable]; // scope 0 at $DIR/structs.rs:+1:34: +1:37
                                           // mir::Constant
                                           // + span: $DIR/structs.rs:78:34: 78:35
                                           // + literal: Const { ty: fn() -> u32 {g}, val: Value(<ZST>) }
      }
  
      bb1: {
          _4 = Escaping { a: const 1_u32, b: const 2_u32, c: move _5 }; // scope 0 at $DIR/structs.rs:+1:8: +1:39
          StorageDead(_5);                 // scope 0 at $DIR/structs.rs:+1:38: +1:39
          _3 = &(_4.0: u32);               // scope 0 at $DIR/structs.rs:+1:7: +1:41
          _2 = &raw const (*_3);           // scope 0 at $DIR/structs.rs:+1:7: +1:41
          _1 = f(move _2) -> [return: bb2, unwind unreachable]; // scope 0 at $DIR/structs.rs:+1:5: +1:42
                                           // mir::Constant
                                           // + span: $DIR/structs.rs:78:5: 78:6
                                           // + literal: Const { ty: fn(*const u32) {f}, val: Value(<ZST>) }
      }
  
      bb2: {
          StorageDead(_2);                 // scope 0 at $DIR/structs.rs:+1:41: +1:42
          StorageDead(_4);                 // scope 0 at $DIR/structs.rs:+1:42: +1:43
          StorageDead(_3);                 // scope 0 at $DIR/structs.rs:+1:42: +1:43
          StorageDead(_1);                 // scope 0 at $DIR/structs.rs:+1:42: +1:43
          _0 = const ();                   // scope 0 at $DIR/structs.rs:+0:19: +2:2
          return;                          // scope 0 at $DIR/structs.rs:+2:2: +2:2
      }
  }
  
