- // MIR for `main` before PromoteTemps
+ // MIR for `main` after PromoteTemps
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/ref_deref_project.rs:4:11: 4:11
      let _1: i32;                         // in scope 0 at $DIR/ref_deref_project.rs:5:5: 5:17
      let mut _2: &i32;                    // in scope 0 at $DIR/ref_deref_project.rs:5:6: 5:17
      let _3: (i32, i32);                  // in scope 0 at $DIR/ref_deref_project.rs:5:8: 5:14
+     let mut _4: &(i32, i32);             // in scope 0 at $DIR/ref_deref_project.rs:5:6: 5:17
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/ref_deref_project.rs:5:5: 5:17
          StorageLive(_2);                 // scope 0 at $DIR/ref_deref_project.rs:5:6: 5:17
-         StorageLive(_3);                 // scope 0 at $DIR/ref_deref_project.rs:5:8: 5:14
-         _3 = (const 4_i32, const 5_i32); // scope 0 at $DIR/ref_deref_project.rs:5:8: 5:14
+         _4 = const main::promoted[0];    // scope 0 at $DIR/ref_deref_project.rs:5:6: 5:17
                                           // ty::Const
-                                          // + ty: i32
-                                          // + val: Value(Scalar(0x00000004))
+                                          // + ty: &(i32, i32)
+                                          // + val: Unevaluated(WithOptConstParam { did: DefId(0:3 ~ ref_deref_project[317d]::main[0]), const_param_did: None }, [], Some(promoted[0]))
                                           // mir::Constant
-                                          // + span: $DIR/ref_deref_project.rs:5:9: 5:10
-                                          // + literal: Const { ty: i32, val: Value(Scalar(0x00000004)) }
-                                          // ty::Const
-                                          // + ty: i32
-                                          // + val: Value(Scalar(0x00000005))
-                                          // mir::Constant
-                                          // + span: $DIR/ref_deref_project.rs:5:12: 5:13
-                                          // + literal: Const { ty: i32, val: Value(Scalar(0x00000005)) }
-         _2 = &(_3.1: i32);               // scope 0 at $DIR/ref_deref_project.rs:5:6: 5:17
+                                          // + span: $DIR/ref_deref_project.rs:5:6: 5:17
+                                          // + literal: Const { ty: &(i32, i32), val: Unevaluated(WithOptConstParam { did: DefId(0:3 ~ ref_deref_project[317d]::main[0]), const_param_did: None }, [], Some(promoted[0])) }
+         _2 = &((*_4).1: i32);            // scope 0 at $DIR/ref_deref_project.rs:5:6: 5:17
          _1 = (*_2);                      // scope 0 at $DIR/ref_deref_project.rs:5:5: 5:17
-         StorageDead(_3);                 // scope 0 at $DIR/ref_deref_project.rs:5:17: 5:18
          StorageDead(_2);                 // scope 0 at $DIR/ref_deref_project.rs:5:17: 5:18
          StorageDead(_1);                 // scope 0 at $DIR/ref_deref_project.rs:5:17: 5:18
          _0 = const ();                   // scope 0 at $DIR/ref_deref_project.rs:4:11: 6:2
                                           // ty::Const
                                           // + ty: ()
                                           // + val: Value(Scalar(<ZST>))
                                           // mir::Constant
                                           // + span: $DIR/ref_deref_project.rs:4:11: 6:2
                                           // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
          return;                          // scope 0 at $DIR/ref_deref_project.rs:6:2: 6:2
      }
  }
  
