// ============================================================================
// Key Representation (HID Usage Page 0x07)
// ============================================================================

/// Normalized key codes based on HID Usage Table (Keyboard/Keypad Page 0x07)
/// Apps receive this, never raw scancodes.
#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Key {
    // Letters (0x04-0x1D)
    A = 0x04,
    B = 0x05,
    C = 0x06,
    D = 0x07,
    E = 0x08,
    F = 0x09,
    G = 0x0A,
    H = 0x0B,
    I = 0x0C,
    J = 0x0D,
    K = 0x0E,
    L = 0x0F,
    M = 0x10,
    N = 0x11,
    O = 0x12,
    P = 0x13,
    Q = 0x14,
    R = 0x15,
    S = 0x16,
    T = 0x17,
    U = 0x18,
    V = 0x19,
    W = 0x1A,
    X = 0x1B,
    Y = 0x1C,
    Z = 0x1D,

    // Numbers (0x1E-0x27)
    Num1 = 0x1E,
    Num2 = 0x1F,
    Num3 = 0x20,
    Num4 = 0x21,
    Num5 = 0x22,
    Num6 = 0x23,
    Num7 = 0x24,
    Num8 = 0x25,
    Num9 = 0x26,
    Num0 = 0x27,

    // Special keys
    Enter = 0x28,
    Escape = 0x29,
    Backspace = 0x2A,
    Tab = 0x2B,
    Space = 0x2C,
    Minus = 0x2D,
    Equal = 0x2E,
    LeftBracket = 0x2F,
    RightBracket = 0x30,
    Backslash = 0x31,
    Semicolon = 0x33,
    Quote = 0x34,
    Grave = 0x35,
    Comma = 0x36,
    Period = 0x37,
    Slash = 0x38,
    CapsLock = 0x39,

    // Function keys (0x3A-0x45)
    F1 = 0x3A,
    F2 = 0x3B,
    F3 = 0x3C,
    F4 = 0x3D,
    F5 = 0x3E,
    F6 = 0x3F,
    F7 = 0x40,
    F8 = 0x41,
    F9 = 0x42,
    F10 = 0x43,
    F11 = 0x44,
    F12 = 0x45,

    // Navigation
    PrintScreen = 0x46,
    ScrollLock = 0x47,
    Pause = 0x48,
    Insert = 0x49,
    Home = 0x4A,
    PageUp = 0x4B,
    Delete = 0x4C,
    End = 0x4D,
    PageDown = 0x4E,
    Right = 0x4F,
    Left = 0x50,
    Down = 0x51,
    Up = 0x52,

    // Modifiers
    LeftCtrl = 0xE0,
    LeftShift = 0xE1,
    LeftAlt = 0xE2,
    LeftMeta = 0xE3,
    RightCtrl = 0xE4,
    RightShift = 0xE5,
    RightAlt = 0xE6,
    RightMeta = 0xE7,

    // Escape hatch for unknown keys
    Unknown = 0xFFFF,
}

impl Key {
    /// Get human-readable name for the key
    pub fn name(self) -> &'static str {
        match self {
            Key::A => "A",
            Key::B => "B",
            Key::C => "C",
            Key::D => "D",
            Key::E => "E",
            Key::F => "F",
            Key::G => "G",
            Key::H => "H",
            Key::I => "I",
            Key::J => "J",
            Key::K => "K",
            Key::L => "L",
            Key::M => "M",
            Key::N => "N",
            Key::O => "O",
            Key::P => "P",
            Key::Q => "Q",
            Key::R => "R",
            Key::S => "S",
            Key::T => "T",
            Key::U => "U",
            Key::V => "V",
            Key::W => "W",
            Key::X => "X",
            Key::Y => "Y",
            Key::Z => "Z",
            Key::Num1 => "1",
            Key::Num2 => "2",
            Key::Num3 => "3",
            Key::Num4 => "4",
            Key::Num5 => "5",
            Key::Num6 => "6",
            Key::Num7 => "7",
            Key::Num8 => "8",
            Key::Num9 => "9",
            Key::Num0 => "0",
            Key::Enter => "Enter",
            Key::Escape => "Esc",
            Key::Backspace => "Bksp",
            Key::Tab => "Tab",
            Key::Space => "Space",
            Key::Minus => "-",
            Key::Equal => "=",
            Key::LeftBracket => "[",
            Key::RightBracket => "]",
            Key::Backslash => "\\",
            Key::Semicolon => ";",
            Key::Quote => "'",
            Key::Grave => "`",
            Key::Comma => ",",
            Key::Period => ".",
            Key::Slash => "/",
            Key::CapsLock => "Caps",
            Key::F1 => "F1",
            Key::F2 => "F2",
            Key::F3 => "F3",
            Key::F4 => "F4",
            Key::F5 => "F5",
            Key::F6 => "F6",
            Key::F7 => "F7",
            Key::F8 => "F8",
            Key::F9 => "F9",
            Key::F10 => "F10",
            Key::F11 => "F11",
            Key::F12 => "F12",
            Key::PrintScreen => "PrtSc",
            Key::ScrollLock => "ScrLk",
            Key::Pause => "Pause",
            Key::Insert => "Ins",
            Key::Home => "Home",
            Key::PageUp => "PgUp",
            Key::Delete => "Del",
            Key::End => "End",
            Key::PageDown => "PgDn",
            Key::Right => "Right",
            Key::Left => "Left",
            Key::Down => "Down",
            Key::Up => "Up",
            Key::LeftCtrl => "LCtrl",
            Key::LeftShift => "LShift",
            Key::LeftAlt => "LAlt",
            Key::LeftMeta => "LMeta",
            Key::RightCtrl => "RCtrl",
            Key::RightShift => "RShift",
            Key::RightAlt => "RAlt",
            Key::RightMeta => "RMeta",
            Key::Unknown => "?",
        }
    }

    /// Convert from raw u16 value
    pub fn from_raw(value: u16) -> Self {
        // Safety: we validate known values, unknown becomes Unknown
        match value {
            0x04 => Key::A,
            0x05 => Key::B,
            0x06 => Key::C,
            0x07 => Key::D,
            0x08 => Key::E,
            0x09 => Key::F,
            0x0A => Key::G,
            0x0B => Key::H,
            0x0C => Key::I,
            0x0D => Key::J,
            0x0E => Key::K,
            0x0F => Key::L,
            0x10 => Key::M,
            0x11 => Key::N,
            0x12 => Key::O,
            0x13 => Key::P,
            0x14 => Key::Q,
            0x15 => Key::R,
            0x16 => Key::S,
            0x17 => Key::T,
            0x18 => Key::U,
            0x19 => Key::V,
            0x1A => Key::W,
            0x1B => Key::X,
            0x1C => Key::Y,
            0x1D => Key::Z,
            0x1E => Key::Num1,
            0x1F => Key::Num2,
            0x20 => Key::Num3,
            0x21 => Key::Num4,
            0x22 => Key::Num5,
            0x23 => Key::Num6,
            0x24 => Key::Num7,
            0x25 => Key::Num8,
            0x26 => Key::Num9,
            0x27 => Key::Num0,
            0x28 => Key::Enter,
            0x29 => Key::Escape,
            0x2A => Key::Backspace,
            0x2B => Key::Tab,
            0x2C => Key::Space,
            0x2D => Key::Minus,
            0x2E => Key::Equal,
            0x2F => Key::LeftBracket,
            0x30 => Key::RightBracket,
            0x31 => Key::Backslash,
            0x33 => Key::Semicolon,
            0x34 => Key::Quote,
            0x35 => Key::Grave,
            0x36 => Key::Comma,
            0x37 => Key::Period,
            0x38 => Key::Slash,
            0x39 => Key::CapsLock,
            0x3A => Key::F1,
            0x3B => Key::F2,
            0x3C => Key::F3,
            0x3D => Key::F4,
            0x3E => Key::F5,
            0x3F => Key::F6,
            0x40 => Key::F7,
            0x41 => Key::F8,
            0x42 => Key::F9,
            0x43 => Key::F10,
            0x44 => Key::F11,
            0x45 => Key::F12,
            0x46 => Key::PrintScreen,
            0x47 => Key::ScrollLock,
            0x48 => Key::Pause,
            0x49 => Key::Insert,
            0x4A => Key::Home,
            0x4B => Key::PageUp,
            0x4C => Key::Delete,
            0x4D => Key::End,
            0x4E => Key::PageDown,
            0x4F => Key::Right,
            0x50 => Key::Left,
            0x51 => Key::Down,
            0x52 => Key::Up,
            0xE0 => Key::LeftCtrl,
            0xE1 => Key::LeftShift,
            0xE2 => Key::LeftAlt,
            0xE3 => Key::LeftMeta,
            0xE4 => Key::RightCtrl,
            0xE5 => Key::RightShift,
            0xE6 => Key::RightAlt,
            0xE7 => Key::RightMeta,
            _ => Key::Unknown,
        }
    }
}
