//@ check-pass

thread_local! {
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    pub static LONG_DOCS: () = ();

    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    /// I love doc comments.
    #[allow(unused_mut, reason = "testing")]
    pub static LONG_DOCS_2: () = ();
}

fn main() {}
