- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/array_index.rs:+0:11: +0:11
      let _1: u32;                         // in scope 0 at $DIR/array_index.rs:+1:9: +1:10
      let mut _2: [u32; 4];                // in scope 0 at $DIR/array_index.rs:+1:18: +1:30
      let _3: usize;                       // in scope 0 at $DIR/array_index.rs:+1:31: +1:32
      let mut _4: usize;                   // in scope 0 at $DIR/array_index.rs:+1:18: +1:33
      let mut _5: bool;                    // in scope 0 at $DIR/array_index.rs:+1:18: +1:33
      scope 1 {
          debug x => _1;                   // in scope 1 at $DIR/array_index.rs:+1:9: +1:10
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/array_index.rs:+1:9: +1:10
          StorageLive(_2);                 // scope 0 at $DIR/array_index.rs:+1:18: +1:30
          _2 = [const 0_u32, const 1_u32, const 2_u32, const 3_u32]; // scope 0 at $DIR/array_index.rs:+1:18: +1:30
          StorageLive(_3);                 // scope 0 at $DIR/array_index.rs:+1:31: +1:32
          _3 = const 2_usize;              // scope 0 at $DIR/array_index.rs:+1:31: +1:32
-         _4 = Len(_2);                    // scope 0 at $DIR/array_index.rs:+1:18: +1:33
-         _5 = Lt(_3, _4);                 // scope 0 at $DIR/array_index.rs:+1:18: +1:33
-         assert(_5, "index out of bounds: the length is {} but the index is {}", _4, _3) -> bb1; // scope 0 at $DIR/array_index.rs:+1:18: +1:33
+         _4 = const 4_usize;              // scope 0 at $DIR/array_index.rs:+1:18: +1:33
+         _5 = const true;                 // scope 0 at $DIR/array_index.rs:+1:18: +1:33
+         assert(const true, "index out of bounds: the length is {} but the index is {}", _4, _3) -> bb1; // scope 0 at $DIR/array_index.rs:+1:18: +1:33
      }
  
      bb1: {
-         _1 = _2[_3];                     // scope 0 at $DIR/array_index.rs:+1:18: +1:33
+         _1 = const 2_u32;                // scope 0 at $DIR/array_index.rs:+1:18: +1:33
          StorageDead(_3);                 // scope 0 at $DIR/array_index.rs:+1:33: +1:34
          StorageDead(_2);                 // scope 0 at $DIR/array_index.rs:+1:33: +1:34
          _0 = const ();                   // scope 0 at $DIR/array_index.rs:+0:11: +2:2
          StorageDead(_1);                 // scope 0 at $DIR/array_index.rs:+2:1: +2:2
          return;                          // scope 0 at $DIR/array_index.rs:+2:2: +2:2
      }
  }
  
