- // MIR for `main` before ConstProp
+ // MIR for `main` after ConstProp
  
  fn main() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/array_index.rs:4:11: 4:11
      let _1: u32;                         // in scope 0 at $DIR/array_index.rs:5:9: 5:10
      scope 1 {
          debug x => _1;                   // in scope 1 at $DIR/array_index.rs:5:9: 5:10
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/array_index.rs:5:9: 5:10
          _1 = const 2_u32;                // scope 0 at $DIR/array_index.rs:5:18: 5:33
          _0 = const ();                   // scope 0 at $DIR/array_index.rs:4:11: 6:2
          StorageDead(_1);                 // scope 0 at $DIR/array_index.rs:6:1: 6:2
          return;                          // scope 0 at $DIR/array_index.rs:6:2: 6:2
      }
  }
  
