- // MIR for `add` before ConstProp
+ // MIR for `add` after ConstProp
  
  fn add() -> u32 {
      let mut _0: u32;                     // return place in scope 0 at $DIR/return_place.rs:5:13: 5:16
      let mut _1: (u32, bool);             // in scope 0 at $DIR/return_place.rs:6:5: 6:10
  
      bb0: {
-         _1 = CheckedAdd(const 2_u32, const 2_u32); // scope 0 at $DIR/return_place.rs:6:5: 6:10
-         assert(!move (_1.1: bool), "attempt to compute `{} + {}`, which would overflow", const 2_u32, const 2_u32) -> bb1; // scope 0 at $DIR/return_place.rs:6:5: 6:10
+         _1 = const (4_u32, false);       // scope 0 at $DIR/return_place.rs:6:5: 6:10
+         assert(!const false, "attempt to compute `{} + {}`, which would overflow", const 2_u32, const 2_u32) -> bb1; // scope 0 at $DIR/return_place.rs:6:5: 6:10
      }
  
      bb1: {
-         _0 = move (_1.0: u32);           // scope 0 at $DIR/return_place.rs:6:5: 6:10
+         _0 = const 4_u32;                // scope 0 at $DIR/return_place.rs:6:5: 6:10
          return;                          // scope 0 at $DIR/return_place.rs:7:2: 7:2
      }
  }
  
